.changeset/tasty-knives-confess.md
sites/geohub/src/routes/(app)/data/[id]/edit/+page.server.ts
sites/geohub/src/routes/api/datasets/+server.ts
sites/geohub/static/api/swagger/spec.yaml

fixes #2692
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1280863424) by [Unito](https://www.unito.io)

fix: created /api/datasets POST method to register/update dataset info. Call new API in dataset edit page.

---

.changeset/mean-rocks-remember.md
sites/geohub/src/components/header/Header.svelte
sites/geohub/src/routes/+error.svelte
sites/static-image-api/src/routes/(app)/+layout.svelte

fixes #2711
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1281583403) by [Unito](https://www.unito.io)

fix: changed header's region text to capitalised and shorter subtitle

---

.changeset/fast-vans-perform.md
sites/geohub/src/components/maplibre/vector/VectorParamsPanel.svelte
sites/geohub/src/components/maplibre/vector/VectorSimulationArgument.svelte
sites/geohub/src/lib/types/RangeSliderConfig.ts
sites/geohub/src/lib/types/index.ts

fixes #2710
redesigned simulation component
for names and units of arguments, need to update postgres functions.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1281718323) by [Unito](https://www.unito.io)

fix: redesigned vector simulation component layout.

---

.changeset/chilled-items-behave.md
sites/geohub/src/components/maplibre/vector/VectorSimulationArgument.svelte

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1281830527) by [Unito](https://www.unito.io)

fix: not show minus (-) symbol for zero value in simulation feature

---

.changeset/neat-goats-cheat.md
sites/geohub/src/components/maplibre/vector/VectorSimulationArgument.svelte

fixed hovered color for simulation component
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1283245168) by [Unito](https://www.unito.io)

fix: adjusted hovered color for simulation

---

backends/k8s/cogserver/yaml/cogserver-deployment.yaml
backends/k8s/titiler/yaml/titiler-deployment.yaml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1283366331) by [Unito](https://www.unito.io)

adjust services CPU and RAM

---

.github/workflows/ci.yml
backends/k8s/cogserver/yaml/cogserver-deployment.yaml
backends/k8s/titiler/yaml/titiler-deployment.yaml

Reverts UNDP-Data/geohub#2731
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1283465124) by [Unito](https://www.unito.io)

Revert changes made in #2730 and #2731

---

.changeset/heavy-deers-roll.md

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1285165712) by [Unito](https://www.unito.io)

first release of svelte-maplibre-storymap

---

.changeset/fresh-crabs-smoke.md
sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
sites/geohub/src/components/pages/data/datasets/PublishedDatasetDeleteDialog.svelte
sites/geohub/src/components/pages/data/datasets/UserPermission.svelte
sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
sites/geohub/src/components/pages/map/data/StacExplorerButton.svelte
sites/geohub/src/components/pages/map/plugins/StyleShare.svelte
sites/geohub/src/components/util/Modal.svelte
sites/geohub/src/components/util/ModalTemplate.svelte
sites/geohub/src/routes/(app)/data/[id]/edit/+page.svelte
sites/geohub/src/routes/(app)/management/stac/+page.svelte
sites/geohub/src/routes/(map)/maps/+layout.svelte
sites/geohub/src/routes/(map)/maps/[id]/+page.svelte

fixes #2745 
fixes #2749
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1286825841) by [Unito](https://www.unito.io)

fix: removed headerfooter from modal. fixed z-index of modal for bug of modal background

---

.changeset/pink-jokes-live.md
pnpm-lock.yaml
sites/geohub/package.json
sites/geohub/src/components/maplibre/heatmap/HeatmapColorRow.svelte

Reverts UNDP-Data/geohub#2751
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1287753221) by [Unito](https://www.unito.io)

Revert "chore(deps): update dependency svelte-awesome-color-picker to v3"

---

.changeset/light-clouds-impress.md
sites/geohub/src/components/pages/data/datasets/UserPermission.svelte
sites/geohub/src/routes/(app)/data/[id]/+page.svelte
sites/geohub/src/routes/(map)/maps/[id]/+page.svelte
sites/geohub/src/routes/+error.svelte

* introduced tabs to a map page
* added GUI of user permission for a map page as permission tab
* remember active tab for a dataset page or a map page
prior to do the above, refactored UserPermission component to be able to handle both style and dataset permission
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1288640052) by [Unito](https://www.unito.io)

feat: introduced tabs to a map page, and added GUI to edit map permissions. Also remember active tab state as hash at a dataset page and a map page

---

.changeset/many-lobsters-buy.md
sites/geohub/src/routes/(map)/maps/[id]/+page.server.ts
sites/geohub/src/routes/api/style/+server.ts

I found private maps are not shown for superusers.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1288701520) by [Unito](https://www.unito.io)

 fix: show all styles for superuser

---

backends/k8s/cogserver-dev/yaml/cogserver-dev-deployment.yaml
backends/k8s/cogserver/yaml/cogserver-deployment.yaml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1289045461) by [Unito](https://www.unito.io)

set concurrency and workers per core for cogserver

---

docker/docker-compose.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1289411314) by [Unito](https://www.unito.io)

fix: bump cogserver version at docker-compose.yml

---

docker/docker-compose.yml

I did stupid mistake...
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1289420843) by [Unito](https://www.unito.io)

fix: cogserver version at docker-compose.yml

---

.changeset/olive-suns-tease.md
sites/geohub/src/routes/api/style/+server.ts
sites/geohub/src/routes/api/style/[id]/+server.ts

there was a bug of checking permission in style apis. I simplified the logic of PUT and DELETE method. Also fixed error handling.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1289453347) by [Unito](https://www.unito.io)

fix: fixed bug of style api to edit maps with write/owner permission

---

.github/workflows/ci.yml

* [ x] Code is up-to-date with the `develop` branch
* [x ] No build errors after `pnpm build`
* [ x] No lint errors after `pnpm lint`
* [x ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`
* [x ] Make sure all the existing features working well
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1289547886) by [Unito](https://www.unito.io)

added cicd for cogserver production

---

.github/workflows/ci.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1289688085) by [Unito](https://www.unito.io)

fix: removed ref equal main for geohub building from ci.yml

---

backends/k8s/cogserver/yaml/cogserver-deployment.yaml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1290218561) by [Unito](https://www.unito.io)

set riotiler threads to 1

---

.changeset/eighty-pugs-notice.md
sites/geohub/src/components/maplibre/raster/RasterAlgorithmParameter.svelte
sites/geohub/src/components/maplibre/raster/RasterAlgorithms.svelte
sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
sites/geohub/src/components/maplibre/raster/RasterSimpleLegend.svelte
sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
sites/geohub/src/components/pages/map/layers/raster/RasterSimpleLayer.svelte
sites/geohub/src/components/util/NumberInput.svelte
sites/geohub/src/lib/helper/getValueFromRasterTileUrl.ts
sites/geohub/src/lib/server/helpers/createDatasetLinks.ts
sites/geohub/src/lib/types/RasterAlgorithm.ts
sites/geohub/src/lib/types/index.ts
sites/geohub/src/routes/api/datasets/[id]/style/[layer]/[type]/+server.ts

closes #2761
* added an accordion to switch titiler algorithm
* show preview image in simple legend for algorithm and true color layer
* replace titiler URL to server setting if saved style's titiler URL is different
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1289756966) by [Unito](https://www.unito.io)

feat: add titiler algorithms

---

.changeset/calm-socks-hope.md
sites/geohub/src/components/maplibre/raster/RasterSimpleLegend.svelte

applied parameters value for simple legend
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1290387333) by [Unito](https://www.unito.io)

fix: apply algorithm_params for simple raster legend

---

.changeset/twelve-tips-fry.md
sites/geohub/src/components/maplibre/hillshade/Hillshade.svelte
sites/geohub/src/components/maplibre/hillshade/HillshadeAccentColor.svelte
sites/geohub/src/components/maplibre/hillshade/HillshadeExaggeration.svelte
sites/geohub/src/components/maplibre/hillshade/HillshadeHighlightColor.svelte
sites/geohub/src/components/maplibre/hillshade/HillshadeIlluminationDirection.svelte
sites/geohub/src/components/maplibre/hillshade/HillshadeShadowColor.svelte
sites/geohub/src/components/maplibre/raster/RasterAlgorithms.svelte
sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
sites/geohub/src/components/maplibre/raster/RasterLegendEdit.svelte
sites/geohub/src/components/maplibre/raster/RasterSimpleLegend.svelte
sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
sites/geohub/src/components/pages/map/layers/LayerList.svelte
sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
sites/geohub/src/lib/RasterTileData.ts
sites/geohub/src/lib/VectorTileData.ts
sites/geohub/src/lib/helper/getLayerStyle.ts
sites/geohub/src/lib/helper/getValueFromRasterTileUrl.ts
sites/geohub/src/lib/helper/updateParamsInURL.ts
sites/geohub/src/lib/types/LayerCreationInfo.ts

fixes #2803
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1290506886) by [Unito](https://www.unito.io)

fix: add terrarium and terrainrgb algorithm as raster dem source / hillshade layer

---

.changeset/wicked-dingos-sparkle.md
sites/geohub/src/components/pages/data/datasets/UserPermission.svelte

fixes #2800
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1293139476) by [Unito](https://www.unito.io)

fix: add title of Authorized users in permission table

---

.changeset/strong-moons-prove.md
sites/geohub/src/lib/server/helpers/getStyleById.ts

fixes #2826 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1297371846) by [Unito](https://www.unito.io)

fix: replace titiler endpoint in saved map to the server settings one to avoid connecting to the wrong titiler endpoint.

---

pnpm-lock.yaml
sites/geohub/package.json

Reverts UNDP-Data/geohub#2839
it shows the below error in hooks.server.ts. want to revert @auth/sveltekit
```shell
2024-02-09T10:36:54.064036029Z 10:36:54 2|geohub  | TypeError: handle2 is not a function
2024-02-09T10:36:54.064673230Z 10:36:54 2|geohub  |     at apply_handle (file:///home/site/wwwroot/server/chunks/hooks.server--n7W3pDe.js:25:14)
2024-02-09T10:36:54.074591437Z 10:36:54 2|geohub  |     at resolve (file:///home/site/wwwroot/server/chunks/hooks.server--n7W3pDe.js:39:35)
2024-02-09T10:36:54.074611837Z 10:36:54 2|geohub  |     at handlePrimary (file:///home/site/wwwroot/server/chunks/hooks.server--n7W3pDe.js:212:10)
2024-02-09T10:36:54.074617837Z 10:36:54 2|geohub  |     at apply_handle (file:///home/site/wwwroot/server/chunks/hooks.server--n7W3pDe.js:25:14) …
```

Revert "chore(deps): update dependency @auth/sveltekit to ^0.12.0"

---

.changeset/red-phones-rescue.md
sites/geohub/src/components/pages/map/plugins/MaplibreLegendControl.svelte
sites/geohub/src/lib/server/helpers/getStyleById.ts
sites/geohub/src/routes/(map)/maps/[id]/+page.svelte

fixes #2831 
* delete layers and sources which are not registered to the database (`/api/style/{id}` api)
* hide open button if layer is not in saved style
* show warning message to delete map if saved map is empty
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1300325533) by [Unito](https://www.unito.io)

fix: remove deleted dataset's layers and source from saved map. hide open button if layers do not exist and show warning message.

---

.changeset/warm-camels-unite.md
sites/geohub/src/components/maplibre/raster/RasterAlgorithms.svelte
sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
sites/geohub/src/components/maplibre/raster/RasterLegendEdit.svelte

fixes #2845
there was issue switching between non-algorithm and algorithm type
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1300396445) by [Unito](https://www.unito.io)

fix: export algorithmId in RasterAlgorithms component to reinitialize layer correctly when algorithm is changed.

---

.changeset/clever-hornets-film.md
sites/geohub/src/routes/(map)/maps/[id]/+page.server.ts
sites/geohub/src/routes/(map)/maps/[id]/edit/+page.server.ts

fixes #2852
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1300456456) by [Unito](https://www.unito.io)

fix: make private map edit page accessible for superuser

---

.changeset/chilly-sloths-perform.md
sites/geohub/src/components/maplibre/raster/RasterAlgorithms.svelte
sites/geohub/src/components/maplibre/raster/RasterLegend.svelte

fixes #2849 
fixes #2850 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1300488972) by [Unito](https://www.unito.io)

fix: changed algorithm accordion title and field labels

---

.changeset/flat-lamps-grin.md
sites/geohub/src/components/maplibre/raster/RasterAlgorithmParameter.svelte
sites/geohub/src/components/maplibre/vector/VectorSimulationArgument.svelte

fixes #2848 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1300524395) by [Unito](https://www.unito.io)

fix: changed colors of vector simulation and raster algorithm when hovering, expanding, and activating

---

.changeset/tiny-knives-buy.md
sites/geohub/src/components/maplibre/raster/RasterAlgorithmParameter.svelte
sites/geohub/src/components/maplibre/vector/VectorSimulationArgument.svelte

fixes #2858
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1301294315) by [Unito](https://www.unito.io)

fix: changed font weight of parameter title to semibold when it is expanded or activated

---

.changeset/cold-feet-count.md
pnpm-lock.yaml
sites/geohub/package.json
sites/geohub/src/components/maplibre/LegendColorMapRow.svelte
sites/geohub/src/components/maplibre/MaplibreColorPicker.svelte
sites/geohub/src/components/util/ColorPicker.svelte

closes #2765
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1302110011) by [Unito](https://www.unito.io)

chore: migrated svelte color picker from v2 to v3

---

.changeset/breezy-rocks-exist.md
.changeset/chilled-badgers-sort.md
.changeset/gentle-owls-shout.md
packages/svelte-static-image-controls/src/lib/MaplibreStaticImageControl.svelte
sites/geohub/src/components/pages/data/datasets/DatasetPreview.svelte
sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
sites/geohub/src/components/pages/data/datasets/PublishedDataset.svelte
sites/geohub/src/components/pages/data/datasets/PublishedDatasetDeleteDialog.svelte
sites/geohub/src/components/pages/data/ingesting/DataUploadButton.svelte
sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
sites/geohub/src/components/pages/data/ingesting/IngestingDatasets.svelte
sites/geohub/src/components/pages/home/ExploreDatasets.svelte
sites/geohub/src/components/pages/map/data/AddLayerButton.svelte
sites/geohub/src/components/pages/map/plugins/StyleShare.svelte
sites/geohub/src/components/util/AccessLevelSwitcher.svelte
sites/geohub/src/components/util/Modal.svelte
sites/geohub/src/components/util/Star.svelte
sites/geohub/src/components/util/stac/StacCatalogItem.svelte
sites/geohub/src/components/util/stac/StacCollectionMap.svelte
sites/geohub/src/routes/(app)/+page.svelte
sites/geohub/src/routes/(app)/data/+page.svelte
sites/geohub/src/routes/(app)/data/[id]/edit/+page.svelte
sites/geohub/src/routes/(app)/data/upload/+page.svelte
sites/geohub/src/routes/(app)/management/stac/+page.svelte
sites/geohub/src/routes/(app)/management/stac/api/[id]/+page.svelte
sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte
sites/geohub/src/routes/(app)/settings/+page.svelte
sites/geohub/src/routes/(auth)/auth/signIn/+page.svelte
sites/geohub/src/routes/(map)/maps/+layout.svelte
sites/geohub/src/routes/(map)/maps/[id]/+page.svelte

fixes #2878 
* basically applied `is-uppercase` and `has-text-weight-bold` for all buttons
* some buttons like for landing page, they keep `is-large` size.
* also, icons were removed from all buttons except few of them (like star button)
* for toggle button, just changed primary color to `is-link`
* fixed export button style in static api control.
if I missed to change some buttons, please excuse me.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1303229956) by [Unito](https://www.unito.io)

fix: button style

---

.github/ISSUE_TEMPLATE/ui_ux_issue.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1303535203) by [Unito](https://www.unito.io)

doc: added UI/UX issue template

---

.changeset/metal-suits-call.md
packages/svelte-undp-design/src/lib/Card/Card.svelte
packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.svelte
packages/svelte-undp-design/src/lib/css/content-card.min.css

fixes #2890
* there is a conflict of class name 'card' between bulma and undp design, thus changed undp's class name to undp-card. 
* removed border-top's black stripe if no tag is specified.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1303934932) by [Unito](https://www.unito.io)

fix: card style

---

packages/svelte-sidebar/src/lib/Sidebar.svelte

I found the position of close button in sidebar was collapsed. fixed it.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1304003919) by [Unito](https://www.unito.io)

fix: adjusted the position of close button in sidebar.

---

.changeset/strange-rockets-wash.md
sites/geohub/src/components/pages/data/datasets/DatasetMapView.svelte
sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
sites/geohub/src/routes/(app)/settings/+page.svelte

closes #2368
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1304669291) by [Unito](https://www.unito.io)

feat: added map view to explore datasets

---

.changeset/mean-meals-smell.md
sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
sites/geohub/src/components/pages/map/layers/header/VisibilityButton.svelte

fixes #2908
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1304732310) by [Unito](https://www.unito.io)

fix: adjusted spaces between layer menu buttons

---

.changeset/heavy-papayas-remember.md
sites/geohub/src/components/pages/home/ExploreDatasets.svelte
sites/geohub/src/components/pages/map/layers/LayerList.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorFilter.svelte
sites/geohub/src/routes/(app)/+page.svelte
sites/geohub/src/routes/(app)/data/+page.svelte

fixes #2904
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1304785131) by [Unito](https://www.unito.io)

fix: changed large buttons on landing page and data page to normal size. fixed button style in vector filter

---

.changeset/nice-lamps-fail.md
sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
sites/geohub/src/components/pages/home/MapStyleCardList.svelte
sites/geohub/src/components/util/AccessLevelSwitcher.svelte
sites/geohub/src/components/util/SegmentButtons.svelte
sites/geohub/src/components/util/stac/StacApiExplorer.svelte
sites/geohub/src/components/util/stac/StacCollectionMap.svelte
sites/geohub/src/routes/(app)/data/[id]/edit/+page.svelte
sites/geohub/src/routes/(app)/settings/+page.svelte

fixes #2905
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1304901557) by [Unito](https://www.unito.io)

fix: segment button design

---

sites/geohub/src/components/util/stac/StacApiExplorer.svelte

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1304923439) by [Unito](https://www.unito.io)

refactor: fixed import of SegmentButtons component

---

.changeset/yellow-bugs-dance.md
sites/geohub/src/components/pages/home/DashboardContents.svelte
sites/geohub/src/hooks.server.ts
sites/geohub/src/lib/config/AppConfig/FooterItems.ts
sites/geohub/src/routes/(app)/+page.svelte
sites/geohub/src/routes/(app)/dashboards/+page.svelte
sites/geohub/src/routes/(app)/dashboards/+page.ts
sites/geohub/src/routes/(app)/maps/+page.ts
sites/geohub/src/routes/(map)/dashboards/electricity/+page.ts
sites/geohub/src/routes/(map)/maps/[id]/edit/+page.ts
sites/geohub/src/routes/(map)/maps/edit/+page.ts

* introduced new dashboard page at /dashboards
* enabled SSR for Electricity Dashboard
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1305840190) by [Unito](https://www.unito.io)

feat: created /dashboards endpoint to manage dashboard page, enabled SSR for Electricity Dashboard

---

sites/static-image-api/src/routes/api/og/+server.ts
sites/static-image-api/static/api/swagger/spec.yaml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1305889467) by [Unito](https://www.unito.io)

fix: allow no content to create og image in static image api.

---

.changeset/honest-dingos-give.md
sites/geohub/src/routes/+layout.server.ts

fixes #2936
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1306254445) by [Unito](https://www.unito.io)

fix: removed content text from social card image

---

.changeset/rotten-clouds-protect.md
packages/svelte-undp-design/src/lib/Header/Header.svelte

fixes #2940
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1306320259) by [Unito](https://www.unito.io)

fix: show all menu items in UNDP header

---

.changeset/three-trainers-behave.md
sites/geohub/src/routes/(app)/+page.svelte

fixes #2939
also applied same css for other hero
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1306345604) by [Unito](https://www.unito.io)

fix: fixed layout of hero in landing page

---

.changeset/odd-carrots-brush.md
.changeset/six-bears-leave.md
packages/undp-bulma/bulma.scss
sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorLabelPanel.svelte
sites/geohub/src/components/util/Accordion.svelte
sites/geohub/src/components/util/FloatingPanel.svelte
sites/geohub/src/routes/(app)/+page.svelte

fixes #2941 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1306393810) by [Unito](https://www.unito.io)

fix: layer editor style and changed grey-darker color in undp-bulma

---

.changeset/wet-cougars-notice.md
sites/geohub/src/components/util/Tabs.svelte

fixes #2952
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1306420419) by [Unito](https://www.unito.io)

fix: enabled horizontal scroll for Tabs component.

---

sites/geohub/src/lib/config/AppConfig/HeaderItems.ts

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1306524006) by [Unito](https://www.unito.io)

fix: rename Map to Maps in HeaderItems.ts

---

.changeset/quiet-toys-build.md
sites/geohub/src/routes/(app)/+page.svelte

fixes #2939
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1307134844) by [Unito](https://www.unito.io)

fix: set max-width: 768px for hero text width

---

.changeset/five-balloons-complain.md
sites/geohub/src/components/maplibre/raster/RasterAlgorithmParameter.svelte
sites/geohub/src/lib/types/RasterAlgorithm.ts

if boolean argment, it will show toggle button
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1310016210) by [Unito](https://www.unito.io)

fix: show toggle button for boolean parameter

---

.changeset/fast-hotels-think.md
.changeset/many-camels-pump.md
packages/svelte-undp-design/src/lib/Card/Card.svelte
sites/geohub/src/components/maplibre/raster/RasterAlgorithmExplorer.svelte
sites/geohub/src/components/maplibre/raster/RasterAlgorithmSelector.svelte
sites/geohub/src/components/maplibre/raster/RasterAlgorithms.svelte
sites/geohub/src/components/maplibre/raster/RasterClassifyLegend.svelte
sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
sites/geohub/src/components/maplibre/raster/RasterLegendEdit.svelte
sites/geohub/src/components/maplibre/raster/RasterRescale.svelte
sites/geohub/src/components/maplibre/raster/RasterSimpleLegend.svelte
sites/geohub/src/components/pages/map/data/AddLayerButton.svelte
sites/geohub/src/components/pages/map/data/DataCard.svelte
sites/geohub/src/components/pages/map/data/RasterAlgorithmExplorerButton.svelte
sites/geohub/src/components/pages/map/data/StacExplorerButton.svelte
sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte
sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
sites/geohub/src/lib/RasterTileData.ts
sites/geohub/src/lib/config/AppConfig/TabNames.ts
sites/geohub/src/lib/helper/getValueFromRasterTileUrl.ts
sites/geohub/src/lib/types/RasterAlgorithm.ts
sites/geohub/src/routes/(app)/data/[id]/+page.svelte
sites/geohub/src/routes/api/stac/[id]/[collection]/[...item]/[asset]/+server.ts

fixes #2969
* data tab in map page
* tools tab in dataset page
* after adding tool
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1311831882) by [Unito](https://www.unito.io)

fix: redesign algo components

---

.changeset/new-carrots-explode.md
sites/geohub/src/components/util/BackToTop.svelte

current back to button is a bit hidden at the bottom-right corner of browser, I moved the position to the top-center of browser.
after 5 seconds, it will be hidden. once scroll end and if position is not top of page, it will be shown again.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1312530719) by [Unito](https://www.unito.io)

fix: improved UI and behaviour of back to top button

---

.changeset/nine-suits-cover.md
sites/geohub/src/components/header/UserAccount.svelte

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1312543410) by [Unito](https://www.unito.io)

fix: close user account popup if clicked menu

---

sites/geohub/src/routes/api/datasets/+server.ts

forgot to remove console.log
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1315136944) by [Unito](https://www.unito.io)

fix: Update /api/datasets/+server.ts to remove console.log

---

.changeset/fair-flowers-thank.md
sites/geohub/src/app.html

I think it can make page loading faster if it does not load all links' source code in advance
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1315341826) by [Unito](https://www.unito.io)

fix: remove  from app.html

---

.changeset/eighty-wolves-learn.md
sites/geohub/src/components/maplibre/raster/RasterAlgorithmExplorer.svelte
sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
sites/geohub/src/lib/config/AppConfig/FooterItems.ts
sites/geohub/src/routes/(app)/+page.svelte
sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.svelte
sites/geohub/src/routes/(app)/tools/+page.server.ts
sites/geohub/src/routes/(app)/tools/+page.svelte
sites/geohub/src/routes/(app)/tools/+page.ts

fixes #2968
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1315325265) by [Unito](https://www.unito.io)

feat: add `/tools` page to allow users to explore datasets by tools

---

backends/k8s/cogserver-dev/yaml/cogserver-dev-deployment.yaml
backends/k8s/cogserver/yaml/cogserver-deployment.yaml

Reverts UNDP-Data/geohub#3022
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1316171825) by [Unito](https://www.unito.io)

Revert "[RELEASE] cogserver"

---

.github/workflows/ci.yml

because users outside of UNDP cannot access to Azure Container Registry in docker-compose, deploy image to both Azure and GitHub.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1316865458) by [Unito](https://www.unito.io)

deploy docker image of static api to GHCR too

---

.changeset/few-ladybugs-drop.md
packages/svelte-undp-design/.storybook/main.ts
packages/svelte-undp-design/src/lib/Accordion/Accordion.stories.ts
packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.stories.ts
packages/svelte-undp-design/src/lib/Button/Button.stories.ts
packages/svelte-undp-design/src/lib/Card/Card.stories.ts
packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.stories.ts
packages/svelte-undp-design/src/lib/Checkbox/Checkbox.stories.ts
packages/svelte-undp-design/src/lib/CtaLink/CtaLink.stories.ts
packages/svelte-undp-design/src/lib/DefaultLink/DefaultLink.stories.ts
packages/svelte-undp-design/src/lib/Download/Download.stories.ts
packages/svelte-undp-design/src/lib/FluidCarousel/FluidCarousel.stories.ts
packages/svelte-undp-design/src/lib/Footer/Footer.stories.ts
packages/svelte-undp-design/src/lib/Header/Header.stories.ts
packages/svelte-undp-design/src/lib/Introduction.mdx
packages/svelte-undp-design/src/lib/Loader/Loader.stories.ts
packages/svelte-undp-design/src/lib/MultiSelect/MultiSelect.stories.ts
packages/svelte-undp-design/src/lib/Pagination/Pagination.stories.ts
packages/svelte-undp-design/src/lib/Radios/Radios.stories.ts
packages/svelte-undp-design/src/lib/SearchExpand/SearchExpand.stories.ts
packages/svelte-undp-design/src/lib/Select/Select.stories.ts
packages/svelte-undp-design/src/lib/Sidebar/Sidebar.stories.ts
packages/svelte-undp-design/src/lib/Stats/Stats.stories.ts
packages/svelte-undp-design/src/lib/Tabs/Tabs.stories.ts
packages/svelte-undp-design/src/lib/TextInput/TextInput.stories.ts
sites/geohub/src/lib/config/AppConfig/FooterItems.ts

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1317756338) by [Unito](https://www.unito.io)

doc: Add componentslink to footer

---

.changeset/real-birds-march.md
.changeset/silent-fireants-wash.md
packages/svelte-undp-components/src/lib/components/SegmentButtons.stories.ts
packages/svelte-undp-components/src/lib/components/SegmentButtons.svelte
packages/svelte-undp-components/src/lib/components/index.ts
sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
sites/geohub/src/components/util/AccessLevelSwitcher.svelte
sites/geohub/src/components/util/stac/StacApiExplorer.svelte
sites/geohub/src/components/util/stac/StacCollectionMap.svelte
sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.svelte
sites/geohub/src/routes/(app)/settings/+page.svelte

fixes #3057
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1318556484) by [Unito](https://www.unito.io)

refactor: moved SegmentButtons component to svelte-undp-component package

---

.changeset/grumpy-eels-wash.md
.changeset/tender-oranges-study.md
packages/svelte-undp-components/src/lib/components/ShowDetails.stories.ts
packages/svelte-undp-components/src/lib/components/ShowDetails.svelte
packages/svelte-undp-components/src/lib/components/index.ts
packages/svelte-undp-components/src/lib/util/handleEnterKey.ts
packages/svelte-undp-components/src/lib/util/index.ts
sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
sites/geohub/src/components/pages/map/plugins/StyleShare.svelte
sites/geohub/src/components/util/stac/StacApiExplorer.svelte

fixes #3059
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1318575200) by [Unito](https://www.unito.io)

refactor: moved ShowDetails component to svelte-undp-component

---

.changeset/twenty-knives-cross.md
.changeset/violet-bikes-tease.md
packages/svelte-undp-components/src/lib/components/Accordion.stories.ts
packages/svelte-undp-components/src/lib/components/Accordion.svelte
packages/svelte-undp-components/src/lib/components/index.ts
packages/svelte-undp-components/src/lib/util/clean.test.ts
packages/svelte-undp-components/src/lib/util/clean.ts
packages/svelte-undp-components/src/lib/util/index.ts
sites/geohub/src/components/maplibre/circle/VectorCircle.svelte
sites/geohub/src/components/maplibre/fill-extrusion/VectorFillExtrusion.svelte
sites/geohub/src/components/maplibre/fill/VectorPolygon.svelte
sites/geohub/src/components/maplibre/heatmap/VectorHeatmap.svelte
sites/geohub/src/components/maplibre/hillshade/Hillshade.svelte
sites/geohub/src/components/maplibre/line/VectorLine.svelte
sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
sites/geohub/src/components/maplibre/raster/RasterLegendEdit.svelte
sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
sites/geohub/src/components/maplibre/vector/VectorSimulationAccordion.svelte
sites/geohub/src/components/pages/map/data/DataCard.svelte
sites/geohub/src/components/pages/map/data/DataVectorCard.svelte
sites/geohub/src/components/pages/map/layers/LayerInfo.svelte
sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorLabelPanel.svelte
sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
sites/geohub/src/components/util/stac/StacCatalogItem.svelte
sites/geohub/src/components/util/stac/StacCatalogMap.svelte

fixes #3063
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1318646583) by [Unito](https://www.unito.io)

refactor: moved Accordion component to svelte-undp-component

---

.changeset/cool-tomatoes-suffer.md
.changeset/spotty-kings-decide.md
packages/svelte-undp-components/src/lib/components/HeroLink.stories.ts
packages/svelte-undp-components/src/lib/components/HeroLink.svelte
packages/svelte-undp-components/src/lib/components/index.ts
sites/geohub/src/routes/(app)/+page.svelte
sites/geohub/src/routes/(app)/data/+page.svelte

fixes #3067
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1318740258) by [Unito](https://www.unito.io)

refactor: moved HeroLink component to svelte-undp-component

---

.changeset/four-bottles-burn.md
.changeset/shaggy-falcons-drop.md
packages/svelte-undp-components/src/lib/components/FloatingPanel.stories.ts
packages/svelte-undp-components/src/lib/components/FloatingPanel.svelte
packages/svelte-undp-components/src/lib/components/index.ts
sites/geohub/src/components/pages/map/layers/LayerEdit.svelte
sites/geohub/src/components/pages/map/plugins/MaplibreLegendControl.svelte

fixes #3069
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1318764249) by [Unito](https://www.unito.io)

refactor: migrated FloatingPanel to svelte-undp-component

---

.changeset/blue-lobsters-cry.md
.changeset/lazy-vans-type.md
packages/svelte-undp-components/src/lib/components/PanelButton.stories.ts
packages/svelte-undp-components/src/lib/components/PanelButton.svelte
packages/svelte-undp-components/src/lib/components/PanelButton.test.ts
packages/svelte-undp-components/src/lib/components/index.ts
sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
sites/geohub/src/components/pages/map/data/TextFilter.svelte

fixes #3071
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1318791233) by [Unito](https://www.unito.io)

refactor: migrated PanelButton to svelte-undp-component

---

.changeset/shiny-toes-tap.md
.changeset/yellow-trainers-sparkle.md
packages/svelte-undp-components/src/lib/components/HeroHeader.stories.ts
packages/svelte-undp-components/src/lib/components/HeroHeader.svelte
packages/svelte-undp-components/src/lib/components/index.ts
sites/geohub/src/routes/(app)/api/+page.svelte
sites/geohub/src/routes/(app)/dashboards/+page.svelte
sites/geohub/src/routes/(app)/data/+page.svelte
sites/geohub/src/routes/(app)/data/[id]/+page.svelte
sites/geohub/src/routes/(app)/data/[id]/style/edit/+page.svelte
sites/geohub/src/routes/(app)/data/supported-formats/+page.svelte
sites/geohub/src/routes/(app)/data/upload/+page.svelte
sites/geohub/src/routes/(app)/management/+page.svelte
sites/geohub/src/routes/(app)/management/pgtileserv/+page.svelte
sites/geohub/src/routes/(app)/management/stac/+page.svelte
sites/geohub/src/routes/(app)/management/stac/api/[id]/+page.svelte
sites/geohub/src/routes/(app)/management/stac/api/[id]/[collection]/+page.svelte
sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte
sites/geohub/src/routes/(app)/maps/+page.svelte
sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
sites/geohub/src/routes/(app)/settings/+page.svelte
sites/geohub/src/routes/(app)/tools/+page.svelte

* created `HeroHeader` component in svelte-undp-components
* replaced all pages' header to use new component (except `/data/{id}/edit` page)
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1319450002) by [Unito](https://www.unito.io)

feat: created HeroHeader component

---

.changeset/sixty-cheetahs-rule.md
sites/geohub/src/components/pages/data/datasets/UserPermission.svelte
sites/geohub/src/lib/server/helpers/index.ts
sites/geohub/src/lib/server/helpers/searchUsersByEmail.ts
sites/geohub/src/routes/api/users/+server.ts
sites/geohub/static/api/swagger/spec.yaml

fixes #3087
* added `/users` endpoint to search users by email address
* show user list alongside with inputted user email text.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1320428219) by [Unito](https://www.unito.io)

fix: show signed user list by typed string for user permission feature

---

.changeset/fluffy-gorillas-divide.md
.changeset/olive-camels-beam.md
packages/svelte-undp-design/src/lib/SearchExpand/SearchExpand.stories.ts
packages/svelte-undp-design/src/lib/SearchExpand/SearchExpand.svelte
sites/geohub/src/lib/server/helpers/createDatasetSearchWhereExpression.ts
sites/geohub/src/routes/(app)/data/+page.server.ts

fixes #3098
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1321204869) by [Unito](https://www.unito.io)

fix: remove & and | char

---

.changeset/quick-pandas-wave.md
sites/geohub/src/components/pages/data/datasets/PublishedDatasetRow.svelte
sites/geohub/src/components/pages/home/MapStyleCardList.svelte
sites/geohub/src/lib/config/DefaultUserConfig/MapPageTableViewType.ts
sites/geohub/src/lib/config/DefaultUserConfig/index.ts
sites/geohub/src/routes/(app)/maps/+page.server.ts
sites/geohub/src/routes/(app)/maps/+page.ts
sites/geohub/src/routes/(app)/settings/+page.svelte

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1321446047) by [Unito](https://www.unito.io)

feat: added map list view

---

.github/workflows/ci.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1321585625) by [Unito](https://www.unito.io)

fix: changed cogserver-dev-deployment.yaml folder path

---

.changeset/hip-bananas-love.md
sites/geohub/src/components/maplibre/raster/RasterAlgorithmParameter.svelte
sites/geohub/src/lib/types/RasterAlgorithm.ts
sites/geohub/src/routes/(app)/tools/+page.svelte

adopt for new version of titiler algorithms parameter
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1322556165) by [Unito](https://www.unito.io)

fix: show title and description at Tools page, and show slider if minimum and maximum value are available in algorithm

---

.changeset/four-foxes-melt.md
sites/geohub/static/robots.txt

I found there are so many sveltekit error about missing robots.txt, hence I added it to static folder
currently, only exclude path of `/api/` endpoints
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1322645678) by [Unito](https://www.unito.io)

fix: added robots.txt

---

.changeset/strange-crabs-dream.md
sites/geohub/src/components/util/MiniMap.svelte
sites/geohub/src/lib/helper/createAttributionFromTags.ts
sites/geohub/src/lib/server/defaultStyle/VectorDefaultStyle.ts
sites/geohub/src/lib/server/helpers/getStyleById.ts
sites/geohub/src/routes/api/datasets/[id]/style/[layer]/[type]/+server.ts

fixes #3127
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1324996778) by [Unito](https://www.unito.io)

fix: fixed bug of not showing attribution correctly for vector datasets, also now forcely update attribution for saved map in /style/{id} endpoint.

---

.changeset/beige-zebras-scream.md
sites/geohub/src/routes/(app)/management/stac/api/[id]/[collection]/+page.svelte
sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1325717867) by [Unito](https://www.unito.io)

fix: the link to map page from STAC management page was fixed

---

.github/workflows/ci.yml
docker/Dockerfile.production

deploy docker image to ACR (only for tagged version branch, develop, and develop*)
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1326041421) by [Unito](https://www.unito.io)

ci: deploy docker image

---

.github/workflows/ci.yml

only build and deploy to ACR for original geohub repo
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1326063779) by [Unito](https://www.unito.io)

fix: check whether it is original repo for CI jobs which deploy to ACR

---

.github/workflows/ci.yml

added `develop-ibm` to CI to trigger jobs
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1326079569) by [Unito](https://www.unito.io)

fix: add develop-ibm

---

.github/workflows/ci.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1326160892) by [Unito](https://www.unito.io)

fix: push docker iamge for main branch

---

.github/workflows/ci.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1326965757) by [Unito](https://www.unito.io)

fix: release docker image with geohub tag version like geohub@X.X.X

---

.changeset/healthy-cherries-enjoy.md
packages/svelte-undp-components/src/lib/components/ColorMapPicker.svelte
packages/svelte-undp-components/src/lib/components/Tabs.svelte

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1326976784) by [Unito](https://www.unito.io)

fix: set href as null instead of empty string if tab id is not starting with hash

---

.github/workflows/ci.yml

previous one did not trigger CI after changeset pushed tag
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1326999627) by [Unito](https://www.unito.io)

fix: fixed version expression for trigger

---

.changeset/big-fans-carry.md
pnpm-lock.yaml
sites/geohub/.gitignore
sites/geohub/package.json
sites/geohub/src/components/header/UserAccount.svelte
sites/geohub/src/lib/config/AppConfig/FooterItems.ts
sites/geohub/src/routes/(app)/license/+page.server.ts
sites/geohub/src/routes/(app)/license/+page.svelte
sites/geohub/src/routes/(app)/license/+page.ts
sites/geohub/svelte.config.js

* show version and link to license page in dropdown
* add /license page
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1327098948) by [Unito](https://www.unito.io)

feat: show GeoHub version and package licenses used

---

documentation/Pipfile
documentation/Pipfile.lock
documentation/docs/slides/tutorial.md
documentation/mkdocs.yml
documentation/theme_overrides/reveal.html

added mermaid plugin to mkdocs and revealjs
usage is slightly different
* usage in mkdocs
```mermaid
graph TD;
A-->B;
A-->C;
B-->D;
C-->D;
```
* usage in revealjs.
```html
<div class="mermaid">
graph TD;
A-->B;
A-->C;
B-->D;
C-->D;
</div>
```
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1327559222) by [Unito](https://www.unito.io)

doc: add mermaid plugin to mkdocs

---

.github/workflows/ci.yml

fixes #3173
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1328295469) by [Unito](https://www.unito.io)

ci: check whether ACR_USERNAME and ACR_PASSWORD exists in CI

---

documentation/mkdocs.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1328429438) by [Unito](https://www.unito.io)

fix: comment site_url because links do not work in docs-dev

---

documentation/mkdocs.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1328460025) by [Unito](https://www.unito.io)

fix: fixed reveal.js path to absolute path

---

.changeset/tough-tips-burn.md
sites/geohub/src/lib/server/config/FooterItems.ts
sites/geohub/src/lib/server/config/HeaderItems.ts
sites/geohub/src/routes/+layout.server.ts

fixed and simplified logic of creating header and footer links
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1329629533) by [Unito](https://www.unito.io)

fix: fixed bug not showing management link in footer correctly

---

.changeset/fast-windows-try.md
pnpm-lock.yaml
sites/geohub/package.json

downgrade a patch version for auth.js
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1330476920) by [Unito](https://www.unito.io)

fix: downgraded a patch version for auth.js to solve this error of ERR_INVALID_URL

---

documentation/docs/data/data_upload.md
documentation/docs/data/index.md
documentation/docs/data/publish_datasets.md
documentation/docs/data/search_datasets.md
documentation/docs/visualization/search_datasets.md
documentation/mkdocs.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1330519534) by [Unito](https://www.unito.io)

doc: changed some structure and added some links of UNDP

---

README.md

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1331473175) by [Unito](https://www.unito.io)

doc: added geo-undpstac-pipeline link on readme

---

.changeset/forty-bats-sit.md
sites/geohub/src/components/pages/data/datasets/PublishedDataset.svelte

fixes #3209
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1332039542) by [Unito](https://www.unito.io)

feat: show year and resolution, admin level tag in info tab if they are applicable

---

.changeset/old-pets-sing.md
sites/geohub/src/components/util/TagInput.svelte
sites/geohub/src/lib/config/AppConfig/TagInputValues.ts
sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.svelte

fixes #3212
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1332094492) by [Unito](https://www.unito.io)

fix:  make important tags visible

---

.changeset/fast-rats-itch.md
pnpm-lock.yaml
sites/geohub/package.json

updated authjs since the bug seemed being fixed already
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1334117987) by [Unito](https://www.unito.io)

chore: update authjs

---

.changeset/five-geckos-look.md
packages/svelte-undp-components/src/lib/components/Breadcrumbs.stories.ts
packages/svelte-undp-components/src/lib/components/Breadcrumbs.svelte
sites/geohub/src/components/util/stac/StacCatalogExplorer.svelte
sites/geohub/src/components/util/stac/StacCollectionMap.svelte
sites/geohub/src/lib/types/StacCatalogBreadcrumb.ts

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1334908287) by [Unito](https://www.unito.io)

fix: add click event for breadcrumbs component if url property is not provided.

---

.changeset/itchy-cameras-exist.md
sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1334935036) by [Unito](https://www.unito.io)

 fix: fixed bug of stac calatalog's breadcrumbs in management page

---

.changeset/new-comics-cry.md
sites/geohub/src/components/maplibre/raster/RasterLegendEdit.svelte

fixes #3249
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1336547360) by [Unito](https://www.unito.io)

fix: enabled rescale property if an algorithm layer has rescale url query param

---

.changeset/fast-mayflies-help.md
.changeset/metal-candles-prove.md
.changeset/olive-queens-drop.md
packages/svelte-undp-components/package.json
packages/svelte-undp-components/src/lib/components/DatePicker.stories.ts
packages/svelte-undp-components/src/lib/components/DatePicker.svelte
packages/svelte-undp-components/src/lib/components/index.ts
pnpm-lock.yaml
sites/geohub/package.json
sites/geohub/src/components/util/stac/StacApiExplorer.svelte
sites/geohub/src/components/util/stac/StacCatalogDatePicker.svelte

fixes #3251
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1336644851) by [Unito](https://www.unito.io)

fix: fixed data picker behaviour

---

backends/k8s/cogserver/yaml/cogserver-deployment.yaml
backends/k8s/cogserver/yaml/cogserver-dev-deployment.yaml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1338089739) by [Unito](https://www.unito.io)

fix: add LOG_LEVEL in k8s

---

documentation/requirements.txt

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1338178873) by [Unito](https://www.unito.io)

fix: added mermaid dependency

---

documentation/docker-compose.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1338183654) by [Unito](https://www.unito.io)

fix: docker-compose path

---

documentation/docs/visualization/handson.md
documentation/docs/visualization/index.md
documentation/docs/visualization/map_view.md
documentation/docs/visualization/save_map.md
documentation/docs/visualization/search_maps.md
documentation/docs/visualization/share_map.md
documentation/docs/visualization/visualize_overview.md
documentation/docs/visualization/visualize_raster.md
documentation/docs/visualization/visualize_vector.md
documentation/mkdocs.yml

just wrote an outline for heading title before starting writing sections.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1338260019) by [Unito](https://www.unito.io)

doc: added outline for visualization section

---

documentation/.mailmap
documentation/mkdocs.yml
documentation/requirements.txt

added author plugin for mkdocs
https://github.com/timvink/mkdocs-git-authors-plugin?tab=readme-ov-file
authors will be automatically added according to git history.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1339570795) by [Unito](https://www.unito.io)

doc: added author plugin

---

.changeset/modern-tools-behave.md
sites/geohub/src/components/pages/map/layers/vector/Tags.svelte
sites/geohub/src/components/pages/map/layers/vector/ValueInput.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorFilter.svelte

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1339728533) by [Unito](https://www.unito.io)

fix: fixed layout collapse for vector filter

---

.changeset/slow-swans-film.md
sites/geohub/src/lib/server/auth.ts

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1339741380) by [Unito](https://www.unito.io)

to run auth.js correctly, set a constant string if it is not provided

---

.changeset/blue-teachers-drop.md
sites/geohub/src/components/pages/map/layers/vector/PropertySelectButtons.svelte
sites/geohub/src/components/pages/map/layers/vector/ValueInput.svelte

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1340316004) by [Unito](https://www.unito.io)

fix: removed scroll from vector filter component since the parent component has it. Use unified button design for some buttons of filter.

---

documentation/docs/visualization/visualize_raster.md

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1340513757) by [Unito](https://www.unito.io)

doc: complete raster visualization (except raster transform)

---

.changeset/lemon-trains-cough.md
sites/geohub/src/components/pages/map/layers/raster/RasterTransform.svelte
sites/geohub/src/components/pages/map/layers/raster/RasterTransformAdvanced.svelte
sites/geohub/src/components/pages/map/layers/raster/RasterTransformNumbersInput.svelte
sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte

raster transform advanced is not working at all. not sure whether it needs to be remained.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1340567914) by [Unito](https://www.unito.io)

fix: use unified design for raster transform. fixed a bug of simple transform when it is applied

---

.changeset/silver-zoos-shave.md
sites/geohub/src/components/maplibre/heatmap/HeatmapColorRow.svelte

fixes #3287
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1341205967) by [Unito](https://www.unito.io)

fix: show ColorPicker dialog correctly for heatmap color property

---

documentation/docs/data/best_practices.md

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1341393259) by [Unito](https://www.unito.io)

fix: text grammer for best practice

---

.changeset/lazy-actors-live.md
.changeset/rude-bottles-worry.md
.changeset/short-rabbits-grow.md
sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte

fixes #3310
In the last step, current code does not allow to have more than one filter, I feel not necessary to have dropdown list to be shown.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1341452826) by [Unito](https://www.unito.io)

fix: transform advanced hidden, and improved UI

---

.changeset/short-goats-judge.md
pnpm-lock.yaml
sites/geohub/package.json
sites/geohub/src/lib/server/helpers/getStyleById.ts

fixes #3327
update base style from the latest to prevent some errors occur due to the style changes (like glyph, sprite)
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1342907435) by [Unito](https://www.unito.io)

fix: update saved style sources and layers from the latest base style

---

.changeset/twelve-files-add.md
sites/geohub/src/routes/(app)/maps/[id]/+page.svelte

fixes #3334
forgot to call `await styleSwitcher.initialise();`
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1342989452) by [Unito](https://www.unito.io)

fix: init style switcher at map portal page

---

.changeset/flat-zoos-bathe.md
packages/svelte-undp-components/src/lib/components/PropertyEditor.stories.ts
packages/svelte-undp-components/src/lib/components/PropertyEditor.svelte
packages/svelte-undp-components/src/lib/components/Slider.stories.ts
packages/svelte-undp-components/src/lib/components/Slider.svelte
packages/svelte-undp-components/src/lib/components/index.ts
packages/svelte-undp-components/src/lib/util/index.ts
packages/svelte-undp-components/src/lib/util/isInt.test.ts
packages/svelte-undp-components/src/lib/util/isInt.ts
sites/geohub/src/components/maplibre/vector/VectorSimpleColorLegend.svelte
sites/geohub/src/lib/helper/getIntervalList.ts
sites/geohub/src/lib/helper/getTextFieldDataType.ts
sites/geohub/src/lib/helper/index.ts
sites/geohub/src/lib/helper/isInt.ts

related to #3343 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1343818330) by [Unito](https://www.unito.io)

feat: add slider component with text editor option

---

.changeset/nasty-moons-design.md
.changeset/olive-pants-hug.md
.changeset/plenty-fishes-sing.md
.changeset/serious-balloons-joke.md
.changeset/thirty-badgers-cheat.md
.changeset/thirty-berries-smell.md
packages/svelte-undp-components/src/lib/components/Slider.stories.ts
packages/svelte-undp-components/src/lib/components/Slider.svelte
pnpm-lock.yaml
sites/geohub/package.json
sites/geohub/src/components/maplibre/MaplibreSlider.svelte
sites/geohub/src/components/maplibre/OpacitySlider.svelte
sites/geohub/src/components/maplibre/fill-extrusion/FillExtrusionBase.svelte
sites/geohub/src/components/maplibre/fill-extrusion/FillExtrusionHeight.svelte
sites/geohub/src/components/maplibre/raster/RasterLegendEdit.svelte
sites/geohub/src/components/maplibre/raster/RasterRescale.svelte
sites/geohub/src/components/pages/map/layers/raster/RasterTransformAdvanced.svelte
sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte
sites/geohub/src/components/pages/map/layers/vector/ValueInput.svelte
sites/geohub/src/components/util/stac/StacApiExplorer.svelte
sites/geohub/src/routes/(app)/settings/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/OverlayControl.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte

fixes #3343
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1343907244) by [Unito](https://www.unito.io)

refactor: Use Slider component from svelte-undp-component

---

.changeset/itchy-toys-cry.md
sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte

closes #3347
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1344620469) by [Unito](https://www.unito.io)

refactor: make logic simplified for RasterTransformSimple

---

.changeset/nervous-brooms-knock.md
pnpm-lock.yaml
sites/geohub/.gitignore
sites/geohub/package.json
sites/geohub/src/hooks.server.ts
sites/geohub/src/lib/config/AppConfig/MapStyles.ts
sites/geohub/src/lib/server/helpers/getStyleById.ts
sites/geohub/src/lib/server/helpers/index.ts
sites/geohub/src/lib/server/helpers/resolveSpriteUrl.ts
sites/geohub/src/routes/api/mapstyle/[id].json/+server.ts
sites/geohub/static/api/swagger/spec.yaml

closes #3289
This PR will increase  a minor version of geohub
* feat: serve base map style from new `/api/mapstyle/{id}.json` endpoint
* feat: host sprite files from `/static/api/mapstyle` folder
* fix: resolve relative sprite URL to absolute URL at `/api/mapstyle/{id}/json` endpoint
* fix: convert relative sprite URL to jsdelivr CDN url if server is localhost (because it cannot work with static image API)
I am thinking to load `MapStyles[0].uri` at +layout.server.ts, so these code can be simplified a lot.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1344802847) by [Unito](https://www.unito.io)

feat: add /api/mapstyle endpoint to serve base maplibre styles. The endpoint solves sprite relative url to absolute url.

---

.github/workflows/ci.yml
documentation/.env.example
documentation/Dockerfile
documentation/docker-compose.yml
documentation/mkdocs.yml

* added `EDIT_URL` variable in .env
* switch branch name dynamically in CI
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1353875187) by [Unito](https://www.unito.io)

doc: change github branch name dynamically

---

.github/workflows/release.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1354725890) by [Unito](https://www.unito.io)

ci: fixed node version and pnpm version for release CI

---

documentation/theme_overrides/reveal.html

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1354730738) by [Unito](https://www.unito.io)

fix: fixed setting go back button URL

---

documentation/docs/data/best_practices.md
documentation/docs/data/data_store.md
documentation/docs/data/data_upload.md
documentation/docs/data/index.md
documentation/docs/data/publish_datasets.md
documentation/docs/data/search_datasets.md
documentation/docs/data/search_datasets_on_map.md
documentation/docs/data/search_datasets_table.md
documentation/docs/getting-started/signin.md
documentation/theme_overrides/reveal.html

adjusted slide layout for data section
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1354757578) by [Unito](https://www.unito.io)

doc: adjusted slide layout for data section

---

documentation/theme_overrides/reveal.html

* added copyright
* added slide number
* adjusted style of home and back buttons
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1354980619) by [Unito](https://www.unito.io)

doc: added copyright and slide number

---

documentation/theme_overrides/home.html

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1355604360) by [Unito](https://www.unito.io)

fix: fixed max-width which make logo hidden in home page

---

documentation/docs/getting-started/signin.md
documentation/docs/stylesheets/extra.css

realized buttons are not very visible in home page because of gradation color is blue
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1355612539) by [Unito](https://www.unito.io)

fix: changed home page's color gradation to UNDP primary color

---

documentation/requirements.txt

upgrade mkdocs to v1.6.0 with mkdocs-material updates
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1355724450) by [Unito](https://www.unito.io)

chore: upgrade mkdocs to v1.6

---

.changeset/quiet-numbers-behave.md
sites/geohub/src/components/maplibre/raster/RasterSimpleLegend.svelte
sites/geohub/src/components/maplibre/vector/VectorSimpleColorLegend.svelte

fixes #3412
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1357183702) by [Unito](https://www.unito.io)

fix: removed padding and domain props which made color legend look differently actual.

---

documentation/docs/getting-started/importance_of_gis.md
documentation/docs/getting-started/overview.md
documentation/mkdocs.yml
documentation/theme_overrides/reveal.html

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1357281235) by [Unito](https://www.unito.io)

add overview and importance

---

documentation/mkdocs.yml

want to try navigation.instant
https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1360361407) by [Unito](https://www.unito.io)

doc: enabled navigation.instant

---

documentation/mkdocs.yml

Reverts UNDP-Data/geohub#3437
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1360365703) by [Unito](https://www.unito.io)

Revert "doc: enabled navigation.instant"

---

.changeset/cuddly-bulldogs-leave.md
sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/AnalyzeBivariate.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/utils/adminLayer.ts

Add analysis of bivariate data by choropleth map feature
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1360359717) by [Unito](https://www.unito.io)

feat: Bivariate choropleth map

---

documentation/theme_overrides/reveal.html

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1361064455) by [Unito](https://www.unito.io)

fix: using python to set url of go back button

---

package.json

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1361143197) by [Unito](https://www.unito.io)

chore: update pnpm to 9.1.0

---

backends/k8s/stac-pipeline/yaml/deployment.yaml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1363343421) by [Unito](https://www.unito.io)

fix: add --force option for stac pipeline deployment

---

backends/k8s/stac-pipeline/yaml/deployment.yaml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1363368236) by [Unito](https://www.unito.io)

fix: changed node pool for stac pipeline from manual to pipeline

---

backends/k8s/data-pipeline/yaml/ingest-environment.yaml
backends/k8s/pgtileserv/yaml/pgtileserv-deployment.yaml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1363379778) by [Unito](https://www.unito.io)

add node selector for ingest and pgtileserv

---

package.json

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1364759112) by [Unito](https://www.unito.io)

chore: upgrade pnpm to 9.1.1

---

backends/k8s/stac-pipeline/yaml/deployment.yaml

changed max replica count from 2 to 1 for stac pipeline
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1365806305) by [Unito](https://www.unito.io)

fix: changed maxReplicaCount to 1

---

.changeset/cuddly-bulldogs-leave.md
.changeset/silly-dancers-beg.md
sites/geohub/src/routes/(map)/dashboards/electricity/components/AnalyzeBivariate.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/utils/adminLayer.ts

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1366546232) by [Unito](https://www.unito.io)

feat: adjust AnalyzeBivariate to match other UI elements

---

.changeset/seven-cows-lay.md
sites/geohub/static/api/swagger/spec.yaml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1366703951) by [Unito](https://www.unito.io)

doc: added more information for  POST endpoint usage.

---

sites/geohub/static/api/swagger/spec.yaml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1366748785) by [Unito](https://www.unito.io)

fix: fixed markdown for table

---

.changeset/witty-rocks-sit.md
pnpm-lock.yaml
sites/geohub/package.json
sites/geohub/src/lib/config/AppConfig/MapStyles.ts
sites/geohub/src/routes/api/mapstyle/[id].json/+server.ts
sites/geohub/static/api/swagger/spec.yaml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1368398295) by [Unito](https://www.unito.io)

feat: add dark style into mapstyle endpoint

---

.changeset/young-berries-grin.md
pnpm-lock.yaml
sites/geohub/package.json
sites/geohub/src/components/pages/home/ExploreDatasets.svelte
sites/geohub/src/components/util/CountryCard.svelte
sites/geohub/src/lib/server/helpers/getStyleById.ts
sites/geohub/src/routes/(app)/+layout@.svelte
sites/geohub/src/routes/(map)/maps/+layout.svelte
sites/geohub/src/routes/api/mapstyle/[id].json/+server.ts
sites/geohub/static/api/swagger/spec.yaml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1369069741) by [Unito](https://www.unito.io)

feat: add Positron base style to /mapstyle endpoint

---

.changeset/ninety-singers-share.md
sites/geohub/src/lib/config/AppConfig/MapStyles.ts

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1369109066) by [Unito](https://www.unito.io)

fix: typo of positron style name

---

package.json

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1369919393) by [Unito](https://www.unito.io)

chore: updated pnpm to 9.1.2

---

.changeset/early-trains-exist.md
packages/style-switcher/package.json
packages/style-switcher/src/lib/index.ts
pnpm-lock.yaml

fixes #3528
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1369897222) by [Unito](https://www.unito.io)

fix: show tooltip for style switcher buttons

---

sites/static-image-api/package-lock.json
sites/static-image-api/package.json
sites/static-image-api/src/lib/server/renderMap.ts
sites/static-image-api/src/lib/server/sources/http.ts
sites/static-image-api/src/lib/server/sources/index.ts
sites/static-image-api/src/lib/server/sources/pmtiles.ts

* fix: remove optimise code not to remove any layers from style
* refactor: make the logic of getting source simpler
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1372500549) by [Unito](https://www.unito.io)

fix: remove optimise code not to remove any layers from style

---

backends/k8s/cogserver/yaml/cogserver-deployment.yaml
backends/k8s/cogserver/yaml/cogserver-dev-deployment.yaml

Changed from Deployment to StatefulSet and added config for gunicorn server
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1372694808) by [Unito](https://www.unito.io)

changed to statefulset + gunicorn config

---

.changeset/wicked-carpets-think.md
sites/geohub/src/components/maplibre/symbol/TextField.svelte
sites/geohub/src/components/maplibre/symbol/TextHaloWidth.svelte
sites/geohub/src/lib/helper/getTextFieldDataType.ts

closes #3547 
fix label bug
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1373053266) by [Unito](https://www.unito.io)

cast halo-width to number and fix getTextFieldDataType

---

.github/workflows/release.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1373293834) by [Unito](https://www.unito.io)

ci: fixed release ci error

---

.github/workflows/release.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1373298309) by [Unito](https://www.unito.io)

ci: fix the bug of gettign PR number for ci

---

.github/workflows/release.yml

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1373302114) by [Unito](https://www.unito.io)

ci: use context.issue.number for pull_number

---

.changeset/mighty-toes-burn.md
sites/geohub/src/hooks.server.ts
sites/static-image-api/src/hooks.server.ts

* added handle to add allowed origin for CORS
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1377479469) by [Unito](https://www.unito.io)

fix: fixed CORS to allow all websites to access to geohub api

---

.changeset/fluffy-teachers-protect.md
sites/geohub/src/routes/api/style/+server.ts

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1377761689) by [Unito](https://www.unito.io)

fix: add error handling for /api/style endpoint

---

.github/workflows/ci.yml

ci: removed production deployment CI since now we use AppService (docker based)
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1378679724) by [Unito](https://www.unito.io)

fix: removed production deployment CI

---

.changeset/polite-hotels-argue.md
sites/geohub/src/components/pages/home/ExploreDatasets.svelte

fix: fixed layout collapse of dataset section in landing page

---

.changeset/light-melons-whisper.md
sites/geohub/src/components/util/stac/StacApiExplorer.svelte

fix: #3616

---

.changeset/smart-sheep-trade.md
sites/geohub/src/components/util/stac/StacApiExplorer.svelte

fix: make multiple items selection work when switching from products tab

---

.changeset/swift-wolves-sort.md
backends/database/geohub-database.sql
sites/geohub/src/components/util/stac/StacApiExplorer.svelte
sites/geohub/src/lib/types/AvailableStacProduct.ts
sites/geohub/src/routes/api/stac/[id]/[collection]/[product_id]/+server.ts
sites/geohub/src/routes/api/stac/[id]/[collection]/products/+server.ts
sites/geohub/static/api/swagger/spec.yaml

fix: change text of product select to description

---

.changeset/smooth-eyes-remain.md
sites/geohub/src/lib/server/Product.ts
sites/geohub/src/routes/api/products/+server.ts
sites/geohub/src/routes/api/products/[id]/+server.ts
sites/geohub/static/api/swagger/spec.yaml

refactor: use id as path parameter in product

---

.changeset/tasty-dodos-sell.md
sites/geohub/src/routes/api/products/[id]/+server.ts
sites/geohub/static/api/swagger/spec.yaml

fix: product id endpoint

---

sites/geohub/src/routes/api/products/+server.ts
sites/geohub/src/routes/api/products/[id]/+server.ts

fix: product_id endpoint

---

documentation/mkdocs.yml
documentation/requirements.txt

added this mkdocs plugin to show updated date
https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/

doc: added git-revision-date-localized plugin to mkdocs

---

.changeset/sharp-tools-wink.md
sites/geohub/src/components/util/stac/StacApiExplorer.svelte
sites/geohub/src/lib/server/Product.ts
sites/geohub/src/lib/types/Product.ts
sites/geohub/src/lib/types/index.ts
sites/geohub/src/routes/api/products/+server.ts
sites/geohub/src/routes/api/products/[id]/+server.ts

- /products/[id] endpoint returns 404 if id does not exist
- POST/PUT endpoint now returns Product object
- refactored /products endpoint. Moved SQLs into ProductManager class (renamed former Product class)
- introduced Product interface

fix: returns 404 error from /products/[id] endpoint. Refactored products endpoint code.

---

.changeset/twenty-dancers-pretend.md
sites/geohub/src/components/util/stac/StacApiExplorer.svelte
sites/geohub/src/lib/types/AvailableStacProduct.ts
sites/geohub/src/lib/types/index.ts

refactor: remvoed duplicated AvailableStacProduct interface to use StacProduct interface.

---

.changeset/cool-tigers-notice.md
sites/geohub/src/routes/(app)/tools/+page.svelte

fix: changed card accent color to yellow for hovered color.

---

.github/workflows/ci.yml

Revert "fix: redeploy produciton docker image"

---

.changeset/gorgeous-spies-happen.md
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
packages/svelte-maplibre-storymap/src/lib/StoryMapChapter.svelte
packages/svelte-maplibre-storymap/src/lib/interfaces/StoryMapChapter.ts
packages/svelte-maplibre-storymap/src/routes/+page.server.ts

added new options from https://github.com/digidem/maplibre-storymap
- onChapterEnter
- onChapterExit

feat: added onChapterEnter and onChapterExit to chapter properties.

---

.changeset/ninety-eggs-jog.md
packages/undp-bulma/bulma.scss

feat: add material-icons-outlined to undp-bulma

---

.changeset/giant-crews-appear.md
sites/geohub/src/components/util/stac/StacCollectionMap.svelte

fix: create 'self' link if it does not exist in catalog.json

---

sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/ElectricityControl.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/ExploreEvolution.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSliderControl.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/constansts.ts
sites/geohub/src/routes/(map)/dashboards/electricity/interfaces/Dataset.ts
sites/geohub/src/routes/(map)/dashboards/electricity/interfaces/index.ts

- enabled cgaz admin tool
- to solve the conflict of control position between admin tool and time slider, switch time slider to use maplibre plugin control class.
- removed most unnecessary code for new dashboard.

fix: enabled cgaz admin tool and fixed bug of time slider position

---

.changeset/green-shoes-refuse.md
sites/geohub/src/lib/server/helpers/generateAzureBlobSasToken.ts
sites/geohub/src/lib/server/helpers/getVectorMetadata.ts
sites/geohub/src/lib/server/helpers/index.ts
sites/geohub/src/lib/server/helpers/isGeoHubBlobStorage.ts
sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.server.ts

current GeoHub only allows GeoHub blob storage data to be registered. This PR is going to allow external HTTP sources to register.

fix: allow external HTTP sources to be registered to GeoHub

---

.changeset/silly-ladybugs-hang.md
sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
sites/geohub/src/components/util/LayerTypeSwitch.svelte

fix: fixed a bug of default layer style editor for vector data to avoid adding layers many times.

---

.changeset/honest-waves-attack.md
sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.server.ts

fix: fixed bug of editing external dataset properties.

---

.changeset/curvy-dingos-wait.md
sites/geohub/src/routes/(app)/maps/[id]/+page.server.ts
sites/geohub/src/routes/(app)/maps/[id]/+page.ts

fix: Use social iamge for saved map instead of using same style image

---

.changeset/clever-pigs-hang.md
sites/geohub/src/lib/server/helpers/createDatasetLinks.ts
sites/geohub/src/routes/(app)/data/[id]/+page.server.ts
sites/geohub/src/routes/(app)/data/[id]/+page.svelte
sites/geohub/src/routes/(app)/data/[id]/+page.ts
sites/geohub/src/routes/+layout.svelte

fix: show social image for dataset preview

---

.changeset/giant-islands-boil.md
.changeset/ten-hotels-itch.md
packages/cgaz-admin-tool/src/lib/index.ts
sites/geohub/src/components/pages/data/datasets/DatasetPreview.svelte
sites/geohub/src/lib/helper/isStyleChanged.ts
sites/geohub/src/lib/helper/localstorage.ts
sites/geohub/src/routes/(app)/data/[id]/+page.svelte
sites/geohub/src/routes/(app)/management/stac/api/[id]/[collection]/+page.svelte
sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte
sites/geohub/src/routes/(app)/tools/+page.svelte
sites/geohub/src/routes/(map)/maps/+layout.svelte

fix: fixed bugs of  when user is leaving map edit page. Also, clear local storage when users add new data from /data page.

---

.changeset/five-foxes-jump.md
sites/geohub/static/api/swagger/spec.yaml

added proposed storymaps endpoints in swagger because it is not yet implemented, put deprecated flag for these endpoints.

doc: added proposed storymaps endpoints in swagger. 

---

sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSliderControl.svelte

Fixed time slider on the Explore Evolution section not changing data of map

fix: time slider on explore evolution not changing data of map

---

.changeset/slimy-baboons-hang.md
sites/geohub/src/routes/(map)/dashboards/electricity/+page.ts

Changed social image for Electricity dashboard

fix: change Electricity dashboard social image

---

.changeset/famous-pans-suffer.md
sites/geohub/src/routes/(storymap)/storymaps/[id]/+page.server.ts
sites/geohub/src/routes/(storymap)/storymaps/[id]/+page.ts

fixed meta tag for storymap page

fix: Use social image for the main style URL of storymap

---

.changeset/four-buttons-walk.md
sites/geohub/src/lib/server/StorymapManager.ts
sites/geohub/src/routes/api/storymaps/+server.ts
sites/geohub/src/routes/api/storymaps/[id]/+server.ts
sites/geohub/src/routes/api/storymaps/[id]/permission/+server.ts
sites/geohub/src/routes/api/storymaps/[id]/star/+server.ts
sites/geohub/src/routes/api/storymaps/[id]/star/count/+server.ts

fix: add error handling for storymap endpoints

---

.changeset/new-panthers-develop.md
sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
sites/geohub/src/lib/RasterTileData.ts
sites/geohub/src/lib/server/defaultStyle/RasterDefaultStyle.ts
sites/geohub/src/lib/types/RasterTileMetadata.ts

fix: set unscale=true for /statistics, /tiles amd /point endpoint if scales of /info is not 1.

---

.changeset/unlucky-olives-unite.md
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.server.ts

fix: show 403 error if users do not have permission to edit storymap

---

.changeset/tasty-lemons-camp.md
sites/geohub/src/routes/(map)/dashboards/electricity/components/Charts.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte

fix: show all labels in time slider by rotating labels.

---

.changeset/nasty-starfishes-rule.md
sites/geohub/src/routes/(map)/dashboards/electricity/components/ElectricityControl.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/ElectricityLegend.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte

fix: adjust electricity legend

---

.changeset/metal-roses-shout.md
sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte

also improved some UI of download dialog

fix: added download links for electricity access data

---

.changeset/green-deers-burn.md
sites/geohub/src/components/pages/home/DashboardContents.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/IntroductionPanel.svelte

fix: updated dashboard description for landing page.

---

.github/workflows/ci.yml

if branch name starts with `feat/`, push docker image to container registry

chore: push docker iamge for branches name starts with `feat/`

---

.github/workflows/ci.yml

I think need to add feat/** in on push to trigger

add feat/** to on push in CI.yaml

---

.changeset/olive-geckos-switch.md
.changeset/popular-feet-pull.md
.changeset/strong-balloons-visit.md
.changeset/warm-lemons-try.md
packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
packages/svelte-undp-components/src/lib/components/FloatingPanel.stories.ts
packages/svelte-undp-components/src/lib/components/FloatingPanel.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapStyleSelector.svelte
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte

implementing slide editor for storymap.
Let me merge this to apply packages' changes first although it is still being implemented.

feat: implementing slide editor

---

.changeset/smart-brooms-travel.md
.changeset/thick-moose-drive.md
packages/svelte-maplibre-storymap/src/lib/StoryMapChapter.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapStyleSelector.svelte
sites/geohub/src/lib/server/StorymapManager.ts

fix: fixed bug of showing map selector in chapter editor

---

.changeset/stupid-yaks-try.md
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
packages/svelte-maplibre-storymap/src/lib/StoryMapChapter.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterPreview.svelte

fix: fix bug of StorymapChapter

---

.changeset/eleven-ligers-camp.md
sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
sites/geohub/src/routes/(storymap)/storymaps/[id]/viewer/+page.svelte

fix: added UNDP footer to the end of storymap

---

.changeset/violet-rocks-juggle.md
sites/geohub/src/lib/server/config/FooterItems.ts
sites/geohub/src/routes/+layout.server.ts

fix: added DfX link in the footer of GeoHub.

---

.changeset/violet-poets-matter.md
.changeset/wild-mails-trade.md
.changeset/wise-dragons-pay.md
packages/svelte-undp-components/src/lib/components/ModalTemplate.stories.ts
packages/svelte-undp-components/src/lib/components/ModalTemplate.svelte
packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.svelte
sites/geohub/src/components/pages/storymap/GeoHubMapSelector.svelte
sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapStyleSelector.svelte
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte

fix: add geohub map selector

---

.changeset/angry-yaks-vanish.md
sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/+layout@.svelte
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
sites/geohub/src/routes/(storymap)/storymaps/[id]/viewer/+page.svelte

fix: implemented storymap saving at editor.

---

.changeset/odd-yaks-visit.md
.changeset/thirty-turtles-mix.md
packages/svelte-maplibre-storymap/src/lib/helpers.ts
sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterLayerEventEditor.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte

Implemented editor for onChapterEnter and onChapterExit

fix: implementing layer chapter editor

---

.changeset/mean-socks-help.md
sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterPreview.svelte

apply layer event changes before adding style to map

fix: fixed bug of layer event for preview

---

.changeset/cuddly-radios-confess.md
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte

fix: implemented preview button for storymap editor.

---

.changeset/tame-monkeys-poke.md
sites/geohub/src/components/pages/storymap/StorymapChapterPreview.svelte

fix: fixed layout collapse of preview when center alignment is selected

---

sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterPreview.svelte
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte

fix: storymap slide settings

---

.changeset/mighty-birds-clean.md
sites/geohub/src/routes/(map)/dashboards/electricity/+page.server.ts
sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/Charts.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/ExploreEvolution.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/utils/adminLayer.ts

fix: replaced to zonalstats admin data with additional 2021-2023 years

---

sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapHeaderFooterMiniPreview.svelte

fix: adjusted preview image size since border is hidden

---

.changeset/seven-socks-exist.md
packages/svelte-maplibre-storymap/src/lib/css/dark/footer.scss
packages/svelte-maplibre-storymap/src/lib/css/dark/header.scss
packages/svelte-maplibre-storymap/src/lib/css/light/footer.scss
packages/svelte-maplibre-storymap/src/lib/css/light/header.scss
sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte

also fixed layout collapse of storymap in responsive

fix: chapter preview image location

---

.changeset/strong-sheep-divide.md
sites/geohub/src/routes/(app)/storymaps/[id]/+page.svelte

fix: relayout /storymaps/{id} page layout by merging info and preview

---

.changeset/plenty-boats-help.md
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte

fix: bug of switching slide setting from header and chapter

---

.changeset/late-olives-refuse.md
.changeset/many-shoes-boil.md
packages/undp-bulma/bulma.scss
packages/undp-bulma/src/main.ts

fixes #3844 
also fixed heading style to align with UNDP design. now change font-size according to window width.
https://design.undp.org/?path=/story/foundation-typography-base-typography--headings

fix: delete button and heading style of undp-bulma

---

sites/geohub/src/routes/(map)/dashboards/ceei/+page.ts

fix: added +page.ts to show page metadata for CEEI dashboard

---

pnpm-lock.yaml
sites/geohub/package.json

fix: moved frontend dependencies (joi, pako, topojson-client, xlsx) to devDependencies

---

.changeset/sharp-ears-tickle.md
sites/geohub/src/components/pages/storymap/StorymapStyleSelector.svelte

fix: show GeoHub map preview next to GEOHUB MAP CATALOG button if a map is selected

---

.changeset/few-melons-complain.md
.changeset/shiny-kings-crash.md
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
sites/geohub/src/routes/(storymap)/storymaps/[id]/viewer/+page.svelte

fix: fixed bug of layout collapse of storymap footer together with UNDP footer

---

.changeset/eighty-pugs-complain.md
sites/geohub/src/routes/(storymap)/storymaps/[id]/viewer/+page.svelte

fix: fixed position of BackToTop component for storymap viewer

---

sites/geohub/src/routes/(map)/dashboards/+layout.server.ts
sites/geohub/src/routes/(map)/dashboards/+layout.svelte
sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/+page.ts

- +layout.server.ts to generate original URLs for dashboards
- define Header at +layout.svelte

refactor: added +layout for both dashboards

---

.changeset/stupid-starfishes-perform.md
sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte

fixes #3890
- first chapter
- middle chapter
- last chapter

fix: added up/down button in chapter mini preview to change order.

---

sites/geohub/src/routes/(map)/dashboards/+layout.server.ts
sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte

fix: added maptiler geocoder for dashboards

---

.changeset/tall-crabs-know.md
sites/geohub/src/routes/(map)/dashboards/ceei/components/PopupTable.svelte

- [ X Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

feat: Add reference year to popup

---

.changeset/stupid-starfishes-perform.md
sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte

fixes #3896
Reverts UNDP-Data/geohub#3896

Revert "fix: added up/down button in chapter mini preview to change order."

---

.changeset/early-dodos-wonder.md
sites/geohub/src/routes/(map)/dashboards/+layout.server.ts
sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte

fix: added IBM attribution to maplibre of dashboards

---

.changeset/cuddly-falcons-relax.md
packages/svelte-maplibre-storymap/src/lib/StoryMapFooter.svelte
packages/svelte-maplibre-storymap/src/lib/StoryMapHeader.svelte
packages/svelte-maplibre-storymap/src/lib/css/dark/footer.scss
packages/svelte-maplibre-storymap/src/lib/css/dark/header.scss
packages/svelte-maplibre-storymap/src/lib/css/light/footer.scss
packages/svelte-maplibre-storymap/src/lib/css/light/header.scss
sites/geohub/src/components/pages/storymap/StorymapHeaderFooterMiniPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapHeaderFooterPreview.svelte
sites/geohub/src/lib/server/StorymapManager.ts
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte

#3852 is partially fixed only for header/footer parts

fix: add header and footer sidebar preview

---

.changeset/slow-spies-float.md
sites/geohub/src/routes/(app)/data/+page.svelte
sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.svelte
sites/geohub/src/routes/(app)/data/[id]/+page.svelte
sites/geohub/src/routes/(app)/data/[id]/style/edit/+page.svelte
sites/geohub/src/routes/(app)/data/supported-formats/+page.svelte
sites/geohub/src/routes/(app)/data/upload/+page.svelte
sites/geohub/src/routes/(app)/license/+page.svelte
sites/geohub/src/routes/(app)/management/+page.svelte
sites/geohub/src/routes/(app)/management/pgtileserv/+page.svelte
sites/geohub/src/routes/(app)/management/stac/+page.svelte
sites/geohub/src/routes/(app)/management/stac/api/[id]/+page.svelte
sites/geohub/src/routes/(app)/management/stac/api/[id]/[collection]/+page.svelte
sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte
sites/geohub/src/routes/(app)/maps/+page.svelte
sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
sites/geohub/src/routes/(app)/storymaps/[id]/+page.svelte
sites/geohub/src/routes/(app)/tools/+page.svelte

fix: changed margin of page contents as 48px (3rem)

---

.changeset/chilly-schools-smell.md
sites/geohub/src/routes/(app)/storymaps/[id]/+page.svelte

feat: added duplicate storymap button

---

.changeset/wicked-rules-compete.md
packages/svelte-maplibre-storymap/package.json
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
packages/svelte-maplibre-storymap/src/routes/+page.server.ts
pnpm-lock.yaml

fix: redesigned slide progress bar for storymaps

---

packages/svelte-maplibre-storymap/package.json
pnpm-lock.yaml

fix: removed @types/svelte-range-slider-pips from storymap plugin

---

.changeset/tough-files-leave.md
packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
packages/svelte-maplibre-storymap/src/lib/css/dark/header.scss
packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
packages/svelte-maplibre-storymap/src/lib/css/light/header.scss

fix: fixed responsive design of storymap

---

.changeset/sharp-cherries-help.md
sites/geohub/src/components/pages/storymap/StorymapHeaderFooterMiniPreview.svelte
sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.server.ts
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte

fixes #3881 
also fixed a bug of footer minipreview layout bug

feat: added create storymap button in map page.

---

.changeset/eleven-seals-fly.md
packages/svelte-undp-components/src/lib/components/ModalNotification.stories.ts
packages/svelte-undp-components/src/lib/components/ModalNotification.svelte
packages/svelte-undp-components/src/lib/components/Notification.stories.ts
packages/svelte-undp-components/src/lib/components/Notification.svelte

fix: hide icon as default for ModalNotification component. Also, changed button color.

---

.changeset/eight-islands-drop.md
sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte

fix: changed size of segment buttons to normal for slide transition.

---

.changeset/grumpy-trains-learn.md
packages/svelte-undp-components/src/lib/components/FieldControl.stories.ts
packages/svelte-undp-components/src/lib/components/FieldControl.svelte
packages/svelte-undp-components/src/lib/components/Help.stories.ts
packages/svelte-undp-components/src/lib/components/Help.svelte

fixes #3945 
fixes #3938
also added size and type options for Help component 

fix: changed fontawesome to material icon for Help component.

---

.changeset/lucky-weeks-thank.md
sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterLayerEventEditor.svelte
sites/geohub/src/components/util/OpacityEditor.svelte

fix: redesigned layer visibility component for storymap editor. also removed onExit.

---

.changeset/heavy-news-serve.md
.changeset/tough-cycles-hug.md
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/+layout@.svelte
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte

fix: scroll problem of storymap preview is fixed now. but progress bar was removed from preview since it has problem for preview.

---

.changeset/violet-pugs-shake.md
sites/geohub/src/components/pages/storymap/MapLocationSelector.svelte
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/+layout.server.ts

fixes #3942
I moved coordinates and zoom info to popup of marker, and added maptiler geocoder
this maptiler geocoder can also provide reverse geocoding (search by latitude, longitude)

fix: added maptiler geocoder for maplocation prop of storymap editor.

---

.changeset/lucky-crabs-remember.md
packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte

fix: set max-width as 512px for storymap slide card.

---

.changeset/late-jobs-look.md
docker/docker-build-prod.sh
pnpm-lock.yaml
sites/geohub/package.json

server is down because of the following error. I saw node-canvas repo to use canvas@next may solve some issues on npm, just want to try.
```shell
2024-08-21T15:01:19.799808009Z: [ERROR]  Error: libuuid.so.1: cannot open shared object file: No such file or directory
2024-08-21T15:01:19.799811309Z: [ERROR]      at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
2024-08-21T15:01:19.799814609Z: [ERROR]      at Module.load (node:internal/modules/cjs/loader:1208:32)
2024-08-21T15:01:19.799818009Z: [ERROR]      at Module._load (node:internal/modules/cjs/loader:1024:12)
2024-08-21T15:01:19.799821109Z: [ERROR]      at Module.require (node:internal/modules/cjs/loader:1233:19)
2024-08-21T15:01:19.799824209Z: [ERROR]      at require …
```

fix: changed canvas to canvas@next

---

.changeset/swift-buses-love.md
pnpm-lock.yaml
sites/geohub/package.json
sites/geohub/src/lib/server/helpers/generateLegendFromStyle.ts
sites/geohub/src/lib/server/helpers/index.ts

fix: because server is down, removed node-canvas temporally.

---

.changeset/flat-cows-smash.md
sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
sites/geohub/src/routes/(app)/settings/+page.svelte

fix: changed font weight to normal for segment buttons used in storymap.

---

.changeset/two-dolphins-glow.md
packages/svelte-undp-components/src/lib/components/Slider.svelte

fix: changed slide color to blue-300 of UNDP design system.

---

.changeset/calm-maps-marry.md
.changeset/ten-gorillas-occur.md
packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte

fix: fixed css for full alignment, and redesigned card alignment and full width

---

.changeset/neat-windows-train.md
sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte

fix: set untitle as default value for title of storymap

---

.changeset/brown-bobcats-rush.md
.changeset/slimy-dogs-behave.md
packages/svelte-undp-components/src/lib/components/ModalTemplate.svelte
sites/geohub/.gitignore
sites/geohub/package.json
sites/geohub/src/components/header/UserAccount.svelte

- added changelog menu in user menu
- show changelog as dialog

feat: show changelog from user account menu

---

.changeset/thin-owls-crash.md
sites/geohub/src/components/pages/home/MapStyleCardList.svelte
sites/geohub/src/components/pages/storymap/GeoHubMapSelector.svelte
sites/geohub/src/components/pages/storymap/StorymapTable.svelte
sites/geohub/src/routes/(app)/maps/+page.svelte
sites/geohub/src/routes/(app)/storymaps/+page.svelte
sites/geohub/src/routes/api/style/+server.ts
sites/geohub/static/api/swagger/spec.yaml

fixes #3878
implemented based on this figma (https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3282-1940&node-type=CANVAS&m=dev) to introduce same UI of storymap portal.
also updated geohub map selector on storymap editor.
documentation will be updated later after merging this PR.

fix: redesigned map portal

---

.changeset/little-cougars-speak.md
sites/geohub/src/routes/(app)/management/stac/api/[id]/+page.svelte

Fixed the  bug of updating access level
Fixes #4021 

fix: updating of access level

---

.changeset/lovely-brooms-juggle.md
sites/geohub/src/lib/server/SvgLegendCreator.ts

fix: show zero value for minimum label of raster linear legend.

---

.changeset/healthy-peaches-live.md
sites/geohub/src/components/pages/home/MapStyleCardList.svelte

I did a mistake to cause layout collapse in responsive.

fix: fixed layout collapse of map page in responsive.

---

.changeset/curvy-shoes-sleep.md
.changeset/healthy-coats-impress.md
.changeset/hip-trains-sell.md
.changeset/hungry-bikes-beg.md
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
packages/svelte-undp-components/src/lib/components/Accordion.stories.ts
packages/svelte-undp-components/src/lib/components/Accordion.svelte
packages/svelte-undp-components/src/lib/util/clean.ts
sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
sites/geohub/src/lib/server/StorymapManager.ts
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+layout.server.ts
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.server.ts
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.svelte
sites/geohub/src/routes/api/storymaps/+server.ts

fixes #3869 
fixes #3940
fixes #3923

fix: allow users to save storymap without chapters.

---

.changeset/healthy-fans-remember.md
packages/svelte-maplibre-storymap/src/lib/MaplibreLegendControl.svelte
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte

fix: hide invisilble layer and removed opacity/visibility buttons for storymap legend

---

.changeset/tender-bags-look.md
sites/geohub/src/routes/(map)/dashboards/ceei/components/PopupTable.svelte

Adds sources to CEEI popup as requested in #4062
- [ X Make sure all the existing features working well

fix: Add sources to CEEI popup

---

.changeset/moody-timers-applaud.md
.changeset/popular-crews-drop.md
packages/svelte-undp-components/src/lib/components/HeroHeader.svelte
packages/svelte-undp-components/src/lib/components/MenuButton.stories.ts
packages/svelte-undp-components/src/lib/components/MenuButton.svelte
packages/svelte-undp-components/src/lib/components/index.ts
packages/svelte-undp-design/package.json
packages/svelte-undp-design/src/lib/Checkbox/Checkbox.svelte
pnpm-lock.yaml

fix: Checkbox bugs in UNDP design and new MenuButton component

---

.changeset/early-news-shout.md
.changeset/twelve-dots-accept.md
packages/svelte-maplibre-storymap/src/lib/MaplibreLegendControl.svelte
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
packages/svelte-maplibre-storymap/src/lib/StoryMapChapter.svelte
packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
packages/svelte-maplibre-storymap/src/lib/css/dark/header.scss
packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
packages/svelte-maplibre-storymap/src/lib/css/light/header.scss
sites/geohub/src/components/pages/storymap/MapLocationSelector.svelte

fixes #4084 
fixes #4082 
fixes #4085 
fixes #3992
fixes #4083

fix: bugs and UI for storymap viewer

---

.changeset/serious-numbers-smile.md
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte

fix: fixed bug of hiding storymap pagination control when scroll is beyond footer.

---

.changeset/nine-hornets-stare.md
sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte

fix: remove ibm logo

---

.changeset/slow-actors-notice.md
packages/svelte-maplibre-storymap/src/lib/MaplibreLegendControl.svelte

fix: set ProximaNova for the font of legend control.

---

.changeset/breezy-turtles-attack.md
packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss

fix: set max-height to 512px and align left for storymap slide image.

---

.changeset/good-games-peel.md
.changeset/tame-islands-film.md
packages/svelte-maplibre-storymap/src/lib/css/markdown-style.scss
pnpm-lock.yaml
sites/geohub/package.json
sites/geohub/src/components/pages/storymap/MarkdownEditor.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte

fixes #4100 
I used this simple markdown editor.
https://github.com/Ionaru/easy-markdown-editor

fix: add markdown editor for chapter description and footer text

---

.changeset/gorgeous-pants-deny.md
sites/geohub/src/routes/(app)/maps/+page.svelte
sites/geohub/src/routes/(app)/storymaps/+page.svelte

fix: fixed typo. changed to plural like my maps and my storymaps

---

.changeset/dull-planes-mix.md
sites/geohub/src/components/pages/storymap/MarkdownEditor.svelte

fix: changed markdown editor's font color.

---

.changeset/perfect-olives-bow.md
sites/geohub/src/components/pages/storymap/MarkdownEditor.svelte

fix: fixed border color of markdown editor.

---

.changeset/shaggy-foxes-decide.md
.changeset/tall-pumpkins-rush.md
sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapHeaderMiniPreview.svelte
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.svelte

fixes #4109
- fix: show footer tab in header slide editor if no chapter.
- fix: added a stripe to chapter preview if it is the last slide.

fix: added a stripe to chapter preview if it is the last slide.

---

.changeset/proud-rivers-call.md
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
packages/svelte-maplibre-storymap/src/lib/StoryMapFooter.svelte
packages/svelte-maplibre-storymap/src/lib/css/dark/footer.scss
packages/svelte-maplibre-storymap/src/lib/css/light/footer.scss
sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.svelte

fixes #4110 
I believe now it is improved

fix: try to fix avoid overlapping footer and map in storymap

---

.changeset/poor-trainers-sniff.md
sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapHeaderMiniPreview.svelte

fix: fixed button style on side bar preview of storymap.

---

.changeset/witty-shrimps-learn.md
sites/geohub/src/components/pages/storymap/ImageUploader.svelte

fix: add GIF for image support in storymap.

---

backends/k8s/cogserver/yaml/cogserver-deployment.yaml
backends/k8s/cogserver/yaml/cogserver-dev-deployment.yaml

fix ci for cogserver. 
I think now dev and prod are completely same

fix: make cogserver deploy yaml files are same for dev and prod

---

.changeset/lucky-yaks-accept.md
packages/svelte-maplibre-storymap/src/lib/css/dark/header.scss
packages/svelte-maplibre-storymap/src/lib/css/light/header.scss

fix: adjusted storymap header style of margin and line-height

---

.changeset/pretty-toes-remain.md
sites/geohub/src/lib/server/helpers/loadStorymapById.ts
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.server.ts
sites/geohub/src/routes/(app)/storymaps/[id]/+page.server.ts
sites/geohub/src/routes/(app)/storymaps/[id]/viewer/+page.server.ts

fix: change storymap viewer access level when it is embed mode.

---

.changeset/new-numbers-grab.md
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
packages/svelte-maplibre-storymap/src/lib/StoryMapChapter.svelte
packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
sites/geohub/src/components/pages/storymap/StorymapFooterEditPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapFooterMiniPreview.svelte

fix: removed margin-bottom from last slide of storymap. enable pointer-events for slide card.

---

pnpm-lock.yaml
sites/static-image-api/package-lock.json

Revert "chore(deps): lock file maintenance"

---

.changeset/small-lemons-change.md
sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/IntroductionPanel.svelte

Changed some of the introduction text in Dashboards

refactor: change text in dashboards

---

pnpm-lock.yaml
sites/geohub/package.json

Revert "chore(deps): update dependency @auth/core to ^0.35.0"

---

.changeset/green-spoons-add.md
sites/geohub/src/components/util/stac/StacApiExplorer.svelte
sites/geohub/src/lib/RasterTileData.ts
sites/geohub/src/lib/server/helpers/createDatasetLinks.ts
sites/geohub/src/routes/api/datasets/style/[layer]/[type]/+server.ts

fix: Fixed #4191 to return normal metadata without algorithm.

---

.changeset/dry-otters-turn.md
packages/svelte-maplibre-storymap/src/lib/css/dark/header.scss
packages/svelte-maplibre-storymap/src/lib/css/light/header.scss

fix: fixed the layout of header preview with logo in sidebar

---

.changeset/real-mails-know.md
packages/svelte-static-image-controls/package.json
packages/svelte-static-image-controls/src/lib/MaplibreStaticImageControl.svelte
packages/svelte-static-image-controls/src/lib/StaticImageControl.svelte
pnpm-lock.yaml

Fix/4205 export control UI

---

.changeset/eighty-taxis-learn.md
sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
sites/geohub/src/lib/types/IngestingDataset.ts
sites/geohub/src/routes/api/datasets/ingesting/+server.ts

fixes #3757
pipeline side will be fixed by https://github.com/UNDP-Data/geohub-data-pipeline/pull/56.
PR in geohub side should be merged prior to bump data-pipleine docker

fix: handle fgbs which new datapipeline will upload together with PMTiles to make sure delete them when ingesting dataset is deleted.

---

backends/k8s/data-pipeline/yaml/ingest-environment.yaml

Revert "[RELEASE] bump version of geohub-data-pipeline"

---

.changeset/metal-avocados-sell.md
sites/geohub/src/lib/server/helpers/getDatasetById.ts
sites/geohub/src/routes/api/datasets/+server.ts

fix: sort by createdat if updatedat is not avaiable in dataset

---

.changeset/twelve-avocados-pay.md
pnpm-lock.yaml
sites/geohub/package.json
sites/geohub/src/routes/api/datasets/[id]/+server.ts
sites/geohub/src/routes/api/datasets/[id]/table/layers/[layer].[format]/+server.ts
sites/geohub/static/api/swagger/spec.yaml

fixes #4225
- feat: add /api/datasets/{id}/table/layers/{layer} endpoint to fetch attribute table data for a dataset.

feat: add /api/datasets/{id}/table/layers/{layer} endpoint to fetch attribute table data for a dataset.

---

.changeset/red-jokes-cheer.md
sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/components/IntroductionPanel.svelte

Removed IBM text from IntroductionPanel

fix: ibm text

---

.changeset/wild-houses-buy.md
sites/geohub/src/lib/server/helpers/index.ts
sites/geohub/src/lib/server/helpers/parseCqlFilter.test.ts
sites/geohub/src/lib/server/helpers/parseCqlFilter.ts
sites/geohub/src/routes/api/datasets/[id]/table/layers/[layer].[format]/+server.ts
sites/geohub/static/api/swagger/spec.yaml

fix: added cql_filter to table search endpoint

---

.changeset/tiny-cooks-complain.md
sites/geohub/src/components/pages/map/layers/vector/VectorTable.svelte
sites/geohub/src/lib/server/helpers/createDatasetLinks.ts
sites/geohub/src/routes/api/datasets/[id]/table/layers/[layer].[format]/+server.ts
sites/geohub/static/api/swagger/spec.yaml

[Please describe what you changed briefly.](fix: add `compress` query param to /table endpoint to compress json/geojson response to gzip. If format is either `csv` or `xlsx`, `compress=true` will be ignored. Regarding to the use of compress API in Nodejs and Javascript, please refer to [this article](https://dev.to/ternentdotdev/json-compression-in-the-browser-with-gzip-and-the-compression-streams-api-4135).)

fix: add compress query param to /table endpoint to compress json/geojson response to gzip.

---

.changeset/sweet-birds-invite.md
sites/geohub/src/components/pages/map/layers/vector/VectorTable.svelte

fixed bug of remaining sort setting in table component

fix: clear sort setting when table is closed.

---

.changeset/breezy-horses-listen.md
sites/geohub/src/components/maplibre/symbol/IconSize.svelte

fix: add error handling in IconSize when loading sprite image

---

.changeset/tame-steaks-beam.md
sites/geohub/src/components/pages/data/ingesting/IngestingDatasetHeader.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorTable.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorTableColumn.svelte

fix: fixed bug of sorting order of table feature

---

.changeset/spotty-chefs-appear.md
sites/geohub/src/lib/helper/expression2cql.test.ts
sites/geohub/src/lib/helper/expression2cql.ts

I did mistake on operator of differs (not `!=`, it is `<>`)

fix: fixed bug to apply differs filter to table.

---

.changeset/dry-moons-smoke.md
sites/geohub/src/components/pages/map/layers/vector/PropertySelectButtons.svelte
sites/geohub/src/components/pages/map/layers/vector/ValueInput.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorFilter.svelte

looks like that slider bug #4272 was there when field data type is mixed, hope this PR fixes #4272

fix: treat mixed data type as string property

---

.changeset/cold-ants-pump.md
sites/geohub/src/components/pages/map/layers/vector/VectorTable.svelte
sites/geohub/src/routes/api/datasets/[id]/table/layers/[layer].[format]/+server.ts

also, keep row selection in table

fix: show marker for selected row by left/right click.

---

.changeset/nine-coats-march.md
sites/geohub/src/components/pages/map/layers/vector/VectorFilter.svelte

fix: avoid creating incomplete maplibre filter when OR/AND is changed.

---

.changeset/real-schools-mix.md
sites/geohub/src/components/pages/map/layers/vector/PropertySelectButtons.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorFilter.svelte

fix: change red button color to blue color. change property cards to selectbox in VectorFiler.

fix: change red button color to blue color. change property cards to selectbox in VectorFiler.

---

documentation/mkdocs.yml

doc: add ceei_slide.md to mkdocs.yml

---

.changeset/sixty-rockets-sell.md
sites/geohub/src/routes/api/settings/+server.ts

fix: deleted console.log from /api/settings

---

.changeset/new-moles-study.md
sites/geohub/src/components/pages/map/layers/LayerEdit.svelte

fix: sync opacity value to slider value when editor is opened.

---

.changeset/lucky-beans-sort.md
sites/geohub/src/lib/server/helpers/existsFileInBlobstorage.ts

fix: decode blob name before checking existance of flatgeobuf.

---

.changeset/serious-wombats-allow.md
sites/geohub/src/components/maplibre/vector/VectorColorClassification.svelte
sites/geohub/src/lib/server/helpers/generateLegendFromStyle.ts

fix: wrap step expression by case expression to set transparent color if a property is missing in a feature.

---

.changeset/kind-cars-sit.md
sites/geohub/src/components/pages/map/layers/vector/VectorTableColumn.svelte

fix: make overflowed name ellipsis as ... if name is longer.

---

.changeset/silly-carrots-teach.md
sites/geohub/src/components/pages/map/layers/vector/VectorTable.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorTableColumn.svelte

fix: show menu by clicking header column to sort directly by asc or desc instead of toggling with click

---

.changeset/famous-toes-glow.md
sites/geohub/src/components/pages/map/layers/LayerList.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorTable.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorTableColumn.svelte
sites/geohub/src/lib/helper/expression2cql.ts

fix: always show header while showing loader in attribute table. also bring id/fid column first.

---

.changeset/thick-carrots-thank.md
sites/geohub/src/components/pages/map/layers/vector/VectorTableColumn.svelte

fix: fixed ssr for VectorTableColumn componenent

---

.changeset/eight-schools-exercise.md
sites/geohub/src/components/pages/data/datasets/DatasetPreview.svelte
sites/geohub/src/components/util/MiniMap.svelte
sites/geohub/src/lib/VectorTileData.ts

fix: fixed bug of 3D polygon preview for data page.

---

.changeset/late-forks-pretend.md
sites/geohub/src/components/maplibre/fill-extrusion/FillExtrusionHeight.svelte

fix: add switch control to enable/disable of logarithmic of 3D height Changed label to Low/High

---

.changeset/fast-grapes-leave.md
sites/geohub/src/components/pages/map/layers/vector/VectorTable.svelte

fix: fixed position of table content loader

---

.changeset/silver-cherries-attack.md
sites/geohub/src/components/pages/map/layers/vector/VectorTable.svelte

fix: fixed showing context menu for table.

---

.changeset/spicy-chicken-relax.md
pnpm-lock.yaml
sites/geohub/package.json

fix: removed unused svelte-body from dependencies

---

.changeset/fair-crabs-occur.md
sites/geohub/src/components/pages/map/layers/vector/VectorTable.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorTableColumn.svelte

fix: show histogram in front of all elements.

---

.changeset/many-eyes-grab.md
sites/geohub/src/components/util/ColorPicker.svelte

fix: enable text input for color picker.

---

.changeset/khaki-olives-enjoy.md
packages/svelte-maplibre-storymap/package.json
packages/svelte-static-image-controls/package.json
packages/svelte-undp-components/package.json
packages/svelte-undp-design/package.json

fix: add svelte 5 to peer dependencies

---

.changeset/witty-falcons-turn.md
packages/svelte-undp-components/src/lib/components/CopyToClipboard.svelte

fix: fixed the way of selecting text when input element is focused.

---

.changeset/proud-shirts-agree.md
sites/geohub/src/components/maplibre/vector/VectorColorClassification.svelte
sites/geohub/src/components/maplibre/vector/VectorValueClassification.svelte
sites/geohub/src/lib/helper/getSampleFromHistogram.test.ts
sites/geohub/src/lib/helper/getSampleFromHistogram.ts
sites/geohub/src/lib/helper/index.ts

fix: get samples from histogram if stats.values is not available.

---

.changeset/smooth-tigers-call.md
sites/geohub/src/lib/server/helpers/generateLegendFromStyle.ts

fix: apply line-dasharray setting for legend

---

.changeset/eight-books-do.md
.changeset/orange-colts-kick.md
packages/svelte-undp-components/src/lib/util/isValidUrl.ts
sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte

fix: show image if URL is image format. also show a tag if string is valid URL (not image) in popup.

---

.changeset/fast-buses-wink.md
.changeset/plenty-starfishes-tease.md
sites/geohub/src/routes/(app)/maps/[id]/+page.svelte

feat: duplicate button to copy existing map and renamed EDIT button to EDIT METADATA button.

---

.changeset/nine-lions-allow.md
sites/geohub/src/lib/server/helpers/parseCqlFilter.test.ts
sites/geohub/src/lib/server/helpers/parseCqlFilter.ts

fix: fixed bug of table filtration if a field name at the left side of operator consists of multiple words with whitespace.

---

.changeset/smart-ducks-sip.md
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
packages/svelte-maplibre-storymap/src/lib/interfaces/StoryMapConfig.ts
packages/svelte-maplibre-storymap/src/routes/+page.server.ts
packages/svelte-maplibre-storymap/vite.config.ts
sites/geohub/drizzle/0001_demonic_mentallo.sql
sites/geohub/drizzle/meta/0001_snapshot.json
sites/geohub/drizzle/meta/_journal.json
sites/geohub/src/components/pages/storymap/MapLocationSelector.svelte
sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapHeaderMiniPreview.svelte
sites/geohub/src/lib/server/StorymapManager.ts
sites/geohub/src/lib/server/schema.ts
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.svelte

feat: add location property for storymap header to allow users to change default location of header slide.

---

.changeset/smart-ducks-sip.md

fixed changeset error

---

sites/static-image-api/src/lib/helpers/handleEnterKey.ts
sites/static-image-api/src/routes/(app)/+page.svelte

fix: changed dropdown for style examples to textbox to allow pasting other style url.

---

.changeset/slimy-shirts-fetch.md
sites/geohub/src/components/maplibre/symbol/TextField.svelte

fix: set default text color and halo color appropriately when label is created.

---

.changeset/witty-pens-wave.md
sites/geohub/src/components/maplibre/symbol/TextField.svelte

fix: changed text-radial-offset from 0.5 to 1.0 since there is some overlaps between icon and label.

---

.changeset/empty-mice-sip.md
sites/geohub/src/components/pages/map/Map.svelte
sites/geohub/src/lib/types/IntroJsOptions.ts

fix: add intro.js option to change cookie key.

---

.changeset/early-frogs-kneel.md
sites/geohub/src/components/pages/map/plugins/TourControl.svelte

fix: forgot to pass donwShowAgainCookie value to introjs instance.

---

.changeset/twelve-eggs-hide.md
sites/geohub/src/components/pages/map/Map.svelte

fix: fixed bug of tour of map editor when layers tab is active.

---

.changeset/silly-oranges-hide.md
packages/svelte-undp-components/src/lib/components/maplibre/symbol/IconSize.svelte
packages/svelte-undp-components/src/lib/util/getIntervalList.ts

fix: fixed bug of IconSize not being updated when icon-image is changed

---

.changeset/poor-walls-yell.md
sites/geohub/src/components/pages/map/Content.svelte
sites/geohub/src/components/pages/map/Map.svelte
sites/geohub/src/components/pages/map/layers/LayerList.svelte
sites/geohub/src/lib/config/AppConfig/TabNames.ts

fix: moved map export control to sidebar. If click export button in layer tab, export tab is added.

---

sites/static-image-api/src/lib/server/renderMap.ts

fix: replace Proxima Nova to Open Sans, and replace space separated rgb to comma separated rgb.

---

.changeset/kind-bananas-jog.md
sites/geohub/src/components/pages/map/layers/LayerList.svelte

fix: fixed save/update button color to blue.

---

.changeset/friendly-fans-impress.md
pnpm-lock.yaml
sites/geohub/package.json

fixed bug of style due to Proxima Nova Italic name change

fix: updated style version to 2.3.3

---

sites/static-image-api/package-lock.json
sites/static-image-api/package.json
sites/static-image-api/src/lib/server/sources/pmtiles.ts
sites/static-image-api/src/lib/server/sources/vt-pbf.d.ts

fix: regenerate requested tile from a tile at max zoom of pmtiles for overzooming feature.

---

.changeset/perfect-parrots-turn.md
sites/geohub/src/routes/(app)/dashboards/zanzibar/+page@.svelte

feat: add export button to Zanzibar dashboard.

---

.changeset/large-humans-train.md
sites/geohub/src/components/pages/map/layers/LayerList.svelte

fix: disable save button if users do not sign in.

---

.changeset/fast-pillows-thank.md
sites/geohub/src/components/pages/map/Map.svelte
sites/geohub/src/components/pages/map/layers/LayerList.svelte
sites/geohub/src/components/pages/storymap/MapLocationSelector.svelte
sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte
sites/geohub/src/components/pages/storymap/StorymapHeaderMiniPreview.svelte
sites/geohub/src/routes/(app)/maps/[[id]]/edit/+layout@.svelte
sites/geohub/src/routes/+layout.svelte

fix: improved UI of unsaved dialog and show tooltip for layer tab footer buttons.

---

.changeset/late-islands-brush.md
sites/geohub/src/routes/(app)/maps/[id]/+page.svelte

fix: rename view button to edit button in map page.

---

.changeset/dirty-beers-bathe.md
sites/geohub/src/components/pages/data/datasets/DatasetPreview.svelte
sites/geohub/src/components/pages/map/data/DataVectorCard.svelte
sites/geohub/src/components/util/MiniMap.svelte

fix: improved MiniMap initialization when layer type is changed.

---

.changeset/fifty-snakes-cry.md
packages/svelte-undp-components/src/lib/components/pg_tileserv/VectorSimulation.svelte
sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte

fix: fixed bug of default style editor for vector dataset.

---

.changeset/three-melons-argue.md
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.svelte

fix: refresh chapter editor when the editor is opened

---

.changeset/mean-carpets-shave.md
sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte

fix: set default hillshade value in storymap from database

---

.changeset/fair-lions-impress.md
packages/svelte-maplibre-storymap/package.json
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
pnpm-lock.yaml
sites/geohub/src/components/pages/storymap/StorymapStyleSelector.svelte

removed maplibre-gl-sky plugin from storymap. it caused the issue when terrain is turned on

fix: add terrain mode for storymap.

---

.changeset/red-emus-draw.md
sites/geohub/src/components/util/Iframe.svelte
sites/geohub/src/routes/(app)/storymaps/[id]/+page.svelte

refactor: merged Iframe component to storymap's +page.svete

---

.changeset/strange-glasses-thank.md
packages/svelte-undp-design/src/lib/Header/Header.stories.ts
packages/svelte-undp-design/src/lib/Header/Header.svelte
packages/svelte-undp-design/src/lib/interfaces/HeaderLink.ts
sites/geohub/src/lib/server/config/HeaderItems.ts

fix: add an option of link type to apply icons like external link or download link for UNDP header.

---

.changeset/swift-jobs-pull.md
sites/geohub/src/lib/server/StorymapManager.ts
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.server.ts
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.svelte

fix: fixed bug of saving storymap when it is created directlink of map

---

.changeset/fluffy-dingos-taste.md
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.svelte

fix: fixed bug of saving storymap without chapters from base style

---

.changeset/eight-seahorses-joke.md
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.server.ts
sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.svelte

fix: show storymap builder even users do not sign in.

---

.changeset/smooth-parents-battle.md
packages/svelte-undp-design/src/lib/Header/Header.svelte

fix: nowrap for region title in UNDP header.

---

.changeset/afraid-insects-perform.md
.changeset/curvy-walls-kneel.md
.changeset/lucky-geese-sit.md
packages/svelte-undp-components/src/lib/components/ui/HeroLink.svelte
packages/svelte-undp-design/src/lib/Button/Button.svelte
packages/svelte-undp-design/src/lib/FluidCarousel/FluidCarousel.svelte
sites/geohub/src/components/pages/map/MapStyleCardList.svelte
sites/geohub/src/lib/config/DefaultUserConfig/HomePageMapSearchLimit.ts
sites/geohub/src/lib/config/DefaultUserConfig/HomePageMapSortingColumn.ts
sites/geohub/src/lib/config/DefaultUserConfig/index.ts
sites/geohub/src/routes/(app)/+page.server.ts
sites/geohub/src/routes/(app)/+page.svelte

fix: adjusted landing page layout in terms of UI concerns

---

.changeset/weak-birds-remember.md
sites/geohub/src/components/pages/map/MapHero.svelte
sites/geohub/src/routes/(app)/auth/signIn/+page.svelte

fix: fixed signin page layout collapse in mobile

---

.changeset/wet-eyes-breathe.md
sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte

`/tiles/{z}/{x}/{y}.png` will not be supported in titiler v0.19

fix: use /tiles/WebMercatorQuad/{z}/{x}/{y}.png in Electricity Dashboard

---

.changeset/bright-doors-remain.md
sites/geohub/src/components/pages/map/data/DataCard.svelte
sites/geohub/src/components/util/stac/StacApiExplorer.svelte
sites/geohub/src/lib/RasterTileData.ts

also, keep selected feature when tab is changed

fix: show tool components when a tool is selected. Also, fixed bug of tools tab is not shown in map page

---

.changeset/cold-squids-obey.md
sites/geohub/svelte.config.js
sites/static-image-api/svelte.config.js

chore: use named import of sveltePreprocess

---

.changeset/heavy-horses-hug.md
sites/geohub/src/components/pages/map/Content.svelte
sites/geohub/src/components/pages/map/layers/LayerInfo.svelte
sites/geohub/src/components/pages/map/layers/LayerList.svelte
sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
sites/geohub/src/components/pages/map/layers/StyleSaveDialog.svelte
sites/geohub/src/components/pages/map/layers/StyleShareDialog.svelte
sites/geohub/src/components/pages/map/layers/order/LayerOrderPanelButton.svelte
sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
sites/geohub/src/components/pages/map/layers/raster/RasterLegend.svelte
sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte
sites/geohub/src/components/pages/map/layers/vector/OperationButtons.svelte
sites/geohub/src/components/pages/map/layers/vector/TextField.svelte
sites/geohub/src/components/pages/map/layers/vector/ValueInput.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorFilter.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorLabelPanel.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorLegend.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorTable.svelte
sites/geohub/src/components/util/Step.svelte
sites/geohub/src/components/util/Wizard.svelte

4333 migrate svelte5 map editor

---

.changeset/nice-peas-wash.md
sites/geohub/src/components/pages/map/layers/LayerEdit.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorLegend.svelte

fix: fixed bug of when layer is deleted.

---

.github/workflows/ci.yml

fix: there is an error of setting EOG_USER and EOG_PASSWORD

---

.github/workflows/ci.yml

Instead of using [azure-blob-storage-upload](https://github.com/bacongobbler/azure-blob-storage-upload) action since it has error, I switched to use official [azure/CLI](https://github.com/Azure/cli) action

fix: use azure@CLI instea of using third party azure-blob-storage-upload

---

.github/workflows/ci.yml

Reverts UNDP-Data/geohub#4721
let's revert this for now until I find a way

Revert "fix: use azure@CLI instea of using third party azure-blob-storage-upload"

---

.github/workflows/ci.yml

fix: change to use azure/cli action for fixing azcopy connection error

---

.changeset/dry-hotels-tell.md
packages/svelte-maplibre-storymap/package.json
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
pnpm-lock.yaml
sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte

fixes #4739 (hope this can fix, the bug is not reproducible in local...)

fix: add pmtiles protocol at the StoryMap component inside.

---

.changeset/witty-wasps-complain.md
packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
sites/geohub/src/lib/server/helpers/loadStorymapById.ts
sites/geohub/src/routes/(app)/storymaps/[id]/viewer/+page@.svelte
sites/geohub/src/routes/api/storymaps/[id]/+server.ts

fix: fixed bug of not setting default location in storymap if users do not customise.

---

.changeset/green-drinks-clap.md
packages/svelte-undp-design/src/lib/SearchExpand/SearchExpand.svelte
sites/geohub/src/components/pages/map/layers/vector/VectorTable.svelte

fix: fixed vector table searching behaviour

---

.changeset/late-suns-poke.md
packages/undp-bulma/bulma.scss
packages/undp-bulma/package.json
packages/undp-bulma/src/main.ts
pnpm-lock.yaml

fix: fixed bug of undp bulma css building. use sass to build

---

.changeset/ten-radios-sort.md
pnpm-lock.yaml
sites/geohub/package.json

chore: upgrade maptiler geocoder to v2

---

.changeset/polite-carrots-hug.md
pnpm-lock.yaml
sites/geohub/package.json

now latest carbon svelte works after migrating to svelte 5

chore: upgrade carbon/charts-svelte

---

sites/static-image-api/Dockerfile
sites/static-image-api/Makefile

I realized `--platform=linux/amd64` is not necessary in Dockefile

fix: removed platform from static api Dockerfile

---

.changeset/chilly-adults-kneel.md
.changeset/strong-tables-film.md
packages/svelte-undp-components/src/lib/components/pg_tileserv/VectorSimulation.svelte
sites/geohub/src/components/pages/data/datasets/DatasetMapView.svelte

fix: fixed bug of showing console error in datasetmap view

---

sites/static-image-api/src/routes/(app)/+page.svelte

fix: hide Help component in static api landing page.

---

backends/k8s/cogserver/yaml/cogserver-deployment.yaml

switch zerossl to letsencrypt for titiler
https://letsdebug.net/titiler.undpgeohub.org/2355483

fix: changed issuer to letsecript from zerossl for titiler

---

.changeset/hot-pants-appear.md
sites/geohub/src/routes/(map)/dashboards/electricity/+page.ts
sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/constansts.ts

I am updating the Electricity dashboard forecast data to use the new v3 data
Should close #4712 

refactor: change electricity forecast to v3 data

---

.changeset/heavy-swans-begin.md
sites/geohub/src/components/pages/map/Map.svelte
sites/geohub/src/components/pages/storymap/MapLocationSelector.svelte
sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte

there was an issue of importing maptiler geocoder in SSR mode. Importing it in browser mode only now.

fix: fixed bug of importing maptiler geocoder in SSR.

---

.github/workflows/release.yml

ci: add permission for release.yaml

---

.github/workflows/release.yml

I think with is not needed. I want to just try if CI works correctly without it

ci: delete with from changeset release action

---

.github/workflows/release.yml

Reverts UNDP-Data/geohub#4807
this is needed

Revert "ci: delete with from changeset release action"

---

.changeset/strong-rice-sort.md
sites/geohub/src/routes/(app)/dashboards/ceei/components/LayerControl.svelte
sites/geohub/src/routes/(app)/dashboards/ceei/stores/index.ts
sites/geohub/src/routes/(app)/dashboards/ceei/utils/layerHelper.ts

fix: fixed bug of error of duplicate layer in CEEI dashboard.

---

.changeset/rare-cobras-rest.md
sites/geohub/src/components/pages/map/data/RasterAlgorithmExplorer.svelte
sites/geohub/src/routes/(app)/tools/+page.svelte

Since titiler was upgrade to 0.21.1 in this [PR](https://github.com/UNDP-Data/geo-cogserver/pull/111), new slope algorithm and several operation algorithms (cast, floor, ceil) were also added to geohub to give suitable tag in algorithm explorer component.

fix: add slode terrain algorithm and operation algorithm to algo explorer component

---

.changeset/perfect-rats-reply.md
sites/geohub/src/hooks.server.ts

this can solve sveltekiterror in server side

fix: fixed hooks.server.ts to avoid sveltekit error for .svelte URL in handleCORS

---

.changeset/early-pens-drum.md
packages/svelte-undp-design/src/lib/Footer/Footer.svelte

fix: removed unnecessary aria-hidden from footer to avoid Blocked aria-hidden error

---

.changeset/fifty-waves-occur.md
.changeset/stale-insects-fry.md
sites/geohub/src/lib/server/api/datasets/GET.ts
sites/geohub/src/lib/server/api/storymaps/GET.ts
sites/geohub/src/lib/server/api/tags/GET.ts
sites/geohub/src/routes/(app)/tools/+page.server.ts
sites/geohub/src/routes/(app)/tools/+page.svelte

fix: fixed /tags api to accepet any string value for tag query param.

---

.changeset/ten-pillows-sparkle.md
packages/svelte-undp-components/package.json
packages/svelte-undp-components/src/lib/components/ui/ImageUploader.stories.svelte
packages/svelte-undp-components/src/lib/components/ui/ImageUploader.svelte
packages/svelte-undp-components/src/lib/components/ui/index.ts
pnpm-lock.yaml
sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte
sites/geohub/src/routes/(app)/settings/+page.svelte

refactor: moved image uploader to component pacakage

---

.changeset/great-pumas-attack.md
.changeset/stupid-teachers-thank.md
packages/svelte-maplibre-storymap/src/lib/MaplibreLegendControl.svelte
packages/svelte-undp-components/src/lib/components/ui/Accordion.svelte
packages/svelte-undp-components/src/lib/components/ui/FloatingPanel.svelte
packages/svelte-undp-components/src/lib/util/clean.ts
sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
sites/geohub/src/lib/server/api/datasets/[id]/table/layers/[layer].[format]/GET.ts

fix: handle layer name correctly if it contains dot (.) in title

---

package.json

chore: approve esbuild to build

---

.changeset/sour-melons-exercise.md
pnpm-lock.yaml
sites/geohub/package.json
sites/geohub/src/components/pages/map/layers/StyleSaveDialog.svelte
sites/geohub/src/routes/(app)/maps/[[id]]/edit/+page.svelte
sites/geohub/src/routes/(app)/maps/[id]/+page.svelte

feat: add measure control to map editor

---

.changeset/silver-toys-flash.md
pnpm-lock.yaml
sites/geohub/src/routes/(app)/maps/[[id]]/edit/+page.svelte
sites/geohub/src/routes/(app)/maps/[id]/+page.svelte

[Please describe what you changed briefly.](fix: added select mode and delete-selection mode to allow users to delete only selected feature.)

fix: added select mode and delete-selection mode to allow users to delete only selected feature.

---

.changeset/fair-shirts-jog.md
sites/geohub/src/routes/(app)/maps/[[id]]/edit/+page.svelte
sites/geohub/src/routes/(app)/maps/[id]/+page.svelte

fix: added tourguide for terrain control and globe control

---

.changeset/soft-garlics-pay.md
sites/geohub/src/components/pages/map/data/DataCard.svelte
sites/geohub/src/components/pages/map/data/RasterAlgorithmExplorer.svelte
sites/geohub/src/lib/server/SvgLegendCreator.ts
sites/geohub/src/routes/(app)/data/[id]/+page.svelte
sites/geohub/src/routes/(app)/tools/+page.svelte

- feat: support statistics algorithms(min, max, median, mean, std, var) of titiler.
- show statistics algorithms as `statistics` tag in tools page and algorithm selector
- add algorithm name to dataset name when it is added to map.
- fix: fixed bug of legend endpoint if min/max is null

feat: support statistics algorithms(min, max, median, mean, std, var) of titiler.

---

docker/README.md

docs: updated README.md for docker folder

---

.changeset/chatty-peaches-draw.md
.changeset/famous-toys-wear.md
.changeset/pretty-games-push.md
.changeset/proud-moles-lick.md
packages/svelte-undp-components/src/lib/components/titiler/RasterClassifyLegend.svelte
packages/svelte-undp-components/src/lib/interfaces/RasterTileMetadata.ts
sites/geohub/src/lib/server/defaultStyle/RasterDefaultStyle.ts
sites/geohub/src/routes/(app)/data/[id]/style/edit/+page.svelte

fix: apply colormap if it is available in raster data metadata itself

---

.changeset/better-heads-clap.md
sites/geohub/src/lib/config/AppConfig/attribution.ts

refactor: update disclaimer

---

sites/geohub/src/lib/config/AppConfig/attribution.ts

fix: remove undp from attribution

---

sites/geohub/src/components/pages/map/MapHero.svelte

Added a small margin to show attribution text in map hero

fix: hidden attribution text in map hero

---

.changeset/solid-carpets-unite.md
sites/geohub/src/components/pages/map/plugins/TourControl.svelte

fix: fixed bug caused by intro.js upgrading when intro.js is loaded in SSR.

---

.changeset/rotten-mugs-share.md
pnpm-lock.yaml
sites/geohub/package.json

fixes #5127 
There was a bug in maplibre-gl-terradraw which was fixed by https://github.com/watergis/maplibre-gl-terradraw/pull/371

fix: upgraded the version of maplibre-gl-terradraw. the previous plugin's cleanStyle function accidentally deleted background layer from the style

---

.changeset/shy-heads-smell.md

- added a changeset for PR #5081 (I forgot to add it in PR, I am sorry)

fix: added a changeset file for storymap terrain PR#5081

---

.changeset/honest-fans-carry.md
sites/geohub/src/routes/(app)/dashboards/electricity/+page.server.ts
sites/geohub/src/routes/(app)/dashboards/electricity/+page@.svelte
sites/geohub/src/routes/(app)/dashboards/electricity/components/TimeSlider.svelte
sites/geohub/src/routes/(app)/dashboards/electricity/utils/adminLayer.ts

In this PR.
1. I updated admin datasets for the Electricity Dashboard and in the geohub updated the URL to point to the right datasets

fix: update electricity dashboard
