UNDP-Data/geohub

- .npmrc
> Revert "fix:add  hoisting for .npmrc"

- src/routes/azstorage.json/+server.ts
> fixed issue#674. Put children property correctly if it is static vector tiles

- documentation/mkdocs.yml
> updated mkdocs yaml

- src/components/BucketView.svelte
- src/components/LayerList.svelte
- src/components/TagsView.svelte
- src/components/UNDPComponents/Content_UNDP.svelte
- disabled scroll in Content.svelte
- now scroll of bucket list and bucket tree view are separated
- also added scroll in tag tab and layer tab
- Changed progress bar location to be able to show all the time when scrolled
> improved scroll in drawer content

- lefthook.yml
- src/routes/stac/+server.ts
- src/routes/stac/mosaicjson/+server.ts
- added error handling in mosaicjson api
- removed resampling method from tilejson URL
> added error handling and removed resampling in tilejson url

- src/components/BucketTreeItemRaster.svelte
- src/routes/stac/mosaicjson/+server.ts
- src/routes/stac/tilejson/+server.ts
there is `strict-origin-when-cross-origin` in `/mosaicjson/tiles` api when maplibre accesses on dev server, I tried to create new endpoint to wrap fetching mosaicjson inside our api directly from blob.
> created new endpoint to wrap azure blob endpoint

- documentation/Pipfile
- documentation/Pipfile.lock
- documentation/mkdocs.yml
references
- https://pypi.org/project/mkdocs-video/
> added mkdocs-video plugin

- src/components/BucketTreeItemRaster.svelte
- src/components/ColorMapPicker.svelte
- src/components/RasterLayer.svelte
- src/components/RasterMosaicLegendContainer.svelte
- src/routes/stac/mosaicjson/+server.ts
currently, there is 404 error if the second mosaicjson layer is added. But most of layers can be added if it is the first mosaic layer in geohub.
> change colormap for mosaic

- src/components/BucketTreeBranch.svelte
- src/components/BucketTreeItemRaster.svelte
- src/components/RasterHistogram.svelte
- src/components/UniqueValuesLegend.svelte
- src/routes/stac/+server.ts
- src/routes/stac/mosaicjson/+server.ts
- fixed a bug of unique value legend for mosaic
- fixed some error handling for some collections (eg, no items in search result)
> fixed uniquevalue legend for mosaic

- src/components/BucketTreeItemCardButton.svelte
> changed placement from right to right-start

- src/components/BucketTreeBranchIcon.svelte
- src/components/BucketTreeItemIcon.svelte
> change a link to div for add layer icon

- src/components/BucketTreeItemCardButton.svelte
- src/components/BucketTreeItemVector.svelte
- src/components/controls/AddLayerModal.svelte
- src/lib/helper/getLayerNumberProperties.ts
- src/routes/martin/+server.ts
- src/routes/martin/[table]/tile.json/+server.ts
- created `/martin/[table]/tile.json` API to generate tilejson v3.0.0 for martin
> created /martin/[table]/tile.json to share the same source code with pgtileserv in frontend

- src/components/BucketView.svelte
- src/components/StyleShare.svelte
> Fix/issue 752: disable bucket card button when share dialog is shown

- src/lib/components/StyleSwitcher.svelte
> fixed issue of rounded map

- src/components/BucketTreeItemVector.svelte
- src/components/Map.svelte
- src/components/MapQueryInfoPanel.svelte
- src/lib/types/Layer.ts
maybe fixed #760 (I cannot reproduce this bug although I have tried sveral times)
- refactored QueryInfoPanel
- Deleted `Layer.features` variable
> refactored mapqueryinfopanel

- src/components/controls/VectorSymbolAdvanced.svelte
- src/components/controls/vector-styles/IconSize.svelte
- src/lib/types/Layer.ts
- deleted iconSize variable from Layer type
- now it always looks value of map.getStyle object
> deleted iconSize variable from Layer type

- package.json
- pnpm-lock.yaml
- src/components/BannerMessageControl.svelte
- src/components/BucketView.svelte
- src/components/Content.svelte
- src/components/ContentSidebar.svelte
- src/components/Map.svelte
- removed smui for banner message
- changed SMUI banner to `svelte-splitter`
> improved banner message

- src/components/BucketTreeItemRaster.svelte
- src/components/BucketTreeItemVector.svelte
- set minzoom and maxzoom of tile source and layer style by using metadata information
- zoom to a layer after adding into the map
> set min-maxzoom for layer source, also zoom to layer after adding

- src/components/BucketTreeItemVector.svelte
This reverts commit 24cc787a8a91ec4c861b9a9b62d7d5892fbbbdb4.
> Revert "fixed calling metadata.json api (#800)"

- src/components/BucketFilter.svelte
- src/components/BucketTreeItemIcon.svelte
- src/components/BucketView.svelte
fixed #816 and #815
new bucket filter window will be shown next to the filter button. also changed the location of clear input button inside textbox.
> changed location of bucket filter window and clear button location

- src/components/DataView.svelte
- src/components/controls/TextFilter.svelte
> disable clear query button when text is empty

- src/components/DataView.svelte
- src/components/LayerList.svelte
- src/components/controls/Notification.svelte
> set limit as 25. show notification message when all data is loaded

- src/components/DataView.svelte
- src/components/controls/TextFilter.svelte
> adjusted margin for breadcrumb

- src/routes/datasets/+server.ts
partially fixed #870 in backend side
> added AND search for tag

- src/lib/VectorTileData.ts
fixed issues due to this change on geohub-cli
https://github.com/UNDP-Data/geohub-cli/commit/d975fb039367ac2d24763352bfc5ead3bd224119
> fixed to use layer id from tags instead of name

- src/components/Content.svelte
- src/components/ContentSidebar.svelte
- src/components/DataView.svelte
- src/components/Header.svelte
- src/components/LayerList.svelte
- src/components/Map.svelte
- src/components/StyleShare.svelte
- src/components/controls/Breadcrumbs.svelte
- src/components/controls/Tabs.svelte
- src/components/controls/TextFilter.svelte
- src/routes/+page.svelte
I could not manage to set map height automatically at Map.svelte, but in other components now get header height dynamically
> removed hard coding to set header height

- package.json
- pnpm-lock.yaml
> reverted sveltekit to 564

- src/components/controls/ColorMapPicker.svelte
- src/components/controls/RasterLegendContainer.svelte
- src/components/controls/Tabs.svelte
- src/components/controls/VectorLineContainer.svelte
- src/components/controls/VectorPolygonContainer.svelte
- src/components/controls/VectorSymbolContainer.svelte
- src/lib/types/Tab.ts
> fixed tabs in colorMapPicker.svelte

- src/components/DataCard.svelte
- src/components/StyleShare.svelte
- src/lib/types/Layer.ts
> exclude microsoft stac layer for style sharing feature

- .npmrc
set link-workspace-packages to `deep`
https://pnpm.io/npmrc#link-workspace-packages
> set link-workspace-packages as deep

- sites/geohub/src/components/DataView.svelte
- sites/geohub/src/components/data-view/SelectedTags.svelte
> reset tag list when tag is deleted

- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/components/BannerMessageControl.svelte
- sites/geohub/src/components/MapQueryInfoPanel.svelte
- sites/geohub/src/components/controls/ActionsDropdown.svelte
- sites/geohub/src/components/controls/ColorMapPicker.svelte
- sites/geohub/src/components/controls/ColorPicker.svelte
- sites/geohub/src/components/controls/DeleteButton.svelte
- sites/geohub/src/components/controls/LayerOrderButtons.svelte
- sites/geohub/src/components/controls/Notification.svelte
- sites/geohub/src/components/controls/NumberInput.svelte
- sites/geohub/src/components/controls/RasterExpressionBuilder.svelte
- sites/geohub/src/components/controls/RasterExpressionSimple.svelte
- sites/geohub/src/components/controls/RasterLegendContainer.svelte
- sites/geohub/src/components/controls/VectorLineContainer.svelte
- sites/geohub/src/components/controls/VectorPolygonContainer.svelte
- sites/geohub/src/components/controls/VectorSymbolContainer.svelte
- sites/geohub/src/components/controls/VisibilityButton.svelte
- sites/geohub/src/components/controls/vector-styles/IconImagePicker.svelte
- sites/geohub/src/components/controls/vector-styles/IconImagePickerCard.svelte
- sites/geohub/src/dashboards/components/DashboardHeader.svelte
- sites/geohub/src/dashboards/components/DashboardMapStyleCard.svelte
- sites/geohub/src/dashboards/components/TimeSlider.svelte
- sites/geohub/src/lib/types/OperatorCategory.ts
- sites/geohub/src/routes/dashboards/+page.svelte
> deleted svelte-fa

- sites/geohub/src/routes/api/stac/mosaicjson/+server.ts
> fix: se new Date().getTime() instead of uuid for mosaicjson api

- sites/geohub/src/app.html
> refactor: removed google font css import

- sites/geohub/src/components/controls/vector-styles/HeatmapColorRow.svelte
- sites/geohub/src/components/controls/vector-styles/IconImage.svelte
- sites/geohub/src/components/controls/vector-styles/MaplibreColorPicker.svelte
> fix: fixed bug of icon image picker. and also fixed some position of color picker

- sites/geohub/src/components/data-view/SelectedTags.svelte
> added tag clear button

- sites/geohub/src/components/controls/VectorLabelPanel.svelte
> fixed to restore vector label from previous style

- sites/geohub/src/components/controls/OpacityPanel.svelte
> initialise opacity from style.json

- sites/geohub/src/components/Header.svelte
> fixed dashboard tooltip name

- sites/geohub/src/components/ContentSidebar.svelte
> Increased the size of the sidebar for the tabs to fit

- sites/geohub/src/components/controls/VectorFilterPanelWizard.svelte
> fix: restore vector filter expression to wizard

- sites/geohub/src/components/MapQueryInfoPanel.svelte
> Fix map query info to display the right information for each visible layer

- sites/geohub/src/components/controls/RasterLegendContainer.svelte
fixes #1028
It will initialise either continous or interval or unique legend from existing style.json. I added some logic of unique value legend, but I have not confirmed by the actual data
> fixed a bug of initialising raster legend from existing sytle.json

- sites/geohub/src/components/controls/RasterLegendContainer.svelte
> fixed bugs of restoring unique value legend in raster layer

- sites/geohub/src/components/StyleShare.svelte
> removed untargetd layers (like STAC) from saved

- sites/geohub/src/components/DataView.svelte
- sites/geohub/src/components/data-view/DataCard.svelte
- sites/geohub/src/components/data-view/DataStacAssetCard.svelte
- sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
- sites/geohub/src/lib/dashboards/MapStyleCardList.svelte
If an accordion is expanded,
- close other accordions for assets list of Microsoft STAC collection
- close other accordions for style list in dashboard
for now, we just keep other accordions open in dataset level in data tab.
> automatically close other accordions if an accordion is expanded

- sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
> added a button to open style map when accordion is closed in dashboard

- sites/geohub/src/components/LayerOrder.svelte
- sites/geohub/src/components/controls/DeleteButton.svelte
- sites/geohub/src/components/controls/VectorLabelPanel.svelte
- sites/geohub/src/components/controls/vector-styles/TextField.svelte
- sites/geohub/src/lib/helper/getLayerProperties.ts
- sites/geohub/src/lib/helper/getPropertyValueFromExpression.ts
> fix: only create label child layer when the annotation is configured

- sites/geohub/src/components/data-view/DataCard.svelte
> fix: reset asset list when accordion is opened again

- sites/geohub/src/components/MapQueryInfoControl.svelte
> use individual variable for showing progress bar in popup rather than using variable in stores

- sites/geohub/src/components/controls/RasterIntervalsLegend.svelte
- sites/geohub/src/components/controls/VectorPolygonAdvanced.svelte
> fix: removed key reactivity for interval legend, so it will work well if color is changed

- sites/geohub/src/components/control-groups/LayerNameGroup.svelte
- sites/geohub/src/components/controls/RasterBandSelector.svelte
- Use RasterBandSelector in layerName component
- show bulma tag if band is only one
- show selectbox if has multiple bands
- removed `mosaic` tag if it is mosaicjson layer. don't show band tag anymore for mosaicjson
> refactor: use raster band selector in layerName

- sites/geohub/src/components/MapQueryInfoControl.svelte
> fixed to query only visible layers

- sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
> Change button size in `DashboardMapStyleCard`

- sites/geohub/src/components/controls/VectorFilterPanelWizard.svelte
- sites/geohub/src/components/controls/vector-styles/ValueInput.svelte
fixes #1033
in order to solve this issue, this change will create a temporally symbol layer for heatmap
> fixed bug of selecting feature on heatmap filter

- sites/geohub/src/components/RasterLayer.svelte
- sites/geohub/src/components/VectorLayer.svelte
- sites/geohub/src/components/control-groups/LayerNameGroup.svelte
- sites/geohub/src/components/controls/vector-styles/HeatmapColor.svelte
- sites/geohub/src/components/controls/vector-styles/IconImage.svelte
- sites/geohub/src/components/controls/vector-styles/Legend.svelte
- sites/geohub/src/lib/constants.ts
fixes #1068
- Symbol
- Symbol with interval legend
- Line
- Line with interval legend
- Polygon
- Polygon with interval legend
- heatmap
- raster
- raster with interval legend
- raster with unique legend
> add legend next to layer name

- .changeset/config.json
- sites/geohub/package.json
references
- https://github.com/changesets/changesets/blob/main/docs/config-file-options.md#ignore-array-of-packages
- https://github.com/changesets/changesets/blob/main/docs/problems-publishing-in-monorepos.md
> set privete=true for geohub's package.json

- apps/electricity-dashboard/src/lib/components/Map.svelte
> fixed initialising map size in electricity dashboard

- sites/geohub/src/components/controls/RasterIntervalsLegend.svelte
- sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
- sites/geohub/src/lib/helper/updateIntervalValues.ts
> vector legend interval control invalid inputs

- .changeset/cyan-pens-lie.md
- packages/geohub-cli/src/cli/azblob.ts
- packages/geohub-cli/src/util/BlobServiceAccountManager.ts
- packages/geohub-cli/src/util/DatabaseManager.ts
- packages/geohub-cli/src/util/Datasets.ts
- fixed bug of upsert SQL for dataset table
- dataset will be removed from database if specified URL of blob does not exists.
> fixed bug of upsert SQL for dataset table and added deleting feature for azblob CLI

- sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
- sites/geohub/src/lib/constants.ts
- sites/geohub/src/lib/server/helpers/fetchVectorInfo.ts
- sites/geohub/src/lib/server/helpers/getStaticPbfMetadataJson.ts
> fixed bug of computing stats for pmtiles

- sites/geohub/src/components/controls/VectorFilterPanelWizard.svelte
- sites/geohub/src/components/controls/vector-styles/PropertySelectButtons.svelte
- sites/geohub/src/components/controls/vector-styles/TextField.svelte
- sites/geohub/src/components/controls/vector-styles/ValueInput.svelte
> fixed bug of vector filter to hard code to use first layer

- .changeset/polite-pumas-study.md
- packages/style-viewer/package.json
- packages/style-viewer/src/lib/StyleViewer.svelte
- pnpm-lock.yaml
> add pmtiles support for style-viewer

- sites/geohub/src/components/data-view/DataCard.svelte
- sites/geohub/src/components/data-view/DataVectorCard.svelte
- sites/geohub/src/components/data-view/MiniMap.svelte
- sites/geohub/src/lib/RasterTileData.ts
- sites/geohub/src/lib/VectorTileData.ts
preload metadata on data tab, and reuse them when layer is added to minimap or geohub map
> preload metadata when search in data tab

- sites/geohub/src/service-worker.ts
trying to add default service worker since sometimes there are many error pointing at service-worker
> add service worker

- .changeset/twelve-snakes-hammer.md
- packages/svelte-undp-design/package.json
- packages/svelte-undp-design/src/lib/Download/Download.stories.ts
- packages/svelte-undp-design/src/lib/Download/Download.svelte
- packages/svelte-undp-design/src/lib/css/download-card.min.css
- packages/svelte-undp-design/src/lib/index.ts
- pnpm-lock.yaml
- sites/geohub/src/components/controls/DataCardInfoButton.svelte
- sites/geohub/src/components/data-view/DataCardInfo.svelte
fixes #1160
- added Download component for svelte-undp-design
- added Download button in DataCardInfo.svelte
- fixed width of popup of DataCardInfo component
> feat: add download button in DataCardInfo.svelte

- README.md
> Add sequence diagram on README.md

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/new_feature_request.yml
- CONTRIBUTING.md
Fixes #1166
- Created contribution guidelines
- Added issue templates fr bug reports and feature requests
> docs: create contributing guidelines

- sites/geohub/src/components/VectorLayer.svelte
- sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
> fix: fixed bug of resetting colormap when visibility button is clicked.

- sites/geohub/src/components/RasterLayer.svelte
- sites/geohub/src/components/controls/RasterLegendContainer.svelte
> refactor: Use LegendTypeSwitcher in Raster component

- sites/geohub/src/components/controls/ColorMapPicker.svelte
- sites/geohub/src/components/controls/RasterContinuousLegend.svelte
- sites/geohub/src/components/controls/RasterIntervalsLegend.svelte
- sites/geohub/src/components/controls/RasterLegendContainer.svelte
- sites/geohub/src/components/controls/RasterUniqueValuesLegend.svelte
- sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
fixes #1177 
- refactored ColorMapPicker to simplify it
- moved the location of ColorMapPicker from RasterLegendContainer to each Raster Legend component
- Updated code in VectorAdvancedLegend for refactored ColorMapPicker.
> refactor: refactored and moved colormappicker to each raster legend components (#1177)

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- added PR template
- updated issue template
- updated readme to mention contributing.md
> doc: added PR template

- sites/geohub/src/routes/dashboards/+page.svelte
Added all relevant links of GeoHub in footer of dashboard page
> feat: added relevant links in footer

- .github/workflows/main_undpgeohub.yml
- .github/workflows/release.yml
- pnpm-lock.yaml
- sites/geohub/.env.example
- sites/geohub/package.json
- sites/geohub/src/components/Header.svelte
- sites/geohub/src/components/UserAccount.svelte
- sites/geohub/src/components/controls/Notification.svelte
- sites/geohub/src/hooks.server.ts
- sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
- sites/geohub/src/routes/+error.svelte
- sites/geohub/src/routes/+layout.server.ts
- sites/geohub/src/routes/api/datasets/+server.ts
- sites/geohub/src/routes/api/style/+server.ts
- sites/geohub/src/routes/api/style/[id].json/+server.ts
- sites/geohub/src/routes/api/style/[id]/+server.ts
- sites/geohub/src/routes/api/style/count/+server.ts
- sites/geohub/src/routes/api/tags/+server.ts
- sites/geohub/src/routes/api/vector/[source]/metadata.json/+server.ts
- sites/geohub/src/routes/api/vector/[source]/tile.json/+server.ts
- sites/geohub/src/routes/api/vector/statistics/+server.ts
- sites/geohub/src/routes/dashboards/+page.svelte
closes #958 
I added SSO feature with Azure Active Directory to enable sign in by UNDP account.
The following references are useful to develop SSO in sveltekit.
- Auth.js for sveltekit
- https://authjs.dev/reference/sveltekit/modules/main
- Azure AD provider
- https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/azure-ad.ts
- auth.js x sveltekit example code
- https://github.com/nextauthjs/next-auth/tree/main/apps/examples/sveltekit
Currently, this PR is still not able to be merged because apps for dev.undpgeohub.org is not yet registered to Azure AD.
> feat: added signin & singout with Azure AD

- .github/workflows/main_undpgeohub.yml
- sites/geohub/src/hooks.server.ts
trying to fix the following server error.
```
2023-01-20T20:25:41.646444114Z [31m[auth][error][UntrustedHost][0m: Read more at [https://errors.authjs.dev#untrustedhost](https://errors.authjs.dev/#untrustedhost)
2023-01-20T20:25:43.006388122Z UntrustedHost: Host must be trusted. URL was: https://dev.undpgeohub.org/api/auth/session
2023-01-20T20:25:43.006437024Z     at assertConfig (file:///home/site/wwwroot/node_modules/@auth/core/lib/assert.js:22:16)
2023-01-20T20:25:43.006443324Z     at Auth (file:///home/site/wwwroot/node_modules/@auth/core/index.js:65:29)
2023-01-20T20:25:43.006448024Z     at async getSession (file:///home/site/wwwroot/server/chunks/hooks.server-b1dda119.js:15:20)
2023-01-20T20:25:43.006452325Z     at async load …
```
> added trustHost in hooks.server.ts

- sites/geohub/src/hooks.server.ts
Added `secret` in hooks.server.ts
```
2023-01-20T21:30:41.743370449Z MissingSecret: Please define a `secret`.
2023-01-20T21:30:41.743462454Z     at assertConfig (file:///home/site/wwwroot/node_modules/@auth/core/lib/assert.js:25:16)
2023-01-20T21:30:41.743482356Z     at Auth (file:///home/site/wwwroot/node_modules/@auth/core/index.js:65:29)
2023-01-20T21:30:41.743496456Z     at async getSession (file:///home/site/wwwroot/server/chunks/hooks.server-e7123ba9.js:15:20)
2023-01-20T21:30:41.743509657Z     at async load (file:///home/site/wwwroot/server/chunks/0-8cf311d0.js:3:14)
2023-01-20T21:30:41.743523358Z     at async load_server_data (file:///home/site/wwwroot/server/chunks/index-ed4cfff2.js:1086:18)
2023-01-20T21:30:41.743536259Z     at async …
```
> added AUTH_SECRET in hooks.server.ts

- sites/geohub/src/routes/+page.ts
I deleted `prerender = true` and added `csr = true` instead.
It works in my localhost for both `pnpm dev` and `pnpm preview`
https://kit.svelte.dev/docs/page-options#csr
> fix: add csr=true in +page.ts and removed prerender settings

- .changeset/cool-crabs-ring.md
- packages/svelte-undp-design/src/lib/Header/Header.stories.ts
- packages/svelte-undp-design/src/lib/Header/Header.svelte
- packages/svelte-undp-design/src/lib/css/mega-menu.min.css
- packages/svelte-undp-design/src/lib/css/menu.min.css
- packages/svelte-undp-design/src/lib/css/mobile-nav.min.css
- packages/svelte-undp-design/src/lib/interfaces/HeaderLink.ts
- packages/svelte-undp-design/src/lib/interfaces/index.ts
- sites/geohub/src/components/Header.svelte
- sites/geohub/src/components/StyleShare.svelte
- sites/geohub/src/routes/+error.svelte
- sites/geohub/src/routes/dashboards/+page.svelte
- sites/geohub/src/routes/dashboards/+page.ts
redesigning svelte [undp header](https://design.undp.org/?path=/story/components-navigation-components-main-navigation-country-header--country-header) component. Now responsive menu design is available. and a slot for custom icon (it is used for SSO user account button)
- Full screen
- narrower width
- narrower width and menu
- smartphone
- dashboard
> refactor: redesigning header

- sites/geohub/src/components/UserAccount.svelte
- sites/geohub/src/hooks.server.ts
- sites/geohub/src/routes/+layout.server.ts
> feat: fetch login user info and add jobTitle to user card

- sites/geohub/src/components/MapQueryInfoControl.svelte
changed map query tool icon to avoid using the same icon with maplibre attribution control
> feat: changed map query tool's icon since it was the same with attribution icon

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/refactoring.yml
> doc: added refactoring template

- .changeset/blue-deers-attend.md
- packages/svelte-undp-design/src/lib/css/country-site-header.min.css
Fixes #1225 
I am not sure whether this change is allowed to do in UNDP.
> fix: #1225 header logo height

- sites/geohub/src/app.html
- sites/geohub/src/components/MainApp.svelte
- sites/geohub/src/components/Map.svelte
- sites/geohub/src/components/MapQueryInfoControl.svelte
- sites/geohub/src/routes/+page.svelte
- sites/geohub/src/routes/dashboards/+page.svelte
- sites/geohub/src/routes/dashboards/electricity/+page.svelte
> fix: map height and dashboard page height in smartphone

- .changeset/angry-readers-cross.md
- apps/electricity-dashboard/src/lib/components/Content.svelte
- apps/electricity-dashboard/src/routes/+page.svelte
- sites/geohub/src/components/Content.svelte
- sites/geohub/src/components/DataView.svelte
- sites/geohub/src/components/LayerList.svelte
- sites/geohub/src/components/MainApp.svelte
> fix: 1207 set splitter height in main geohub, and fix height of electricity dashboard content

- .github/workflows/main_undpgeohub.yml
Set environmental variables for SSO in production on CI.
The following variables were also registered in AppService
- AUTH_SECRET
- AZURE_AD_CLIENT_ID
- AZURE_AD_CLIENT_SECRET
- AZURE_AD_TENANT_ID
> updated CI for production. set env in CI

- sites/geohub/src/components/AccessLevelSwitcher.svelte
- sites/geohub/src/components/RasterLayer.svelte
- sites/geohub/src/components/StyleShare.svelte
- sites/geohub/src/components/VectorLayer.svelte
- sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
- sites/geohub/src/routes/dashboards/+page.svelte
few bug fixes on dashboard, and new features for saved maps
> fix: improve dashboard map

- sites/geohub/src/lib/helper/updateParamsInURL.ts
fixes #1259
I found a new way to update source URL in stackoverflow
https://stackoverflow.com/questions/38631344/recommended-way-to-switch-tile-urls-in-mapbox-gl-js
> fix: bug of weird maplibre error by using new way to upload source URL

- sites/geohub/src/components/controls/VectorClassifyLegend.svelte
fixes #1269 
I could not manage to sort string values in unique value legend, but now at least colormap rows and layer legend style are syncronised.
> fix: when selected property is number field, sort stops

- sites/geohub/src/components/controls/VectorClassifyLegend.svelte
> fix: keep random sample values same in order to compute same results for natural breaks and quantile

- sites/geohub/src/components/__tests__/IconImagePickerCard.test.ts
- sites/geohub/src/components/controls/VectorClassifyLegend.svelte
- sites/geohub/src/components/controls/VectorLine.svelte
- sites/geohub/src/components/controls/VectorSymbol.svelte
- sites/geohub/src/components/controls/vector-styles/IconImage.svelte
- sites/geohub/src/components/controls/vector-styles/IconImagePicker.svelte
- sites/geohub/src/components/controls/vector-styles/IconImagePickerCard.svelte
- sites/geohub/src/components/controls/vector-styles/IconOverlap.svelte
- sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
- sites/geohub/src/components/controls/vector-styles/LineWidth.svelte
> feat: redesign line symbol legend

- sites/geohub/src/components/controls/VectorLabelPanel.svelte
- sites/geohub/src/components/controls/VectorLine.svelte
- sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
fixes #1276 
also, found vector line layout become collapsed in responsive. I fixed it.
> fixed layout vector label and vector line in responsive

- sites/geohub/src/components/controls/VectorLine.svelte
> fix: removed padding from vector line to adjust layout

- sites/geohub/src/components/Content.svelte
- sites/geohub/src/components/Header.svelte
- sites/geohub/src/routes/+page.svelte
fixes #1277
also set map name in head title
> enabled data tab in readonly mode, and set saved map name in head title

- sites/geohub/src/components/controls/vector-styles/PropertySelect.svelte
> capitalise and clean property text

- sites/geohub/src/components/data-view/DataCard.svelte
- sites/geohub/src/components/data-view/DataStacAssetCard.svelte
- sites/geohub/src/components/data-view/DataVectorCard.svelte
- sites/geohub/src/lib/helper/loadMap.ts
the progressindicator store is used to control the status pf the indefinite progress bar. While it was used in GeoHub it was not explicitly tied to map loading. This PR add sets the indicator whenever the map is loading
> Progress indicator

- sites/geohub/src/components/MainApp.svelte
> fix: revert minPrimaryWidth to 360px

- sites/geohub/src/app.html
- sites/geohub/src/components/Header.svelte
- sites/geohub/src/routes/+page.svelte
- sites/geohub/src/routes/dashboards/+page.svelte
- sites/geohub/src/routes/dashboards/electricity/+page.svelte
- sites/geohub/src/routes/maps/+page.svelte
Moved meta title and og:title and og:site_name to each +page.svelte from app.html. Hope it works
> fix: set metadata title for each page

- sites/geohub/src/components/Header.svelte
- sites/geohub/src/components/StyleShare.svelte
fixes #1278
In this PR, I just enabled saving feature for other user's map, and it is going to save as new map of login user.
For reloading preload funcitons, refer to https://kit.svelte.dev/docs/modules#$app-navigation-invalidate
> feat: fixes #1278 to enalbe save as new map

- sites/geohub/src/components/controls/VectorParamsPanel1.svelte
THIS PR changes the style pf the selected parameters for function layers. By default the parameters are blue, the selected parameters are green and feature a circular xmark icon which removes the parameter in question from the selected list of parameters.
> change icon and styles for selected  parameters

- sites/geohub/src/components/controls/RasterClassifyLegend.svelte
- sites/geohub/src/components/controls/RasterDefaultLegend.svelte
> fix: #1305 show colormap in raster unique

- sites/geohub/src/components/Header.svelte
- sites/geohub/src/components/MainApp.svelte
move the progress bar from header as to prevent the map to flicker or change height
> move progress bar from header to MainApp

- sites/geohub/src/components/DataView.svelte
- sites/geohub/src/components/data-view/TextFilter.svelte
- sites/geohub/src/lib/constants.ts
- sites/geohub/src/lib/types/DataOrderType.ts
- sites/geohub/src/lib/types/DataSortingColumn.ts
> feat: 1315 enhance sort

- sites/geohub/src/components/DataView.svelte
uncommented code to allow only an accordion to expand
> feat: uncommented code to allow only an accordion to expand

- sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
> fix: made line pattern width a bit narrower

- sites/geohub/src/components/data-view/DataCard.svelte
> fix: preload vector metadata to make add layer button work well

- sites/geohub/src/components/UserAccount.svelte
Improve style for UserAccount.svelte component
> Style improvements

- .changeset/fast-months-do.md
- packages/svelte-undp-design/src/lib/Loader/Loader.stories.ts
- packages/svelte-undp-design/src/lib/Loader/Loader.svelte
- sites/geohub/src/components/StyleShare.svelte
- sites/geohub/src/components/data-view/AddLayerButton.svelte
- sites/geohub/src/components/data-view/DataCard.svelte
- sites/geohub/src/components/data-view/DataStacAssetCard.svelte
- sites/geohub/src/components/data-view/DataVectorCard.svelte
> feat: add loaders in style share and add layer buttons to indicate loading process

- sites/geohub/src/components/data-view/DataVectorCard.svelte
- sites/geohub/src/lib/VectorTileData.ts
> feat: added layer type option for polygon layer

- sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
- sites/geohub/src/components/data-view/DataVectorCard.svelte
> fixed not to syncronise line pattern legend color with line color

- sites/geohub/src/routes/data/+page.ts
hope it can fix https://dev.undpgeohub.org/docs/index.html page error
> added +page.ts under /data route

- .github/workflows/main_undpgeohub.yml
> fix: not to move docs html to prerender folder in CI

- sites/geohub/src/components/controls/VectorLabelPanel.svelte
- sites/geohub/src/components/controls/vector-styles/TextField.svelte
- sites/geohub/src/lib/helper/getLayerProperties.ts
> fix: some properties of string type are not shown in label tab

- .github/workflows/deploy_storybook.yml
- .github/workflows/main_undpgeohub.yml
- sites/geohub/src/lib/constants.ts
- added CI to deploy storybook to Azure Blob container.
- added `AZURE_STORAGE_CONNECTION_STRING_UPLOAD` secret in Github repo
> feat: deploy storybook

- .github/workflows/docker-image.yml
- CONTRIBUTING.md
- Dockerfile
- docker-compose.yml
- package.json
- pnpm-lock.yaml
- fixed Dockerfile
- deleted `prepare` command for lefthook install. because changeset CI everytime takes time
> fixed Dockerfile to adpot latest code. removed prepare command for lefthook install

- Dockerfile
> fixed bug of Dockerfile entrypoint

- sites/geohub/src/routes/data/upload/+page.server.ts
fixed bug of env variable in data upload page
> fix: env variable in data upload

- sites/geohub/src/routes/data/+page.server.ts
- sites/geohub/src/routes/data/+page.svelte
- changed accordion to table in data page
- added same search setting components 
> feat: changed accordion to table in data page

- sites/geohub/src/app.d.ts
- sites/geohub/src/hooks.server.ts
I changed the position fetching job title to the same callback with setting token. 
> fix: fetching jobtitle in hooks

- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/routes/api/datasets/ingesting/+server.ts
- sites/geohub/src/routes/data/+page.svelte
- added cancel button in ingesting datasets table
> feat: cancel button for data uploading

- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- show error log in dialog after clicking button in error status
> feat: show error log in dialog for failed uploaded data

- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/lib/types/IngestingDataset.ts
- sites/geohub/src/routes/api/datasets/ingesting/+server.ts
forget to delete .ingesting file when cancel button is clicked
> fix: delete .ingesting file when user click cancel button

- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/components/data-view/DataVectorCard.svelte
- sites/geohub/src/lib/VectorTileData.ts
- sites/geohub/src/lib/server/helpers/generateAzureBlobSasToken.ts
- sites/geohub/src/routes/api/datasets/[id]/+server.ts
- sites/geohub/src/routes/data/+page.svelte
- sites/geohub/src/routes/data/publish/+page.server.ts
fixes #1436
- delete .ingesting file after publishing new data from ingesting datasets table
- create `.ingesting` file again if the dataset is deleted from PostGIS database. so it will be appeared ingesting datasets table again.
- fixed a bug of getting metadata of pmtiles.
> fix: publish delete ingesting file

- sites/geohub/src/components/data-upload/DataUploadButton.svelte
- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/routes/data/+layout.svelte
- sites/geohub/src/routes/data/+page.svelte
> refactor: data upload

- sites/geohub/src/components/data-view/DataCardInfo.svelte
> fix: added license info in DataCardInfo

- .changeset/kind-cats-compete.md
- packages/svelte-undp-design/.storybook/preview-head.html
- packages/svelte-undp-design/src/lib/Radios/Radios.svelte
- sites/geohub/src/components/AccessLevelSwitcher.svelte
- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/components/maps/MapStyleCardList.svelte
- sites/geohub/src/routes/data/+page.server.ts
- sites/geohub/src/routes/maps/+page.server.ts
> fix: bug of resetting offset to 0 when the reload browser in /maps and /data page

- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
closes #1449
added download button in ingesting dataset table
> feat: added download button in ingesting datasets table

- .changeset/quick-mice-reflect.md
- packages/svelte-undp-design/src/lib/Radios/Radios.svelte
- sites/geohub/src/components/data-upload/DataPreview.svelte
- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/components/data-view/MiniMap.svelte
- sites/geohub/src/lib/types/DatasetFeature.ts
- sites/geohub/src/lib/types/IngestingDataset.ts
- sites/geohub/src/routes/api/datasets/ingesting/+server.ts
- sites/geohub/src/routes/data/publish/+page.server.ts
- sites/geohub/src/routes/data/publish/+page.svelte
fixes #1450
- added preview button in ingesting datasets table
- added preview after expanding accordion in published datasets table
- added preview button in publish page
- fixed bug of UNDP radio button
> feat: add preview in /data page and /data/publish

- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
> feat: add confirmation of deleting dataset by typing name

- sites/geohub/src/components/controls/PanelButton.svelte
- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/components/data-view/AddLayerButton.svelte
- sites/geohub/src/components/data-view/TagFilter.svelte
- sites/geohub/src/components/data-view/TextFilter.svelte
- sites/geohub/src/lib/constants.ts
- sites/geohub/src/routes/api/stac/mosaicjson/+server.ts
- fixed bug of mosaicjson
- improved add layer button behaviour
- added search window in tag filter
- added new tags for continent, region and country in tag filter
> fix: fixed mosaicjson api bug and improved tag filter

- sites/geohub/static/api/swagger/spec.yaml
> doc: added security in swagger yaml

- sites/geohub/src/components/data-upload/DataPreview.svelte
- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
> fix: disabled preview button if the original file is not pmtiles because we are not sure whether it is cloud optimised

- sites/geohub/src/components/controls/RasterDefaultLegend.svelte
> fix: changed the position of unit to the bottom of slider

- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/routes/api/datasets/[id]/+server.ts
- fix: clear textbox for deleted dataset name typed by user when dialog is closed
- fix: only generate .ingesting file if URL has string of 'userdata/{id}/datasets' when dataset is unregistered
> fix: data upload bug

- .changeset/curvy-suits-happen.md
- .changeset/smooth-books-accept.md
- packages/geohub-cli/package.json
- packages/geohub-cli/src/cli/cog-unit-update.ts
- packages/geohub-cli/src/cli/index.ts
- packages/geohub-cli/src/interfaces/DatasetFeature.ts
- packages/geohub-cli/src/interfaces/DatasetFeatureCollection.ts
- packages/geohub-cli/src/interfaces/index.ts
- packages/geohub-cli/src/util/PgtileservManager.ts
- packages/geohub-cli/src/util/Tags.ts
- pnpm-lock.yaml
> fix: 1470 migrate unit

- sites/geohub/src/components/data-upload/TagInput.svelte
- sites/geohub/src/lib/constants.ts
- sites/geohub/src/routes/data/publish/+page.svelte
created a new constraint variable to share between two components.
> fix: bug of unit in data publish page

- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/routes/data/upload/+page.svelte
added validation for file name. it rejects if `<, >, ", /, \, |, ?, *, +` these characters are included in file name.
> fix: added file name validation in upload page

- sites/geohub/src/components/controls/RasterDefaultLegend.svelte
- sites/geohub/src/components/data-view/DataCardInfo.svelte
> fix: use tag for unit instead of using from band metadata

- README.md
> doc: updated readme

- sites/geohub/src/components/controls/VectorParamsPanel.svelte
> fix:slider cursor bounce

- sites/geohub/src/components/controls/VectorClassifyLegend.svelte
- sites/geohub/src/lib/server/helpers/fetchVectorInfo.ts
- sites/geohub/src/lib/server/helpers/generateMetadataJson.ts
- sites/geohub/src/lib/types/TileJson.ts
If there are fields which do not contain actual values (all values are null), we should not show them in property selectbox. This PR is going to remove those undefined values' columns from vector_layers and tilestats.
> fix: tilestats computing

- pnpm-lock.yaml
- sites/geohub/setupTest.ts
- sites/geohub/src/components/controls/vector-styles/FillColor.test.ts
- sites/geohub/src/components/controls/vector-styles/MaplibreColorPicker.svelte
- sites/geohub/src/lib/types/Layer.ts
- sites/geohub/vite.config.ts
trying to add test for component which uses maplibre
> test: added FillColor component test

- sites/geohub/src/components/controls/RasterBandSelector.svelte
closes #1517 
- fixed bug of getting error when switch band.
- use tippy to show band selector
> fix: switch bands in raster layer

- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/components/DataView.svelte
- sites/geohub/src/components/data-view/DataCard.svelte
- sites/geohub/src/components/data-view/DataCategoryCardList.svelte
- sites/geohub/src/routes/+page.server.ts
closes #1521
introduced streaming for main page
> feat: page streaming

- sites/geohub/src/components/Header.svelte
- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/lib/config/AppConfig/FooterItems.ts
- sites/geohub/src/lib/config/AppConfig/HeaderItems.ts
- sites/geohub/src/routes/data/+page.svelte
- sites/geohub/src/routes/maps/+page.svelte
- sites/geohub/src/routes/settings/+page.svelte
- added link for /data page
- added refresh button
> feat: add data link

- Makefile
added Makefile for some shortcuts
> feat: added Makefile

- sites/geohub/src/components/DataView.svelte
- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/components/data-view/DataCategoryCardList.svelte
- sites/geohub/src/components/data-view/SelectedTags.svelte
- sites/geohub/src/components/data-view/TagFilter.svelte
- sites/geohub/src/lib/config/AppConfig/DatasetSearchQueryParams.ts
- sites/geohub/src/routes/+page.server.ts
now menus and breadcrumbs are created in +page.server.ts
> refactor: move breadcrumbs to backend

- sites/geohub/src/components/data-upload/CountryPicker.svelte
- sites/geohub/src/routes/api/continents/+server.ts
- sites/geohub/src/routes/api/countries/+server.ts
- sites/geohub/src/routes/api/regions/+server.ts
- sites/geohub/static/api/swagger/spec.yaml
- added admin apis to swagger (I forget to add them before)
- added `filterbytag` option for admin apis
- fixed bug of CountryPicker
> doc: add admin api to swagger

- .changeset/loud-rockets-hide.md
- packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.stories.ts
> doc: update Breadcrumbs.stories.ts

- sites/geohub/src/components/Settings.svelte
> fix: form action and improve styles

- sites/geohub/src/components/App.svelte
- sites/geohub/src/components/Settings.svelte
- sites/geohub/src/components/SplitterControl.svelte
> fix: reflect sidebar position

- sites/geohub/src/components/data-upload/TagInput.svelte
- sites/geohub/src/components/data-upload/Tags.svelte
- sites/geohub/src/routes/data/publish/+page.svelte
> fix: bug of deleting tag in publish page

- sites/geohub/src/components/data-upload/CountryPicker.svelte
- sites/geohub/src/routes/data/+layout.svelte
- sites/geohub/src/routes/data/publish/+page.server.ts
- sites/geohub/src/routes/data/publish/+page.svelte
> feat: implemented new country selector

- sites/geohub/src/components/DataView.svelte
- sites/geohub/src/components/controls/RasterLegend.svelte
- sites/geohub/src/components/controls/VectorLegend.svelte
…rLegend`
New help text for `DataView`, `RasterLegend`, `VectorLegend`
> refactor: enhance help text for `DataView`, `RasterLegend`, `VectorLegend`

- sites/geohub/src/components/DataView.svelte
- sites/geohub/src/components/data-upload/CountryPicker.svelte
- sites/geohub/src/components/data-view/DataCard.svelte
- sites/geohub/src/lib/config/AppConfig/TagInputValues.ts
- sites/geohub/src/lib/config/AppConfig/TagSearchKeys.ts
- sites/geohub/src/routes/+page.server.ts
- sites/geohub/src/routes/data/publish/+page.svelte
> fix: country picker

- README.md
@iferencik review for me
added mermaid diagrams for azure ad and pipeline
> doc: added some sequence diagrams in readme

- sites/geohub/src/components/Help.svelte
- sites/geohub/src/components/Settings.svelte
- sites/geohub/src/components/controls/FieldControl.svelte
- sites/geohub/src/components/controls/FieldControl.test.ts
- sites/geohub/src/routes/settings/+page.svelte
@Thuhaa review it for me.
- added Help component
- added more description
> feat: add help in settings

- .changeset/loud-kings-rest.md
- packages/svelte-undp-design/src/lib/Header/Header.svelte
- sites/geohub/src/routes/+error.svelte
- sites/geohub/src/routes/maps/+page.svelte
- sites/geohub/src/routes/settings/+page.svelte
fixed margin of menu-item in UNDP header. moved CSS to the component
> fix: margin of menu-item in undp header

- sites/geohub/src/components/StyleShare.svelte
- sites/geohub/src/components/data-upload/CountryPicker.svelte
- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/components/data-view/AddLayerButton.svelte
- sites/geohub/src/components/data-view/DataCard.svelte
- sites/geohub/src/routes/data/publish/+page.svelte
- fixed UNDP loader style
- fixed bug of saved style dialog
- fixed bug of ingesting datasets 
> fix: loader style

- sites/geohub/src/components/StyleShare.svelte
- sites/geohub/src/components/data-upload/CountryPicker.svelte
- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/components/data-view/AddLayerButton.svelte
- sites/geohub/src/components/data-view/DataCard.svelte
- sites/geohub/src/routes/data/publish/+page.svelte
> chore: develop to main

- sites/geohub/src/components/Header.svelte
- sites/geohub/src/components/UserAccount.svelte
- sites/geohub/src/routes/+error.svelte
- sites/geohub/src/routes/dashboards/+page.svelte
- sites/geohub/src/routes/maps/+page.svelte
- sites/geohub/src/routes/settings/+page.server.ts
- redirect from `/settings` to `/` if users do not sign in
- disable `/data` menu in header if users do not sign in
- add `/data` menu in dashboard page (I forgot to add it)
- Close user menu by clicking outside.
> fix: disable settings

- sites/geohub/src/components/Settings.svelte
- sites/geohub/src/routes/settings/+page.svelte
- refactored source code on settings
- remember selected tab in URL hash
- added reset to default button
- added back to previous button
> feat: settings enhancement

- .github/ISSUE_TEMPLATE/data_issue.yml
> doc: added data issue report

- sites/geohub/src/routes/dashboards/electricity/+page.ts
I reverted from prerender to csr. I thought prerender is fine, but it has a problem in production. I checked it in `make dockerrun` command, and electricity dashboard works in docker.
> fix: reverted electricity dashboard from prerender to csr

- package.json
- sites/geohub/src/lib/config/AppConfig/FooterItems.ts
> Update FooterItems.ts (#1696)

- .github/workflows/main_undpgeohub.yml
- Dockerfile
There is an error when building for production as follows.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: geohub@0.0.2
npm ERR! Found: svelte@4.1.2
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^4.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"3.x" from svelte-htm@1.2.0
npm ERR! node_modules/svelte-htm
npm ERR!   dev svelte-htm@"^1.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! …
```
> fix: added --legacy-peer-deps command in CI

- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/lib/helper/downloadFile.ts
When I tried `make dockerrun` locally, there is an error occurred by mime library.
Only downloadFile function uses mime, and it is not actually necessary. So I removed mime library completely. The docker works well in my local computer now. Hope it will work in production too.
> fix: remove mime package from downloadFile function

- .changeset/tender-birds-fix.md
- packages/svelte-undp-design/src/lib/Header/Header.stories.ts
- packages/svelte-undp-design/src/lib/Header/Header.svelte
- packages/svelte-undp-design/src/lib/Header/Header.test.ts
- packages/svelte-undp-design/src/lib/interfaces/HeaderLink.ts
- sites/geohub/src/components/Header.svelte
- sites/geohub/src/lib/config/AppConfig/HeaderItems.ts
Removed icons from header as original UNDP design's header has no icons. Tooltip text will be shown if the mouse is hovered on title menu.
For responsive menu, I added tooltip next to title to help users understand.
> fix: removed icon from UNDP header.

- .changeset/tender-birds-fix.md
- packages/svelte-undp-design/src/lib/Header/Header.stories.ts
- packages/svelte-undp-design/src/lib/Header/Header.svelte
- packages/svelte-undp-design/src/lib/Header/Header.test.ts
- packages/svelte-undp-design/src/lib/interfaces/HeaderLink.ts
- sites/geohub/src/components/Header.svelte
- sites/geohub/src/components/UserAccount.svelte
- sites/geohub/src/lib/config/AppConfig/HeaderItems.ts
Please merge PR #1738  first before merging this PR.
Normal) If window width is greater than 1440, 
Responsive) If window width is less than 1440,
> feat: improved UserAccount component to show name, title and email in header

- .changeset/fifty-hotels-begin.md
- packages/svelte-undp-design/src/lib/Header/Header.svelte
- packages/svelte-undp-design/src/lib/css/base-minimal.min.css
- packages/svelte-undp-design/src/lib/css/country-site-header.min.css
- packages/svelte-undp-design/src/lib/css/mega-menu.min.css
- packages/svelte-undp-design/src/lib/css/menu.min.css
- packages/svelte-undp-design/src/lib/css/mobile-nav.min.css
- sites/geohub/src/components/UserAccount.svelte
> fix: updated UNDP header's CSS and HTML

- .changeset/green-rockets-clap.md
- packages/style-switcher/package.json
- packages/style-switcher/src/lib/StyleSwitcher.svelte
- pnpm-lock.yaml
> fix: changed control css name from 'mapboxgl-ctrl' to 'maplibregl-ctrl'

- sites/geohub/src/components/App.svelte
> fix: set initial/min sidebar width

- sites/geohub/src/components/App.svelte
- sites/geohub/src/components/LayerList.svelte
- sites/geohub/src/components/StyleShare.svelte
- sites/geohub/src/components/controls/LegendColorMapRow.svelte
- sites/geohub/src/components/controls/vector-styles/IconImage.svelte
- sites/geohub/src/components/controls/vector-styles/IconSize.svelte
- sites/geohub/src/components/controls/vector-styles/MaplibreColorPicker.svelte
- sites/geohub/src/lib/helper/index.ts
- sites/geohub/src/lib/helper/isStyleChanged.ts
- sites/geohub/src/lib/helper/localstorage.ts
New state management's concept is described in discussion page: https://github.com/UNDP-Data/geohub/discussions/1747
Note. There is a different bug from this state management. The rgba color on vector layer is not reflected to style.json in map object even the color is reflected on the map. I created new issue for that (https://github.com/UNDP-Data/geohub/issues/1749).
> feat: Use local storage to save layerList and map style to prevent losing user's work if they move to different page

- sites/geohub/src/components/maps/MapStyleCard.svelte
- sites/geohub/src/components/maps/MapStyleCardList.svelte
- sites/geohub/src/lib/server/helpers/pageNumber.ts
- sites/geohub/src/routes/api/style/+server.ts
> refactor: change shared map layout

- sites/geohub/src/routes/(app)/+layout.svelte
> fix: recreate header links after navigate

- pnpm-lock.yaml
- sites/geohub/package.json
Since /api/og does not work, I moved sveltekit-og to devDependencies
> fix: moved sveltekit-og to devDependencies

- .changeset/cool-hounds-brake.md
- packages/current-location/src/lib/AdminLayer.ts
- sites/geohub/src/routes/(app)/+page.svelte
- sites/geohub/src/routes/(maps)/dashboards/electricity/+page.server.ts
- sites/geohub/src/routes/(maps)/dashboards/electricity/+page.svelte
- sites/geohub/src/routes/(maps)/dashboards/electricity/components/Charts.svelte
- sites/geohub/src/routes/(maps)/dashboards/electricity/components/TimeSlider.svelte
- sites/geohub/src/routes/(maps)/dashboards/electricity/interfaces/ElectricityDatasets.ts
- sites/geohub/src/routes/(maps)/dashboards/electricity/interfaces/index.ts
- sites/geohub/src/routes/(maps)/dashboards/electricity/stores/index.ts
- sites/geohub/src/routes/(maps)/dashboards/electricity/utils/adminLayer.ts
- fix page data loading of dashboard by using streaming at load function
- fixed bug of setting feature state id in current-location plugin
> fix: page loading of electricity dashboard

- .changeset/brown-donuts-sing.md
- packages/svelte-undp-design/src/lib/FluidCarousel/FluidCarousel.svelte
> fix: changed href of a tag to on:click event to open the link in FluidCarousel component

- sites/geohub/src/components/data-upload/PublishedDataset.svelte
- sites/geohub/src/components/data-upload/PublishedDatasetHeader.svelte
- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/components/data-view/MiniMap.svelte
redesigning layout of published dataset table
- Desktop
- Mobile
> feat: redesign dataset table

- .changeset/little-carpets-obey.md
- packages/undp-bulma/bulma.scss
- sites/geohub/src/routes/(app)/data/+page.svelte
Changed tabs from UNDP to Bulma in data page
> feat: changed UNDP design tab to Bulma tab

- sites/geohub/src/components/data-upload/DataPreview.svelte
- sites/geohub/src/components/data-upload/DataPreviewContent.svelte
- sites/geohub/src/components/data-upload/PublishedDatasetRow.svelte
- sites/geohub/src/components/data-view/MiniMap.svelte
added selectbox for data preview in Data tab to select a layer if it is multiple vector tiles (like pmtiles)
> feat: added selectbox to select a pmtiles layer to preview in Data tab

- .changeset/famous-apes-hammer.md
- packages/svelte-undp-design/src/lib/Header/Header.svelte
- sites/geohub/src/lib/config/AppConfig/HeaderItems.ts
- sites/geohub/src/routes/(app)/+page.svelte
- deleted tooltip from UNDP header menu (I feel it is not necessary now since we stop using icon)
- updated menu texts
- added data page link button in home page
> fix: update header menus

- sites/geohub/src/components/data-upload/PublishedDatasetRow.svelte
- sites/geohub/src/components/data-view/Star.svelte
- added star button in dataset table in data tab.
- added isCompact option in Star.svelte
> feat: added star button in dataset table in data tab

- sites/geohub/src/components/Content.svelte
- sites/geohub/src/components/LayerList.svelte
- sites/geohub/src/lib/config/AppConfig/DatasetSearchQueryParams.ts
new tab screenshot
also, query param of `activetab` will be added in URL of /map page to remember users' selection.
> feat: changed UNDP tab to Bulma tab in /map page

- sites/geohub/src/components/data-upload/PublishedDatasetHeader.svelte
- sites/geohub/src/components/data-upload/PublishedDatasetRow.svelte
- sites/geohub/src/components/data-view/DataVectorCard.svelte
- sites/geohub/src/components/data-view/LayerTypeSwitch.svelte
- sites/geohub/src/lib/RasterTileData.ts
- sites/geohub/src/lib/VectorTileData.ts
- sites/geohub/src/lib/helper/localstorage.ts
> feat: added show it on map button in data page preview

- packages/style-switcher/src/example/Map.svelte
- sites/geohub/src/lib/config/AppConfig/MapStyles.ts
> fix: changed style.json URL to CDN

- sites/geohub/src/components/Header.svelte
- sites/geohub/src/components/LayerList.svelte
- sites/geohub/src/components/Map.svelte
- sites/geohub/src/components/data-view/LayerTypeSwitch.svelte
- sites/geohub/src/lib/helper/getSpriteImageIist.ts
- sites/geohub/src/lib/helper/index.ts
- sites/geohub/src/routes/(app)/+layout.svelte
- sites/geohub/src/routes/(app)/+page.svelte
- fix: check whether layer is defined or not in layertypeswitcher
- fix: set style= query param from other page if styleId is stored in local storage
- fix: reload spriteImageList if it is not loaded
> fix: bug of setting style id in URL and others

- sites/geohub/src/components/LayerList.svelte
fixed a bug of trying to restore styles when $map variable become ready. moved the logic to inside `$: if ($map)` statement
> fix: changed the timing of restoring style

- sites/geohub/src/components/data-upload/PublishedDatasetRow.svelte
> fix: add if statement to check whether selected vector layer variable is available

- sites/geohub/src/components/LayerList.svelte
- sites/geohub/src/components/StyleShare.svelte
- sites/geohub/src/routes/(app)/map/+page.server.ts
stop using streaming to fetch existing style in load function
also fixes several bugs to restore style from localstorage or database
> fix: changed style loading from streaming to normal way in load function

- .changeset/perfect-stingrays-greet.md
- packages/style-switcher/src/lib/StyleSwitcher.svelte
> fix: restore current selected map state to style switcher button

- sites/geohub/src/components/data-view/DataCard.svelte
- sites/geohub/src/components/data-view/DataStacAssetCard.svelte
- sites/geohub/src/components/data-view/DataVectorCard.svelte
- sites/geohub/src/components/data-view/Star.svelte
- sites/geohub/src/lib/helper/loadMap.ts
- sites/geohub/src/stores/index.ts
removed unused store values of `indicatorProgress` and `layerState`
> refactor: deleted two store values which are not actually used

- sites/geohub/src/components/data-upload/PublishedDataset.svelte
- sites/geohub/src/components/data-upload/PublishedDatasetRow.svelte
- sites/geohub/src/routes/(app)/data/[id]/+page.server.ts
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
- sites/geohub/src/routes/(app)/data/[id]/+page.ts
- sites/geohub/src/routes/api/og/+server.ts
- added /data/{id} page for a dataset
- enabled SSR for dataset page (not sure it can work!! just try)
- fixed `/og` api. make font size smaller if the length of content is long.
> feat: create individual page for dataset in URL of /data/{id}, and added link in /data page table

- sites/geohub/src/components/data-upload/PublishedDatasetOperations.svelte
- sites/geohub/src/components/data-upload/PublishedDatasetRow.svelte
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
> refactor: created a common component for dataset operation menu

- .changeset/ninety-geese-itch.md
- .changeset/shaggy-worms-kiss.md
- packages/svelte-undp-design/src/lib/CtaLink/CtaLink.svelte
- packages/svelte-undp-design/src/lib/Download/Download.svelte
- sites/geohub/src/components/CopyToClipboard.svelte
- sites/geohub/src/components/StyleShare.svelte
- sites/geohub/src/components/data-upload/PublishedDataset.svelte
- sites/geohub/src/components/data-upload/PublishedDatasetRow.svelte
- sites/geohub/src/components/data-view/DataCardInfo.svelte
- sites/geohub/src/components/maps/MapStyleCard.svelte
- sites/geohub/src/lib/server/helpers/createDatasetLinks.ts
- sites/geohub/src/lib/server/helpers/index.ts
- sites/geohub/src/lib/types/DatasetFeature.ts
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
- sites/geohub/src/routes/(app)/data/[id]/+page.ts
- sites/geohub/src/routes/(app)/map/+layout@.svelte
- sites/geohub/src/routes/api/datasets/+server.ts
- sites/geohub/src/routes/api/datasets/[id]/+server.ts
- sites/geohub/static/api/swagger/spec.yaml
- added relevant dataset links in `/datasets/` and `/datasets/{id}` api
- added readmore button in details section of data page
- added relevant API links for developers in `/data/{id}` page. 
- fixed UNDP download component to use href instead of using callback.
- created `CopyToClipboard` component
> feat: add links in dataset api to manage relevant API links together

- sites/geohub/src/components/data-view/MiniMap.svelte
> fix: set the height of loader in minimap

- .changeset/calm-files-retire.md
- packages/style-switcher/src/lib/StyleSwitcher.svelte
> fix: fixed a bug of style switching when default style is bing aerial

- README.md
- sites/geohub/src/lib/config/AppConfig/MapStyles.ts
> feat: updated style.json version to v1.1.0 to use Proxima Nova font

- pnpm-lock.yaml
- sites/geohub/package.json
> fix: package.json of geohub

- sites/geohub/src/components/UserAccount.svelte
* before click user account button
* after click
header height will become larger.
This PR is going to fix this weird bug
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1200006041) by [Unito](https://www.unito.io)
> fix: fixed weird behaviour when click to show user account dropdown menu

- sites/geohub/src/components/LayerHeader.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1200047774) by [Unito](https://www.unito.io)
> fix: removed vector label icon from layer header since it is not very useful

- sites/geohub/src/routes/(app)/+page.svelte
- sites/geohub/src/routes/(app)/api/+page.svelte
- sites/geohub/src/routes/(app)/data/+page.svelte
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
- sites/geohub/src/routes/(app)/data/publish/+page.svelte
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
- sites/geohub/src/routes/(app)/settings/+page.svelte
- sites/geohub/src/routes/(map)/map/+page.svelte
- sites/geohub/src/routes/(map)/map/[id]/+page.svelte
- sites/geohub/src/routes/dashboards/electricity/+page.svelte
- sites/geohub/src/routes/dashboards/electricity/+page.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1200307327) by [Unito](https://www.unito.io)
> fix: Disable electricity ssr

- sites/geohub/src/components/data-upload/IngestingDatasetRow.svelte
- sites/geohub/src/components/data-upload/IngestingDatasetRowDetail.svelte
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
- sites/geohub/src/routes/api/datasets/ingesting/+server.ts
/datasets/ingesting API does not work when there are multiple layers under a raw dataset.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1200861156) by [Unito](https://www.unito.io)
> fix: bug of ingesting table when there are multiple layers under a raw dataset

- sites/geohub/src/routes/(map)/+layout.server.ts
- sites/geohub/src/routes/(map)/+layout.svelte
- sites/geohub/src/routes/(map)/dashboards/electricity/+page.server.ts
- sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
- sites/geohub/src/routes/(map)/map/+layout.server.ts
- sites/geohub/src/routes/(map)/map/+layout.svelte
added header in Electricity dashboard
Screenshots with new header are shown in below.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1200408824) by [Unito](https://www.unito.io)
> feat: electricity add header

- sites/geohub/src/components/data-upload/IngestingDatasetHeader.svelte
- sites/geohub/src/components/data-upload/IngestingDatasetRow.svelte
- sites/geohub/src/components/data-upload/IngestingDatasetRowDetail.svelte
- sites/geohub/src/components/data-upload/PublishedDatasetDeleteDialog.svelte
- sites/geohub/src/components/data-upload/PublishedDatasetOperations.svelte
* renamed cancel button to delete button
* added icon for dropdown menu items
* added `edit` button and `unpublish` button in my data tab. now users directly can edit or delete published dataset
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1201068549) by [Unito](https://www.unito.io)
> fix: cancel button name

- sites/geohub/src/components/Settings.svelte
- sites/geohub/src/components/data-upload/DataUploadButton.svelte
- sites/geohub/src/components/data-upload/IngestingDatasetHeader.svelte
- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/lib/config/AppConfig/DatasetSearchQueryParams.ts
- sites/geohub/src/lib/config/AppConfig/IngestingDatasetSortingColumns.ts
- sites/geohub/src/lib/config/AppConfig/index.ts
- sites/geohub/src/lib/config/DefaultUserConfig/DataPageIngestingSortingColumn.ts
- sites/geohub/src/lib/config/DefaultUserConfig/DataPageIngestingSortingOrder.ts
- sites/geohub/src/lib/config/DefaultUserConfig/index.ts
- sites/geohub/src/routes/(app)/+page.svelte
- sites/geohub/src/routes/(app)/data/+layout.svelte
- sites/geohub/src/routes/(app)/data/+page.server.ts
- sites/geohub/src/routes/(app)/data/+page.svelte
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
- sites/geohub/src/routes/(app)/data/publish/+page.svelte
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
- sites/geohub/src/routes/api/datasets/ingesting/+server.ts
- sites/geohub/static/api/swagger/spec.yaml
* added upload button in the bottom page
* added sortby and sortorder option in /ingesting api
* added sortable columns in my data table (name, size, uploaded at are available to sort)
* added default sorting column and order in settings.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1201878114) by [Unito](https://www.unito.io)
> feat: add Upload button in landing page, add sorting feature for my data

- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/components/data-upload/SdgCard.svelte
- sites/geohub/src/components/data-upload/SdgPicker.svelte
* Added SDG filtering in data page
* Added the notification message of total number of datasets found
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1202656550) by [Unito](https://www.unito.io)
> feat: added SDG filtering in data page

- sites/geohub/src/components/data-upload/IngestingDatasetRow.svelte
- sites/geohub/src/lib/types/IngestingDataset.ts
- sites/geohub/src/routes/api/datasets/ingesting/+server.ts
* changed to dropdown menu for raw data operations
* moved delete button to dropdown menu
* created new menu operation to show log file (if applicable)
* redesign log dialog
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1203257625) by [Unito](https://www.unito.io)
> feat: changed delete button to dropdown menu and add new menu for showing log file

- sites/geohub/src/routes/(app)/data/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1203626000) by [Unito](https://www.unito.io)
> fix: removed `a` for the text of searching by SDG

- sites/geohub/src/routes/(app)/data/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1204110692) by [Unito](https://www.unito.io)
> fix: removed duplicated label in data page

- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/routes/(app)/data/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1204161065) by [Unito](https://www.unito.io)
> feat: add country and continent tag to make them visible in datatable

- .changeset/silly-rivers-shop.md
- packages/svelte-undp-design/src/lib/SearchExpand/SearchExpand.stories.ts
- packages/svelte-undp-design/src/lib/SearchExpand/SearchExpand.svelte
- sites/geohub/src/components/DataView.svelte
- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/components/data-view/TagFilter.svelte
- sites/geohub/src/components/data-view/TextFilter.svelte
- sites/geohub/src/components/maps/MapStyleCardList.svelte
- sites/geohub/src/lib/config/AppConfig/SearchDebounceTime.ts
- sites/geohub/src/lib/config/AppConfig/TourOptions.ts
- sites/geohub/src/lib/config/AppConfig/index.ts
* changed bounce timeout from 500ms to 1sec
* introduced SearchExpand to home page and map page
* introduced `disabled` and `loading` options in SearchExpand
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1205105153) by [Unito](https://www.unito.io)
> fix: search expand

- sites/geohub/src/routes/api/style/[id].json/+server.ts
- sites/geohub/static/api/swagger/spec.yaml
closes #1709
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1205226308) by [Unito](https://www.unito.io)
> feat: add exclude param in style.json api to remove basemap's sources and layers

- sites/geohub/src/components/LayerTemplate.svelte
- sites/geohub/src/components/RasterLayer.svelte
- sites/geohub/src/components/VectorLayer.svelte
- sites/geohub/src/lib/types/Layer.ts
- sites/geohub/src/routes/(map)/map/[id]/+page.svelte
- sites/geohub/src/stores/layerList.ts
closes #1497
store active tab for each layer in layerList store and store it in database as well
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1205270913) by [Unito](https://www.unito.io)
> feat: remember active tab

- sites/geohub/src/components/data-upload/IngestingDatasetRow.svelte
delete .log file as well.
but I think we need to move this kind of logic to server side...
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206169600) by [Unito](https://www.unito.io)
> fix: delete log file for ingesting dataset

- .github/workflows/ci.yml
- Dockerfile
- README.md
- sites/geohub/build-nodemodules.sh
* refactored deploy script
* added CI and license badge in readme
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206324184) by [Unito](https://www.unito.io)
> reafactor: create script for nodemodules

- .github/workflows/ci.yml
Upload build files to artifact in build job, then download artifact in deploy job.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206548984) by [Unito](https://www.unito.io)
> refactor: upload artifact after building, then download in deploy job

- .github/workflows/ci.yml
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206570564) by [Unito](https://www.unito.io)
> fix: unzip downloaded artifact

- sites/geohub/src/lib/server/helpers/createDatasetSearchWhereExpression.ts
very stupid mistake...
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206860989) by [Unito](https://www.unito.io)
> fix: bug of when dataset is shared within UNDP

- sites/geohub/src/components/controls/RasterHistogram.svelte
- sites/geohub/src/lib/RasterTileData.ts
fixes #1906
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206875331) by [Unito](https://www.unito.io)
> fix: bug of updating statistics from stats api

- sites/geohub/src/components/data-upload/IngestingDatasetRow.svelte
The cancel dialog is shown in the below screenshot
The format of cancel message is defined at this discussion page.
https://github.com/UNDP-Data/geohub/discussions/545#discussioncomment-7081485
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1207684082) by [Unito](https://www.unito.io)
> feat: add cancel dialog and menu for in progress ingesting dataset

- .changeset/cold-points-invent.md
- packages/svelte-undp-design/src/lib/Header/Header.svelte
- packages/svelte-undp-design/src/lib/Header/Header.test.ts
- packages/svelte-undp-design/vite.config.js
- sites/geohub/src/components/BackToTop.svelte
- sites/geohub/src/components/Header.svelte
- sites/geohub/src/components/MapHero.svelte
- sites/geohub/src/components/Settings.svelte
- sites/geohub/src/components/Tags.svelte
- sites/geohub/src/components/data-view/Star.svelte
- sites/geohub/src/components/maps/MapStyleCardList.svelte
- sites/geohub/src/routes/(app)/+layout@.svelte
- sites/geohub/src/routes/(app)/+page.server.ts
- sites/geohub/src/routes/(app)/+page.svelte
- sites/geohub/src/routes/(app)/+page.ts
- sites/geohub/src/routes/(app)/api/+page.svelte
- sites/geohub/src/routes/(app)/api/+page.ts
- sites/geohub/src/routes/(app)/data/+page.svelte
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
- sites/geohub/src/routes/(app)/data/[id]/+page.ts
- sites/geohub/src/routes/(app)/data/publish/+page.ts
- sites/geohub/src/routes/(app)/data/upload/+page.ts
- sites/geohub/src/routes/(app)/settings/+page.ts
- sites/geohub/src/routes/(auth)/auth/signIn/+page.ts
- sites/geohub/src/routes/(map)/dashboards/electricity/+page.ts
- sites/geohub/src/routes/(map)/map/+layout.svelte
So far, I turned to SSR for the following pages:
* `/`: home page
* `/auth/signIn`: Sign in page
* `/settings`
* `/api`
* `/data{id}`
* `/data/upload`
* `/data/publish`
SSR cannot return promises in load function, so turning to SSR in `/data` and `/map` is not done yet.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1213150055) by [Unito](https://www.unito.io)
> feat: turn to ssr

- sites/geohub/src/routes/(map)/dashboards/electricity/+page.ts
currently only Electricity dashboard does not work for SSR. Let me switch to CSR for now.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1213224168) by [Unito](https://www.unito.io)
> fix: disable SSR for Electricity Dashboard for now

- sites/geohub/src/components/DataView.svelte
- sites/geohub/src/components/MapHero.svelte
- sites/geohub/src/components/data-upload/IngestingDatasetRow.svelte
- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/components/data-view/Star.svelte
- sites/geohub/src/components/data-view/TagFilter.svelte
- sites/geohub/src/components/data-view/TextFilter.svelte
- sites/geohub/src/routes/(app)/+page.server.ts
- sites/geohub/src/routes/(app)/+page.svelte
- sites/geohub/src/routes/(app)/data/+page.server.ts
- sites/geohub/src/routes/(app)/data/+page.svelte
- sites/geohub/src/routes/(app)/data/+page.ts
- sites/geohub/src/routes/(map)/map/+layout.server.ts
* turned /data page to SSR
* tag filter does work in data page, but it does not work for map page. the logic of searching in map page is too complicated. Since the tag filter seems not very useful in map page, I deleted it for now. But it is still there in data page
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1213421590) by [Unito](https://www.unito.io)
> feat: turn data to ssr

- sites/geohub/src/components/data-upload/IngestingDatasetRow.svelte
- sites/geohub/src/routes/(app)/+page.svelte
- sites/geohub/src/routes/(app)/data/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1214037939) by [Unito](https://www.unito.io)
> fix: show ingested datasets even for failed dataset

- sites/geohub/src/components/data-upload/IngestingDatasetRow.svelte
- sites/geohub/src/routes/(app)/data/+page.svelte
- sites/geohub/src/routes/(app)/data/+page.ts
fixed bug of parsing received websocket message
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1214175163) by [Unito](https://www.unito.io)
> fix: bug of websocket client message

- sites/geohub/build-nodemodules.sh
Reverts UNDP-Data/geohub#1927
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1214767722) by [Unito](https://www.unito.io)
> Revert "fix: don't copy package.json to deployment"

- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/app.d.ts
- sites/geohub/src/hooks.server.ts
- sites/geohub/src/routes/(app)/+error.svelte
I found some posts in svelte discord mentioning sentury-node for the error of `ReferenceError: require is not defined in ES module scope, you can use import instead`. Let me try to remove it
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1214854306) by [Unito](https://www.unito.io)
> remove sentury-node

- sites/geohub/src/components/controls/FieldControl.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1214876142) by [Unito](https://www.unito.io)
> fix: changed help button position to just next to title

- sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
- sites/geohub/src/routes/(map)/map/+layout.svelte
hope this can solve the error
I saw log as follows.
```shell
2023-09-27T13:05:10.682291690Z ReferenceError: require is not defined in ES module scope, you can use import instead
2023-09-27T13:05:10.682335891Z This file is being treated as an ES module because it has a '.js' file extension and '/home/site/wwwroot/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
2023-09-27T13:05:10.682343591Z     at file:///home/site/wwwroot/server/chunks/MenuControl-1ee6a12c.js:3854:16
2023-09-27T13:05:10.682348991Z     at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```
Refer to [CONTRIBUTING.MD](https://github.com/UNDP-Data/geohub/blob/develop/CONTRIBUTING.md) for more …
> fix: only execute MenuControl in client side

- packages/geohub-cli/package.json
- packages/geohub-cli/src/cli/cog-unit-update.ts
- pnpm-lock.yaml
hope it will fix this CI error
https://github.com/UNDP-Data/geohub/actions/runs/6326728202/job/17180918593
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1214906345) by [Unito](https://www.unito.io)
> fix: removed sleep from geohub-cli

- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/routes/(app)/+layout@.svelte
- sites/geohub/src/routes/(auth)/auth/+layout@.svelte
- sites/geohub/src/routes/(map)/+layout@.svelte
- sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
- sites/geohub/src/routes/(map)/map/+layout.svelte
- sites/geohub/src/routes/+layout.svelte
* Updated menu control (https://github.com/watergis/svelte-maplibre-components/pull/338)
* refactored some codes to move to +layout.svelte (for svelte:html and css import)
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1214964135) by [Unito](https://www.unito.io)
> fix: updated menu control

- sites/geohub/src/lib/MosaicJsonData.ts
current version does not work in `/map` page because it uses relative path
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1214984559) by [Unito](https://www.unito.io)
> fix: mosaicjson API path in MosaicJsonData.ts

- sites/geohub/src/lib/MosaicJsonData.ts
- sites/geohub/src/service-worker.js
I found the following error log in server.
I added `service-worker.js` by using the sveltekit's example (https://kit.svelte.dev/docs/service-workers#inside-the-service-worker). But it will exclude caching from titiler, pgtileserv, martin and microsoft planetary.
```shell
2023-09-27T15:24:40.306012974Z ReferenceError: require is not defined in ES module scope, you can use import instead
2023-09-27T15:24:40.306082476Z This file is being treated as an ES module because it has a '.js' file extension and '/home/site/wwwroot/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
2023-09-27T15:24:40.306091076Z     at file:///home/site/wwwroot/server/chunks/MenuControl-eea18ba8.js:3854:16 …
```
> feat: add service-worker.js

- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/components/data-upload/PublishedDataset.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1215036507) by [Unito](https://www.unito.io)
> fix: updated menu-control

- sites/geohub/src/routes/(map)/dashboards/electricity/+page.ts
- sites/geohub/src/routes/(map)/map/+page.ts
- sites/geohub/src/routes/(map)/map/[id]/+page.ts
back to CSR
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1215127283) by [Unito](https://www.unito.io)
> fix: bring map and dashboard pages to CSR

- sites/geohub/src/components/data-upload/IngestingDatasetRow.svelte
- sites/geohub/src/components/data-upload/IngestingDatasetRowDetail.svelte
- sites/geohub/src/lib/config/AppConfig/AcceptedExtensions.ts
- sites/geohub/src/routes/(app)/data/upload/+page.server.ts
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
closes #1941 
also show warning message if file size is more than 100MB
new allowed file format
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1221233064) by [Unito](https://www.unito.io)
> fix: handle a file with two extensions, allow `.fgb` and other archive format to upload

- sites/geohub/src/app.html
I added `data-sveltekit-preload-data="hover" data-sveltekit-preload-code="viewport"` at body element of app.html
I hope it can improve performance of moving to a link
https://kit.svelte.dev/docs/link-options#data-sveltekit-preload-code
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1221240239) by [Unito](https://www.unito.io)
> fix: add data-sveltekit-preload-data/code prop in app.html

- sites/geohub/src/lib/config/AppConfig/FooterItems.ts
- sites/geohub/src/routes/(app)/data/publish/+page.server.ts
- sites/geohub/src/routes/(app)/settings/+page.server.ts
- sites/geohub/src/routes/+layout.svelte
- sites/geohub/static/api/swagger/spec.yaml
* add some error handling for some pages
* update page meta after navigating in layout
* updated api doc
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1221430219) by [Unito](https://www.unito.io)
> fix: error handling for pages

- sites/geohub/src/components/StyleShare.svelte
Now URL is always shown for existing map
Also, renamed `Share` to `Update` for existing map.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1222182885) by [Unito](https://www.unito.io)
> fix: some behaviours of share dialog. show shared URL always for exsitng map

- sites/geohub/src/components/StyleShare.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1222218782) by [Unito](https://www.unito.io)
> fix: show details as default in share dialog

- README.md
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1225316774) by [Unito](https://www.unito.io)
> doc: add link of static image api

- .changeset/green-bottles-jam.md
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1225337115) by [Unito](https://www.unito.io)
> fix:undp-data-header-changeset

- sites/geohub/.env.example
- sites/geohub/src/components/maps/MapStyleCard.svelte
- sites/geohub/src/components/maps/MapStyleCardList.svelte
- sites/geohub/src/lib/server/helpers/createStyleLinks.ts
- sites/geohub/src/lib/server/helpers/getStyleById.ts
- sites/geohub/src/lib/server/helpers/index.ts
- sites/geohub/src/routes/(map)/map/[id]/+page.server.ts
- sites/geohub/src/routes/api/style/+server.ts
- sites/geohub/src/routes/api/style/[id]/+server.ts
- sites/geohub/src/routes/api/style/[id]/static/[bbox]/[width]x[height].png/+server.ts
- sites/geohub/src/routes/api/style/[id]/static/[lon],[lat],[zoom],[bearing],[pitch]/[width]x[height].png/+server.ts
- sites/geohub/src/routes/api/style/[id]/static/auto/[width]x[height].png/+server.ts
- sites/geohub/static/api/swagger/spec.yaml
- sites/geohub/svelte.config.js
* added `/style/{id}/static/auto|{bbox}|{lon},{lat},{zoom},{bearing},{pitch}/{width}x{height}.png` endpoints to wrap static image API's POST method
* Use `/static/auto` api to get images for home page's map style card.
* updated swagger for new endpoints.
* To allow static image api to access to our style.json API, I slightly changed access validation. Now style.json can be accessed from any third parties, but all other style apis will check access level for the style.
I added two variables in `.env`
* GEOHUB_STATIC_IMAGE_API
* GEOHUB_API_ENDPOINT - this is only required for localhost. Because of using different app service, static image api cannot access to our localhost endpoints, temporally uses dev.undpgeohub.org for localhost. But in …
> feat: use static api for homepage

- sites/geohub/src/lib/server/helpers/getStyleById.ts
fixed the following error on prod
【 code  】
2023-10-04T17:20:25.058395192Z Error: Not found: /undefined/api/vector/pgtileserv/tile.json
2023-10-04T17:20:25.058474194Z     at resolve (file:///home/site/wwwroot/server/chunks/index-d3ff52f5.js:3607:18)
2023-10-04T17:20:25.058481394Z     at resolve (file:///home/site/wwwroot/server/chunks/index-d3ff52f5.js:3441:34)
2023-10-04T17:20:25.058487394Z     at resolve (file:///home/site/wwwroot/server/chunks/hooks.server-d977f172.js:91:16)
2023-10-04T17:20:25.058497895Z     at file:///home/site/wwwroot/server/chunks/hooks.server-d977f172.js:130:14
2023-10-04T17:20:25.058502995Z     at apply_handle (file:///home/site/wwwroot/server/chunks/hooks.server-d977f172.js:73:14)
2023-10-04T17:20:25.058507895Z     at …
> fix: fixed if statement to check origin is localhost or not

- sites/geohub/src/hooks.server.ts
- sites/geohub/src/lib/server/helpers/createStyleLinks.ts
fixes #1963 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1226622671) by [Unito](https://www.unito.io)
> fix: style links to return correct paths and add CORS settings

- sites/geohub/src/lib/server/helpers/createStyleLinks.ts
- sites/geohub/src/routes/api/style/[id]/static/[bbox]/[width]x[height].[format]/+server.ts
- sites/geohub/src/routes/api/style/[id]/static/[lon],[lat],[zoom],[bearing],[pitch]/[width]x[height].[format]/+server.ts
- sites/geohub/src/routes/api/style/[id]/static/auto/[width]x[height].[format]/+server.ts
- sites/geohub/static/api/swagger/spec.yaml
* use directly GET method of static api if in production
* use POST method of static api if in localhost
* changed file format from png to webp
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1226763041) by [Unito](https://www.unito.io)
> fix: Use POST method in localhost and use GET method in production for static image api

- sites/geohub/src/components/data-upload/PublishedDataset.svelte
- sites/geohub/src/components/data-upload/PublishedDatasetRow.svelte
- sites/geohub/src/components/data-view/DataCardInfo.svelte
- sites/geohub/src/components/data-view/Star.svelte
- sites/geohub/src/components/maps/MapStyleCard.svelte
- sites/geohub/src/lib/types/DashboardMapStyle.ts
- sites/geohub/src/routes/(app)/+page.svelte
fixes #1968 
fixes #1969 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1226805384) by [Unito](https://www.unito.io)
> fix: moved dashboard after community maps, and introduced delete confirmation for style deletion.

- sites/geohub/src/components/data-view/DataCard.svelte
- sites/geohub/src/components/stac/StacExplorer.svelte
- sites/geohub/src/lib/stac/MicrosoftPlanetaryStac.ts
* fix: add clicked event listener for the button after expanding accordion
* fix: skip to add datetime filter if from and to are same (for ALOS data)
* fix: not selecting asset as default except the collection only has one asset
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1229898084) by [Unito](https://www.unito.io)
> fix: fixed several bugs for stac explorer

- sites/geohub/src/lib/server/helpers/createStyleLinks.ts
- sites/geohub/src/lib/types/DashboardMapStyle.ts
- sites/geohub/src/lib/types/DatasetFeature.ts
- sites/geohub/src/lib/types/DatasetFeatureCollection.ts
- sites/geohub/src/lib/types/Link.ts
- sites/geohub/src/lib/types/MapsData.ts
- sites/geohub/src/lib/types/StacCatalog.ts
- sites/geohub/src/lib/types/StacCollection.ts
- sites/geohub/src/lib/types/StacCollections.ts
- sites/geohub/src/lib/types/StacItemFeature.ts
- sites/geohub/src/lib/types/StacItemFeatureCollection.ts
- sites/geohub/src/lib/types/index.ts
- sites/geohub/src/routes/api/datasets/+server.ts
- sites/geohub/src/routes/api/style/+server.ts
closes #1976
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1229924574) by [Unito](https://www.unito.io)
> refactor: renamed StacLink to Link

- sites/geohub/src/components/util/StacExplorer.svelte
closes #1998
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1231400626) by [Unito](https://www.unito.io)
> fix: stac add mergin

- sites/geohub/src/hooks.server.ts
- sites/geohub/svelte.config.js
I realised there many error logs related to handleCORS, and I feel this is not working properly. let me remove it.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1231473270) by [Unito](https://www.unito.io)
> fix: removed handleCORS from hooks.server.ts

- sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
- sites/geohub/src/lib/types/IngestingDataset.ts
- sites/geohub/src/routes/api/datasets/ingesting/+server.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1231640686) by [Unito](https://www.unito.io)
> fix: fetch stage and progress from blob metadata

- sites/geohub/src/components/maplibre/symbol/TextField.svelte
- sites/geohub/src/components/maplibre/symbol/TextFieldDecimalPosition.svelte
- sites/geohub/src/components/maplibre/symbol/TextHaloColor.svelte
- sites/geohub/src/components/maplibre/symbol/TextHaloWidth.svelte
- sites/geohub/src/components/maplibre/symbol/TextSize.svelte
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLabelPanel.svelte
- sites/geohub/src/components/util/NumberFormat.svelte
- sites/geohub/src/lib/helper/getTextFieldDataType.ts
- sites/geohub/src/lib/helper/index.ts
fixes #1972
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1233068209) by [Unito](https://www.unito.io)
> fix: decimal position bug

- Dockerfile
- sites/geohub/build-nodemodules.sh
- sites/geohub/pm2.json
closes #2015
I think I need to do the following settings to enable pm2
【 code  】
az webapp config set --resource-group "undpdpbppssdganalyticsgeo" --name "undpgeohub-dev" --startup-file "pm2.json"
az webapp config set --resource-group "undpdpbppssdganalyticsgeo" --name "undpgeohub" --startup-file "pm2.json"
【 end code 】
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1233134442) by [Unito](https://www.unito.io)
> feat: add pm2.json

- sites/geohub/build-nodemodules.sh
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1233146982) by [Unito](https://www.unito.io)
> fix: Update build-nodemodules.sh to rename pm2 config name

- CONTRIBUTING.md
added PM2 settings in CONTRIBUTING.md
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1233221032) by [Unito](https://www.unito.io)
> doc: add pm2 setting in CONTRIBUTING.md

- .github/workflows/static-api.yml
I did stupid mistake
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1233288020) by [Unito](https://www.unito.io)
> fix: context path for static api ci

- sites/geohub/src/routes/(app)/+page.svelte
Inpired by the last meeting about designing, I slightly changed home page's button color. I applied different color to buttons other than using same primary color.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1233816393) by [Unito](https://www.unito.io)
> Redisign homepage

- .changeset/five-lies-cheer.md
- sites/geohub/static/api/swagger/spec.yaml
Add proposed endpoints for default layer style feature into swagger
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1234678521) by [Unito](https://www.unito.io)
> doc: add new default style endpoint in swagger (WIP)

- .changeset/gold-monkeys-move.md
- .changeset/smooth-forks-notice.md
- sites/geohub/src/components/pages/data/datasets/PublishedDatasetOperations.svelte
- sites/geohub/src/lib/config/AppConfig/FooterItems.ts
closes #2054 
closes #2053
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1234697225) by [Unito](https://www.unito.io)
> fix: disable edit page link and added static api link in footer

- .changeset/calm-peaches-kiss.md
- sites/geohub/src/components/header/UserAccount.svelte
closes #2068
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1235368092) by [Unito](https://www.unito.io)
> fix: only show user icon in header

- .changeset/moody-crabs-juggle.md
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1235381967) by [Unito](https://www.unito.io)
> fix: file selected using select button failure to upload

- .changeset/nervous-humans-kick.md
- sites/geohub/src/routes/(app)/+page.svelte
closes #2066
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1235433782) by [Unito](https://www.unito.io)
> fix: redesign home page

- .changeset/hot-points-exist.md
- sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasets.svelte
- sites/geohub/src/routes/(app)/data/+page.svelte
closes #2081 
Added the number of datasets in tabs
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1235760845) by [Unito](https://www.unito.io)
> feat: show total count in tab at data page

- .changeset/short-mirrors-shout.md
- sites/geohub/src/routes/+layout.server.ts
- sites/geohub/src/routes/+layout.svelte
closes #2084 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1236058388) by [Unito](https://www.unito.io)
> fix: avoid accessing  store inside <svelte:head> in server side. Move d some variables to load function in +layout.server.ts

- .changeset/brown-bottles-switch.md
- sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
- sites/geohub/src/components/util/SdgCard.svelte
- sites/geohub/src/components/util/SdgPicker.svelte
- sites/geohub/src/routes/(app)/data/publish/+page.svelte
I made refactroing sdg picker
also removed shadow from sdg picker to fit other buttons' design
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1236108236) by [Unito](https://www.unito.io)
> refactor: sdg picker

- .changeset/popular-lies-shave.md
- .changeset/rare-plums-ring.md
- packages/svelte-undp-design/src/lib/MultiSelect/MultiSelect.stories.ts
- packages/svelte-undp-design/src/lib/MultiSelect/MultiSelect.svelte
- packages/svelte-undp-design/src/lib/css/multi-select.min.css
- packages/svelte-undp-design/src/lib/index.ts
- packages/svelte-undp-design/src/lib/interfaces/MultiSelect.ts
- packages/svelte-undp-design/src/lib/interfaces/index.ts
- sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
- sites/geohub/src/components/util/CountryCard.svelte
- sites/geohub/src/components/util/CountryPicker.svelte
- sites/geohub/src/components/util/SdgCard.svelte
- sites/geohub/src/routes/(app)/data/publish/+page.server.ts
- sites/geohub/src/routes/(app)/data/publish/+page.svelte
- sites/geohub/src/routes/(app)/data/publish/+page.ts
closes #2080
* added CountryPicker in data page
* added MultiSelect component in undp design (it is not used, I gave up using because of several issues)
* fixed several bugs related to country picker in publish page
* fixed filckering in SDG picker and country picker
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1236387558) by [Unito](https://www.unito.io)
> feat: add country picker to data

- .changeset/lemon-bottles-grin.md
- packages/svelte-undp-design/src/lib/DefaultLink/DefaultLink.stories.ts
- packages/svelte-undp-design/src/lib/DefaultLink/DefaultLink.svelte
- sites/geohub/src/routes/(app)/data/supported-formats/+page.svelte
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1236386517) by [Unito](https://www.unito.io)
> refactor: add DefaultLink openInNewTab option

- sites/geohub/src/routes/(app)/data/supported-formats/+page.svelte
Fixes #2079
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1236862090) by [Unito](https://www.unito.io)
> fix: use tags to show extension

- .github/workflows/ci.yml
* created new environments for svelte UNDP design and Userguide
* moved secrets to environments
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1236847079) by [Unito](https://www.unito.io)
> chore: created environment for svelte undp design and userguide

- sites/geohub/src/lib/config/AppConfig/AcceptedExtensions.ts
- sites/geohub/src/routes/(app)/data/supported-formats/+page.svelte
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1237144492) by [Unito](https://www.unito.io)
> fix: supported formats shapefiles show difference between required and non required

- sites/geohub/src/routes/(app)/settings/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1238111927) by [Unito](https://www.unito.io)
> fix: bug of classification method selectbox in settings page

- .changeset/silly-houses-ring.md
- sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
- sites/geohub/src/components/pages/data/datasets/PublishedDataset.svelte
- sites/geohub/src/components/pages/data/datasets/RasterBandSelectbox.svelte
- sites/geohub/src/components/pages/map/data/DataCard.svelte
- sites/geohub/src/lib/RasterTileData.ts
- sites/geohub/src/lib/VectorTileData.ts
- sites/geohub/src/lib/helper/getDefaultLayerStyle.ts
closes #2109
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1237965804) by [Unito](https://www.unito.io)
> feat: show raster legend in style edit page.

- .changeset/brave-tools-marry.md
- sites/geohub/src/components/maplibre/vector/VectorClassifyLegend.svelte
- sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
- sites/geohub/src/components/pages/data/datasets/PublishedDatasetOperations.svelte
closes #2116
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1238683050) by [Unito](https://www.unito.io)
> feat: add styleedit page link

- .changeset/yellow-donuts-tickle.md
- sites/geohub/src/components/util/ColorMapPicker.svelte
- sites/geohub/src/components/util/ColorMapPickerCard.svelte
- sites/geohub/src/components/util/ColorMapPickerCard.test.ts
closes #2113
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1238741453) by [Unito](https://www.unito.io)
> fix: removed color map name from colormap picker

- .changeset/nice-pans-decide.md
- sites/geohub/src/components/util/DataPreviewContent.svelte
- sites/geohub/src/lib/RasterTileData.ts
- sites/geohub/src/routes/(app)/data/publish/+page.svelte
closes #1708
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1239231417) by [Unito](https://www.unito.io)
> feat: relayout publish page

- .changeset/chilly-pugs-heal.md
- sites/geohub/src/components/maplibre/raster/RasterClassifyLegend.svelte
- sites/geohub/src/components/maplibre/vector/VectorClassifyLegend.svelte
- sites/geohub/src/components/pages/map/layers/header/Legend.svelte
- sites/geohub/src/components/util/ColorMapPicker.svelte
- sites/geohub/src/components/util/ColorMapPickerCard.svelte
- sites/geohub/src/lib/colormaps.ts
- sites/geohub/src/lib/helper/generateColorMap.ts
closes #2112
added reverse colormap feature
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1240154547) by [Unito](https://www.unito.io)
> feat: reverse colormap

- .changeset/chilly-pugs-heal.md
- sites/geohub/CHANGELOG.md
- sites/geohub/package.json
- sites/geohub/src/components/maplibre/raster/RasterClassifyLegend.svelte
- sites/geohub/src/components/maplibre/vector/VectorClassifyLegend.svelte
- sites/geohub/src/components/pages/map/layers/header/Legend.svelte
- sites/geohub/src/components/util/ColorMapPicker.svelte
- sites/geohub/src/components/util/ColorMapPickerCard.svelte
- sites/geohub/src/lib/colormaps.ts
- sites/geohub/src/lib/helper/generateColorMap.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1240181083) by [Unito](https://www.unito.io)
> chore: merge develop to main

- .changeset/heavy-seals-join.md
- sites/geohub/src/lib/server/helpers/getStyleById.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1240296448) by [Unito](https://www.unito.io)
> fix: skip updating dataset properties if the dataset feature does not exist at /api/style endpoint

- .changeset/wet-boxes-rush.md
- sites/geohub/src/components/pages/home/MapStyleCard.svelte
- sites/geohub/src/components/pages/map/plugins/StyleShare.svelte
- sites/geohub/src/routes/api/style/+server.ts
- sites/geohub/src/routes/api/style/[id]/+server.ts
closes #2138
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1240329508) by [Unito](https://www.unito.io)
> feat: superuser to update / delete style

- .changeset/hot-emus-flow.md
- sites/geohub/src/routes/(app)/data/supported-formats/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1240374961) by [Unito](https://www.unito.io)
> feat: improve supported format page

- .github/workflows/release.yml
I saw the log in CI that looks like creating new branch from main branch (I set base as main), and it says there is no ahead of changes.
Let me just try set base to develop and checkout from main
【 code  】
From https://github.com/UNDP-Data/geohub
* [new branch]        main       -> main
* [new branch]        main       -> origin/main
/usr/bin/git checkout --progress main --
Switched to branch 'main'
/usr/bin/git rev-list --reverse develop..95f778b4-ec61-4044-ba12-0dabc7a7abf4 .
/usr/bin/git checkout --progress -B 95f778b4-ec61-4044-ba12-0dabc7a7abf4 HEAD --
Switched to and reset branch '95f778b4-ec61-4044-ba12-0dabc7a7abf4'
/usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --force origin main:main
/usr/bin/git -c …
> fix: changed main to ref and base to develop

- .changeset/dirty-baboons-develop.md
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1240784841) by [Unito](https://www.unito.io)
> fix: show-tags-of-present-files-for-shapefiles

- .changeset/gorgeous-guests-travel.md
- sites/geohub/src/components/maplibre/symbol/IconImagePicker.svelte
- sites/geohub/src/components/pages/map/data/DataCardInfo.svelte
- sites/geohub/src/components/pages/map/layers/header/DataCardInfoMenu.svelte
- sites/geohub/src/components/util/ColorMapPicker.svelte
* refactor: Use bulma's tab and close icon css for ColorMapPicker, IconImagePicker and DataCardInfoMenu
* refactor: Use display grid for IconImagePicker
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1240971526) by [Unito](https://www.unito.io)
> refactor: IconImagePicker and ColorMapPicker

- .changeset/beige-snakes-kick.md
- .changeset/gold-impalas-sip.md
- sites/geohub/src/components/maplibre/MaplibreColorPicker.svelte
- sites/geohub/src/components/maplibre/OpacitySlider.svelte
- sites/geohub/src/components/maplibre/OptionalPropertyEditor.svelte
- sites/geohub/src/components/maplibre/heatmap/HeatmapColor.svelte
- sites/geohub/src/components/maplibre/heatmap/HeatmapColorRow.svelte
- sites/geohub/src/components/maplibre/heatmap/VectorHeatmap.svelte
- sites/geohub/src/components/maplibre/line/VectorLine.svelte
- sites/geohub/src/components/maplibre/raster/RasterPropertyEditor.svelte
- sites/geohub/src/components/maplibre/symbol/IconImage.svelte
- sites/geohub/src/components/maplibre/symbol/IconSize.svelte
- sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
- sites/geohub/src/components/maplibre/vector/VectorClassifyLegend.svelte
- sites/geohub/src/components/maplibre/vector/VectorLegend.svelte
- sites/geohub/src/components/maplibre/vector/VectorPropertyEditor.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
- sites/geohub/src/components/util/NumberInput.svelte
- sites/geohub/src/components/util/ToggleOptions.svelte
- sites/geohub/src/lib/config/AppConfig/TabNames.ts
- sites/geohub/src/stores/applyToOption.ts
- sites/geohub/src/stores/index.ts
Introduced properties editor popup (like raster one) to vector legend.
moved some minor properties to the popup
* heatmap
* symbol
* line
* fill
no changes
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1241174449) by [Unito](https://www.unito.io)
> feat: introduce vector property popup

- .changeset/beige-parents-doubt.md
- sites/geohub/src/components/pages/data/ingesting/DataUploadButton.svelte
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
Used `goto` method in upload button
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1241605933) by [Unito](https://www.unito.io)
> refactor: use goto function in upload button

- .changeset/serious-insects-give.md
- sites/geohub/src/routes/(app)/data/+page.svelte
closes #2166
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1241615795) by [Unito](https://www.unito.io)
> fix: bug of not updating ingesting dataset count in my data tab in data page

- .changeset/stupid-hornets-hear.md
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
Redesign upload page
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1241946096) by [Unito](https://www.unito.io)
> refactor: redesign upload page

- .changeset/great-trains-float.md
- sites/geohub/src/components/pages/map/layers/raster/RasterHistogram.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/lib/types/BandStatistics.ts
fixes #2184
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1242548010) by [Unito](https://www.unito.io)
> fix: removed overlapped x axis label from histogram.

- .changeset/polite-oranges-smash.md
- .changeset/spicy-news-sparkle.md
- sites/geohub/src/components/maplibre/raster/RasterPropertyEditor.svelte
- sites/geohub/src/components/pages/map/layers/header/HistogramMenu.svelte
- sites/geohub/src/components/pages/map/layers/header/LayerHeader.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/lib/config/AppConfig/TabNames.ts
closes #2192
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1242611234) by [Unito](https://www.unito.io)
> feat: moved histogram tab to layer drop down menu

- .changeset/proud-panthers-scream.md
- sites/geohub/src/components/util/LayerTypeSwitch.svelte
switched radio to select for layer type switcher.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1242981185) by [Unito](https://www.unito.io)
> feat: changed radio button to select box for layer type switcher

- .changeset/green-books-explain.md
- sites/geohub/src/components/maplibre/OptionalPropertyEditor.svelte
- sites/geohub/src/components/maplibre/raster/RasterPropertyEditor.svelte
- sites/geohub/src/components/maplibre/vector/VectorPropertyEditor.svelte
closes #2202
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1243054705) by [Unito](https://www.unito.io)
> feat: group properties in raster/vector popup by accordion (Data or Appearance)

- .changeset/rich-wasps-change.md
- .changeset/twenty-donkeys-smell.md
- packages/svelte-undp-design/src/lib/Accordion/Accordion.svelte
- sites/geohub/src/components/maplibre/OptionalPropertyEditor.svelte
- sites/geohub/src/components/maplibre/circle/VectorCircle.svelte
- sites/geohub/src/components/maplibre/raster/RasterDefaultLegend.svelte
- sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
- sites/geohub/src/components/maplibre/raster/RasterPropertyEditor.svelte
- sites/geohub/src/components/maplibre/vector/VectorPropertyEditor.svelte
- sites/geohub/src/lib/helper/updateParamsInURL.ts
closes #2201
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1243102144) by [Unito](https://www.unito.io)
> feat: add label for colormap

- .changeset/slimy-pandas-do.md
- .changeset/thick-singers-tickle.md
- packages/svelte-undp-design/src/lib/css/stats-cards.min.css
- sites/geohub/src/components/pages/home/ExploreDatasets.svelte
- sites/geohub/src/lib/server/helpers/getDatasetStats.ts
- sites/geohub/src/lib/server/helpers/index.ts
- sites/geohub/src/routes/(app)/+page.server.ts
- sites/geohub/src/routes/(app)/+page.svelte
- sites/geohub/src/routes/api/datasets/stats/+server.ts
- sites/geohub/static/api/swagger/spec.yaml
closes #2215
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1243866150) by [Unito](https://www.unito.io)
> feat: add dataset stats

- sites/geohub/src/routes/(app)/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1243884940) by [Unito](https://www.unito.io)
> fix: adjast layout of oss section

- .changeset/late-fireants-yawn.md
- sites/geohub/src/components/maplibre/vector/VectorColorClassification.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1244674304) by [Unito](https://www.unito.io)
> fix: adjust colorpicker width in color classification component

- .changeset/wet-moles-buy.md
- sites/geohub/src/routes/api/datasets/[id]/style/[layer]/[type]/+server.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1244716420) by [Unito](https://www.unito.io)
> fix: fixed bug of POST/DELETE endpoints to save/delete style

- .changeset/grumpy-cougars-visit.md
- sites/geohub/src/components/maplibre/vector/VectorClassifyLegend.svelte
- sites/geohub/src/components/maplibre/vector/VectorColorClassification.svelte
- sites/geohub/src/lib/helper/checkVectorLayerHighlySkewed.ts
- sites/geohub/src/lib/helper/index.ts
* fix: set logarithmic if the vector layer property has highly skewed values. created a helper function to check highly skewed (`checkVectorLayerHighlySkewed`).
* fix: set random color if the defaultColor variable is undefined when the propoerty is changed in ColorClassification component.
* refactor: removed code for fill from VectorClassifyLegend.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1245009581) by [Unito](https://www.unito.io)
> refactor: remove fill from vectorclassifylegend

- .changeset/modern-queens-cheat.md
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1246692223) by [Unito](https://www.unito.io)
> refactor: vector layer and raster layer to use hidden prop to switch tab

- .changeset/soft-turkeys-provide.md
- sites/geohub/src/components/maplibre/line/VectorLine.svelte
fixes #2241
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1246765017) by [Unito](https://www.unito.io)
> fix: change line width tab icon

- sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1246881719) by [Unito](https://www.unito.io)
> fix: bug of loading RasterTransform component

- .changeset/purple-kangaroos-kneel.md
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/header/LayerHeader.svelte
- sites/geohub/src/components/pages/map/layers/header/VisibilityButton.svelte
* align visibility button and menu button in the right side
* removed legend from header
* toggle layer content by clicking the entire header
* stop using panel of bulma
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1246917736) by [Unito](https://www.unito.io)
> feat: improved layer layout

- .changeset/lovely-flies-vanish.md
- .changeset/ninety-llamas-design.md
- packages/undp-bulma/bulma.scss
- sites/geohub/src/components/maplibre/LegendTypeSwitcher.svelte
- sites/geohub/src/components/maplibre/line/VectorLine.svelte
- sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
- sites/geohub/src/components/maplibre/vector/VectorLegend.svelte
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/header/LayerHeader.svelte
- sites/geohub/src/components/pages/map/layers/header/VisibilityButton.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1247285681) by [Unito](https://www.unito.io)
> fix: adjust desigin of layer header and tabs

- .changeset/spotty-spies-wait.md
- packages/undp-bulma/bulma.scss
- packages/undp-bulma/index.html
- packages/undp-bulma/src/main.ts
- sites/geohub/src/components/util/NumberInput.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1247345408) by [Unito](https://www.unito.io)
> fix: apply UNDP design style for UNDP input

- .changeset/long-apricots-enjoy.md
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/order/LayerOrderPanelButton.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
- sites/geohub/src/lib/types/Layer.ts
- sites/geohub/src/stores/layerList.ts
closes #2246 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1247376807) by [Unito](https://www.unito.io)
> feat: expand/collapse all

- .changeset/witty-eagles-approve.md
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/header/VisibilityButton.svelte
closes #2247
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1247648291) by [Unito](https://www.unito.io)
> feat: add show only this layer menu in the dropdown

- .changeset/heavy-hornets-chew.md
- .changeset/witty-dolphins-flow.md
- sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
- sites/geohub/src/components/util/AccessLevelSwitcher.svelte
fixes #2264
fixes #2265
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1249859731) by [Unito](https://www.unito.io)
> fix: bug of RasterLegend to switch colormap

- .changeset/sharp-wolves-promise.md
- sites/geohub/src/components/pages/map/Content.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1250424519) by [Unito](https://www.unito.io)
> fix:fix scrollbar in content

- .changeset/great-peaches-compete.md
- sites/geohub/src/components/maplibre/LegendColorMapRow.svelte
- sites/geohub/src/components/maplibre/line/LineWidth.svelte
- sites/geohub/src/components/maplibre/raster/RasterClassifyLegend.svelte
- sites/geohub/src/components/maplibre/vector/VectorColorClassification.svelte
- sites/geohub/src/components/maplibre/vector/VectorValueClassification.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1250570954) by [Unito](https://www.unito.io)
> feat: add table header and fixed position against scrolling content

- .changeset/cold-grapes-develop.md
- sites/geohub/src/components/pages/map/Content.svelte
- sites/geohub/src/components/util/Tabs.svelte
Improved styling of tabs
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1251265388) by [Unito](https://www.unito.io)
> fix: improve tab styling

- .changeset/tough-humans-speak.md
- sites/geohub/src/components/maplibre/OptionalPropertyEditor.svelte
fixes #2290. I think placement: auto works fine
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1251415657) by [Unito](https://www.unito.io)
> fix: chagned placement from right to auto for property editor

- .changeset/metal-tips-invent.md
- sites/geohub/src/components/maplibre/symbol/PropertySelect.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1251425773) by [Unito](https://www.unito.io)
> fix: removed margin-right from property select component

- sites/geohub/src/components/pages/map/layers/vector/VectorLabelPanel.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1252120470) by [Unito](https://www.unito.io)
> fix: renamed general to font for label tab

- .changeset/friendly-planes-turn.md
- .changeset/unlucky-baboons-wink.md
- sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRowDetail.svelte
- sites/geohub/src/components/pages/home/ExploreDatasets.svelte
- sites/geohub/src/components/util/CountryPicker.svelte
- sites/geohub/src/components/util/SdgPicker.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1252265040) by [Unito](https://www.unito.io)
> feat: add satellite menu

- .changeset/calm-dolphins-own.md
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1252277136) by [Unito](https://www.unito.io)
> fix: show error messages correctly on fileRejections

- .changeset/old-rockets-pump.md
- sites/geohub/src/components/pages/map/layers/raster/RasterTransform.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte
- sites/geohub/src/lib/types/RasterExpression.ts
fixes #1019 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1252327749) by [Unito](https://www.unito.io)
> fix: restore raster simple expression

- .github/workflows/ci.yml
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1252862101) by [Unito](https://www.unito.io)
> fix: namespace of ci for pipeline

- .github/workflows/bump-pipeline.yml
- backends/k8s/data-pipeline/bump-version.sh
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1252956743) by [Unito](https://www.unito.io)
> fixed bump ci

- .changeset/happy-lemons-tease.md
- packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1253127665) by [Unito](https://www.unito.io)
> fix: minor inprovements of breadcrumbs styles

- packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.svelte
- packages/svelte-undp-design/src/lib/Checkbox/Checkbox.svelte
- packages/svelte-undp-design/src/lib/DefaultLink/DefaultLink.svelte
- packages/svelte-undp-design/src/lib/Footer/Footer.svelte
- packages/svelte-undp-design/src/lib/Tabs/Tabs.svelte
- packages/svelte-undp-design/src/lib/TextInput/TextInput.svelte
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
- sites/geohub/src/components/pages/home/MapStyleCardList.svelte
- sites/geohub/src/routes/(app)/data/supported-formats/+page.svelte
- sites/geohub/src/routes/api/datasets/ingesting/+server.ts
- sites/geohub/src/routes/api/style/+server.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1253898321) by [Unito](https://www.unito.io)
> chore: format by prettier

- pnpm-lock.yaml
- sites/geohub/package.json
Since auth.js released new version after fixing the bug, I am going to upgrade auth.js version
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1254788707) by [Unito](https://www.unito.io)
> chore: upgrade auth.js

- .changeset/healthy-planets-serve.md
- sites/geohub/src/components/pages/data/datasets/PublishedDataset.svelte
- sites/geohub/src/components/pages/data/datasets/PublishedDatasetHeader.svelte
- sites/geohub/src/components/pages/data/datasets/PublishedDatasetRow.svelte
- sites/geohub/src/components/util/SdgCard.svelte
- sites/geohub/src/lib/config/AppConfig/SdgLogos.ts
- sites/geohub/src/lib/config/AppConfig/index.ts
fixes #2339 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1257376119) by [Unito](https://www.unito.io)
> fix: show just SDG number with circle and color instead of SDG logo in dataset table. If SDGs are more than three, it will show ... to popup

- .changeset/soft-eagles-cry.md
- sites/geohub/src/components/pages/data/datasets/PublishedDatasetRow.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1257803348) by [Unito](https://www.unito.io)
> fix: adjust the layout of SDG circle mark for public dataset table

- .changeset/curly-ghosts-perform.md
- .changeset/healthy-dingos-jog.md
- .changeset/honest-cameras-explain.md
- packages/svelte-undp-design/src/lib/Card/Card.stories.ts
- packages/svelte-undp-design/src/lib/Card/Card.svelte
- packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.stories.ts
- packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.svelte
- packages/svelte-undp-design/src/lib/css/content-card.min.css
- packages/svelte-undp-design/src/lib/index.ts
- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/components/pages/data/datasets/CardView.svelte
- sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
- sites/geohub/src/routes/api/datasets/[id]/preview/[bbox]/[width]x[height].[format]/+server.ts
- sites/geohub/src/routes/api/datasets/[id]/preview/[lon],[lat],[zoom],[bearing],[pitch]/[width]x[height].[format]/+server.ts
- sites/geohub/src/routes/api/datasets/[id]/preview/auto/[width]x[height].[format]/+server.ts
- sites/geohub/src/routes/api/datasets/[id]/preview/style.json/+server.ts
- sites/geohub/static/api/swagger/spec.yaml
closes #2340
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1258039008) by [Unito](https://www.unito.io)
> feat: add CardView in data page

- .changeset/rare-squids-beg.md
- packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.stories.ts
- packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.svelte
- sites/geohub/src/components/pages/data/datasets/CardView.svelte
- sites/geohub/src/routes/api/datasets/[id]/preview/auto/[width]x[height].[format]/+server.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1258087974) by [Unito](https://www.unito.io)
> fix: show loader in CardWithImage. also missed /(slash) in GET method

- .changeset/wise-garlics-flow.md
- sites/geohub/src/routes/api/datasets/[id]/preview/[bbox]/[width]x[height].[format]/+server.ts
- sites/geohub/src/routes/api/datasets/[id]/preview/[lon],[lat],[zoom],[bearing],[pitch]/[width]x[height].[format]/+server.ts
- sites/geohub/src/routes/api/datasets/[id]/preview/auto/[width]x[height].[format]/+server.ts
- sites/geohub/src/routes/api/datasets/[id]/preview/style.json/+server.ts
- sites/static-image-api/src/lib/server/renderMap.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1258174985) by [Unito](https://www.unito.io)
> fix: fixed static API to create empty response if tile is missing in PMTiles source

- .changeset/famous-poems-dance.md
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasetHeader.svelte
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRowDetail.svelte
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasets.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1258770749) by [Unito](https://www.unito.io)
> fix: improved ingesting table design

- .changeset/purple-pans-flow.md
- sites/geohub/src/routes/(app)/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1258987152) by [Unito](https://www.unito.io)
> feat: Use Card component for the home page

- .changeset/beige-lemons-argue.md
- sites/geohub/src/components/pages/map/data/DataView.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1259117335) by [Unito](https://www.unito.io)
> fix: fixed bug of not showing home icon in breadcrumbs

- .changeset/strange-goats-fail.md
- packages/svelte-undp-design/src/lib/Card/Card.svelte
- sites/geohub/src/routes/(app)/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1259532997) by [Unito](https://www.unito.io)
> fix: hide content tag in Card if tag variable is empty string

- .changeset/mighty-beers-rest.md
- .changeset/strong-yaks-ring.md
- sites/geohub/src/components/pages/data/datasets/PublishedDataset.svelte
- sites/geohub/src/components/pages/map/data/DataCard.svelte
- sites/geohub/src/lib/RasterTileData.ts
- sites/geohub/src/lib/config/AppConfig/MapStyles.ts
- sites/geohub/src/lib/helper/getFirstSymbolLayerId.ts
- sites/geohub/src/lib/helper/index.ts
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
- sites/geohub/src/routes/(app)/management/stac/api/[id]/[collection]/+page.svelte
- sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte
fixes #2366
This PR is going to upgrade base map style to v1.1.1. This can fix bug of #2366 and a part of #2369
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1259584915) by [Unito](https://www.unito.io)
> refactor: get first symbol layer and update base style version to v1.1.1

- .changeset/real-hornets-flash.md
- sites/geohub/src/components/util/stac/StacCollectionMap.svelte
- sites/geohub/src/lib/types/TableViewType.ts
* added list view in STAC catalog explorer because some of collection/item are overlapped on the map, list view can be helpful somehow
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1260556651) by [Unito](https://www.unito.io)
> fix: fixed several bugs in STAC catalog explorer. Furthermore, added list view.

- renovate.json
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1260581421) by [Unito](https://www.unito.io)
> chore: removed groupnonmajor setting from renovate.json

- .changeset/fuzzy-radios-hide.md
- .changeset/heavy-hairs-perform.md
- .changeset/lovely-vans-pump.md
- sites/geohub/src/components/pages/home/MapStyleCardList.svelte
- sites/geohub/src/components/pages/map/Map.svelte
- sites/geohub/src/components/pages/map/plugins/LayerVisibilitySwitcher.svelte
- sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
- sites/geohub/src/components/util/Star.svelte
- sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
- sites/geohub/src/routes/(map)/maps/+layout.svelte
- sites/geohub/src/stores/layerList.ts
* renamed edit button to open button and align right
* made buttons larger at maps/{id} page
* add map query tool at /maps/{id} page
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1261361053) by [Unito](https://www.unito.io)
> fix: map page layout

- .changeset/funny-shrimps-grow.md
- sites/geohub/src/components/maplibre/symbol/TextField.svelte
- sites/geohub/src/components/maplibre/symbol/TextFieldDecimalPosition.svelte
- sites/geohub/src/components/pages/map/Content.svelte
- sites/geohub/src/components/pages/map/Map.svelte
- sites/geohub/src/components/pages/map/data/DataCard.svelte
- sites/geohub/src/components/pages/map/data/DataVectorCard.svelte
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/header/DeleteMenu.svelte
- sites/geohub/src/components/pages/map/layers/header/VisibilityButton.svelte
- sites/geohub/src/components/pages/map/layers/order/LayerOrderPanelButton.svelte
- sites/geohub/src/components/pages/map/layers/order/SortLayer.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorParamsPanel.svelte
- sites/geohub/src/components/pages/map/plugins/StyleShare.svelte
- sites/geohub/src/components/pages/map/plugins/StyleShareControl.svelte
- sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
- sites/geohub/src/routes/(map)/maps/+layout.svelte
- sites/geohub/src/stores/layerList.ts
fixes #2010
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1261930354) by [Unito](https://www.unito.io)
> refactor: switch layerList store from global variable to ContextAPI

- .changeset/fifty-suits-hide.md
- sites/geohub/src/components/pages/data/datasets/PublishedDataset.svelte
fixes #2422
I also fixed a behaviour, now a layer will not be added to any saved existing map stored in local storage.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1261939251) by [Unito](https://www.unito.io)
> fix: fixed the link to maps page from /data/{id} page

- .changeset/early-tools-occur.md
- sites/geohub/src/lib/config/AppConfig/FooterItems.ts
- sites/geohub/src/lib/config/AppConfig/HeaderItems.ts
- sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
fixes #2423
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1261954337) by [Unito](https://www.unito.io)
> fix: removed attribution from /maps/{id} page

- .changeset/two-zoos-kneel.md
- sites/geohub/src/components/maplibre/LegendColorMapRow.svelte
- sites/geohub/src/components/maplibre/MaplibreColorPicker.svelte
- sites/geohub/src/components/maplibre/circle/CircleRadius.svelte
- sites/geohub/src/components/maplibre/circle/VectorCircle.svelte
- sites/geohub/src/components/maplibre/heatmap/HeatmapColor.svelte
- sites/geohub/src/components/maplibre/heatmap/HeatmapColorRow.svelte
- sites/geohub/src/components/maplibre/raster/RasterClassifyLegend.svelte
- sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
- sites/geohub/src/components/maplibre/symbol/IconImage.svelte
- sites/geohub/src/components/maplibre/symbol/PropertySelect.svelte
- sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
- sites/geohub/src/components/maplibre/vector/VectorColorClassification.svelte
- sites/geohub/src/components/maplibre/vector/VectorLegend.svelte
- sites/geohub/src/components/maplibre/vector/VectorValueClassification.svelte
- sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/header/VisibilityButton.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
- sites/geohub/src/components/pages/map/plugins/MaplibreLegendControl.svelte
- sites/geohub/src/components/util/ColorMapPicker.svelte
- sites/geohub/src/components/util/NumberInput.svelte
- sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
- sites/geohub/src/stores/index.ts
- sites/geohub/src/stores/legendReadonly.ts
fixes #2418
readonly state is referred through legendreadonly store & context api.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1262100404) by [Unito](https://www.unito.io)
> feat: add floating readonly legend at /maps/{id} page

- sites/static-image-api/package-lock.json
- sites/static-image-api/package.json
- sites/static-image-api/src/app.html
- sites/static-image-api/src/routes/(app)/+layout.svelte
- sites/static-image-api/src/routes/(app)/+page.svelte
- sites/static-image-api/src/routes/(app)/playground/+page.svelte
- sites/static-image-api/src/routes/api/og/+server.ts
- sites/static-image-api/src/routes/api/style/static/[bbox]/[width]x[height].[format]/+server.ts
- sites/static-image-api/src/routes/api/style/static/[lon],[lat],[zoom],[bearing],[pitch]/[width]x[height].[format]/+server.ts
- sites/static-image-api/src/routes/api/style/static/auto/[width]x[height].[format]/+server.ts
- sites/static-image-api/static/api/swagger/spec.yaml
also, added x3 and x4 for ratio
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1262912953) by [Unito](https://www.unito.io)
> fix: use new export plugin for static image api playground

- .changeset/tidy-lemons-pull.md
- sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
- sites/geohub/src/components/pages/data/datasets/CardView.svelte
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
- sites/geohub/src/components/pages/home/MapStyleCardList.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/routes/(app)/data/supported-formats/+page.svelte
- sites/geohub/src/routes/(map)/dashboards/electricity/+page.ts
- sites/geohub/src/routes/(map)/maps/+layout.svelte
- sites/geohub/src/routes/(map)/maps/+page.svelte
- sites/geohub/src/routes/(map)/maps/+page.ts
- sites/geohub/src/routes/(map)/maps/[id]/+page.ts
- sites/geohub/src/routes/(map)/maps/[id]/edit/+page.svelte
- sites/geohub/src/routes/(map)/maps/[id]/edit/+page.ts
- sites/geohub/src/routes/api/datasets/ingesting/+server.ts
* fixed bug of layer header
* also turned SSR on 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1265537064) by [Unito](https://www.unito.io)
> fix: layer header layout

- sites/geohub/src/routes/(map)/dashboards/electricity/+page.ts
- sites/geohub/src/routes/(map)/maps/+page.ts
- sites/geohub/src/routes/(map)/maps/[id]/+page.ts
- sites/geohub/src/routes/(map)/maps/[id]/edit/+page.ts
revert ssr to csr
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1265557402) by [Unito](https://www.unito.io)
> Revert ssr

- .changeset/curly-bulldogs-melt.md
- sites/geohub/src/components/util/MapSidebar.svelte
add animation for sidebar button
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1265782725) by [Unito](https://www.unito.io)
> feat: arrow animation

- .changeset/selfish-dancers-wink.md
- sites/geohub/src/components/pages/map/Map.svelte
fixes #2448
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1265793613) by [Unito](https://www.unito.io)
> fix: fixed zindex for map progress bar and refactored the code

- .changeset/big-ads-shave.md
- sites/geohub/src/routes/api/datasets/+server.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1265896486) by [Unito](https://www.unito.io)
> fix: fixed bug of /datasets api. removed next link if it is the last page

- .github/workflows/bump-cogserver.yml
- backends/k8s/cogserver/yaml/cogserver-deployment.yaml
- packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.svelte
- packages/svelte-undp-design/src/lib/Footer/Footer.svelte
- packages/svelte-undp-design/src/lib/Tabs/Tabs.svelte
- sites/geohub/src/components/maplibre/line/LinePattern.svelte
- sites/geohub/src/components/pages/data/datasets/CardView.svelte
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
- sites/geohub/src/components/pages/home/MapStyleCardList.svelte
- sites/geohub/src/components/util/stac/StacCollectionMap.svelte
- sites/geohub/src/routes/(app)/data/supported-formats/+page.svelte
- sites/geohub/src/routes/api/countries/+server.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1265924750) by [Unito](https://www.unito.io)
> Fix cogserver

- .github/workflows/bump-cogserver.yml
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1266253542) by [Unito](https://www.unito.io)
> fix cogserver image name in cicd bump script

- .github/workflows/bump-cogserver.yml
- .github/workflows/ci.yml
- backends/k8s/cogserver/yaml/cogserver-deployment.yaml
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1266767545) by [Unito](https://www.unito.io)
> mode back deployment to ci.yml

- .changeset/good-parrots-own.md
- sites/geohub/src/components/util/stac/StacCatalogCollections.svelte
- sites/geohub/src/components/util/stac/StacCatalogExplorer.svelte
- sites/geohub/src/components/util/stac/StacCatalogMap.svelte
- sites/geohub/src/components/util/stac/StacCollectionMap.svelte
- sites/geohub/src/lib/server/helpers/createMosaicDataSetFeature.ts
- sites/geohub/src/lib/server/helpers/index.ts
- sites/geohub/src/routes/api/stac/[id]/[collection]/[...item]/[asset]/+server.ts
- sites/geohub/src/routes/api/stac/catalog/[id]/item/+server.ts
- sites/geohub/static/api/swagger/spec.yaml
closes #2378
* add `scene` / `mosaic` selector in STAC catalog explorer if it reaches item level
* create mosaicjson for selected items
* /stac/catalog/{id}/item endpoint now can receive multiple `url` values, if multiple URLs, will return mosaicjson
* moved mosaicjson creation functions to helper
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1266860951) by [Unito](https://www.unito.io)
> feat: stac catalog mosaicjson

- .github/workflows/ci.yml
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1267306021) by [Unito](https://www.unito.io)
> add cogserver to changes step

- .changeset/poor-jobs-speak.md
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/util/stac/StacCatalogExplorer.svelte
- sites/geohub/src/components/util/stac/StacCatalogMap.svelte
- sites/geohub/src/components/util/stac/StacCollectionMap.svelte
* fixed bug to show mosaic for jaxa dataset
* adjusted header layout of stac catalog explorer
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1267344963) by [Unito](https://www.unito.io)
> fix: jaxa mosaic

- backends/k8s/cogserver/yaml/cogserver-deployment.yaml
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1267379403) by [Unito](https://www.unito.io)
> set cogserver image to main

- backends/k8s/pgtileserv/yaml/pgtileserv-deployment.yaml
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1267450819) by [Unito](https://www.unito.io)
> set tag to a working image version because of a bug

- .github/workflows/ci.yml
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1267489584) by [Unito](https://www.unito.io)
> create pgtileserv namespace if it does not exist

- .github/workflows/ci.yml
let us try to deploy pgtileserv-deployment.yml first, then delete/create secrets. I think this can work.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1267504384) by [Unito](https://www.unito.io)
> fix: pg_tileserv deployment in CI

- .changeset/healthy-items-beam.md
- .changeset/popular-deers-tan.md
- .changeset/sour-seahorses-tap.md
- packages/svelte-sidebar/src/lib/Sidebar.svelte
- packages/svelte-sidebar/src/routes/+page.svelte
- packages/svelte-static-image-controls/src/lib/MaplibreStaticImageControl.svelte
- sites/geohub/src/components/pages/map/Map.svelte
- sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
- sites/geohub/src/components/pages/map/plugins/StyleShareControl.svelte
- sites/geohub/src/lib/config/AppConfig/TourOptions.ts
fixes #2512
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1268209969) by [Unito](https://www.unito.io)
> fix: sidebar icon design

- .changeset/mean-ducks-thank.md
- .changeset/unlucky-nails-judge.md
- packages/svelte-undp-design/src/lib/css/country-site-header.min.css
- packages/undp-bulma/bulma.scss
- packages/undp-bulma/src/main.ts
- sites/geohub/src/components/pages/map/Content.svelte
- sites/geohub/src/components/util/Tabs.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1268269201) by [Unito](https://www.unito.io)
> fix: tab color and UNDP header

- .changeset/curly-dolphins-nail.md
- .changeset/eleven-bees-live.md
- sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
- sites/geohub/src/components/pages/map/data/DataView.svelte
- sites/geohub/src/components/pages/map/data/TextFilter.svelte
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/components/pages/map/layers/order/LayerOrderPanelButton.svelte
- sites/geohub/src/components/util/PanelButton.svelte
- sites/geohub/src/routes/(map)/maps/+layout.server.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1268324272) by [Unito](https://www.unito.io)
> fix: remove breadcrumb icon and remove border from panel buttons

- backends/k8s/cogserver/yaml/cogserver-deployment.yaml
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1268530149) by [Unito](https://www.unito.io)
> change port and cert provider

- .changeset/tiny-penguins-sing.md
- sites/geohub/src/components/header/UserAccount.svelte
fixed the position of user info popup, also removed `azure-ad` from signout method
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1272063149) by [Unito](https://www.unito.io)
> fix: fixed position of user info popup

- .changeset/angry-carrots-explode.md
- .changeset/honest-tools-melt.md
- .changeset/rotten-badgers-rest.md
- .changeset/spicy-tables-jam.md
- .changeset/warm-chicken-push.md
- sites/geohub/src/components/maplibre/LegendColorMapRow.svelte
- sites/geohub/src/components/maplibre/circle/VectorCircle.svelte
- sites/geohub/src/components/maplibre/fill-extrusion/VectorFillExtrusion.svelte
- sites/geohub/src/components/maplibre/fill/VectorPolygon.svelte
- sites/geohub/src/components/maplibre/line/VectorLine.svelte
- sites/geohub/src/components/maplibre/raster/RasterSimpleLegend.svelte
- sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
- sites/geohub/src/components/maplibre/vector/VectorColorClassification.svelte
- sites/geohub/src/components/maplibre/vector/VectorSimpleColorLegend.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/header/VisibilityButton.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
- sites/geohub/src/lib/config/AppConfig/TabNames.ts
fixes #2541
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1273298169) by [Unito](https://www.unito.io)
> fix: improved vector simple legend

- .changeset/eleven-planes-tease.md
- sites/geohub/src/lib/config/AppConfig/MapStyles.ts
fixes #2556
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1273303622) by [Unito](https://www.unito.io)
> fix: Update style json version to 1.2.1

- .changeset/short-bugs-fetch.md
- sites/geohub/src/hooks.server.ts
- sites/geohub/src/routes/+layout.server.ts
- sites/geohub/src/routes/api/datasets/+server.ts
- sites/geohub/src/routes/api/datasets/[id]/+server.ts
- sites/geohub/src/routes/api/datasets/[id]/preview/style.json/+server.ts
- sites/geohub/src/routes/api/datasets/[id]/style/[layer]/[type]/+server.ts
- sites/geohub/src/routes/api/stac/+server.ts
- sites/geohub/src/routes/api/stac/[id]/+server.ts
- sites/geohub/src/routes/api/style/+server.ts
- sites/geohub/src/routes/api/style/[id].json/+server.ts
- sites/geohub/src/routes/api/style/[id]/+server.ts
- sites/geohub/src/routes/api/style/[id]/static/[bbox]/[width]x[height].[format]/+server.ts
- sites/geohub/src/routes/api/style/[id]/static/[lon],[lat],[zoom],[bearing],[pitch]/[width]x[height].[format]/+server.ts
- sites/geohub/src/routes/api/style/[id]/static/auto/[width]x[height].[format]/+server.ts
- sites/geohub/src/routes/api/tags/+server.ts
…er.ts (pages) and server.ts (API)
I found there are often postgres error from +hooks.server.ts caused by calling is_superuser function. I moved is_superuser function to +layout.server.ts or +server.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1273324242) by [Unito](https://www.unito.io)
> fix: moved is_superuser function from +hook.server.ts to +layout.server.ts (pages) and server.ts (API)

- .changeset/old-jobs-double.md
- sites/geohub/src/components/maplibre/circle/VectorCircle.svelte
- sites/geohub/src/components/maplibre/fill-extrusion/VectorFillExtrusion.svelte
- sites/geohub/src/components/maplibre/fill/VectorPolygon.svelte
- sites/geohub/src/components/maplibre/heatmap/VectorHeatmap.svelte
- sites/geohub/src/components/maplibre/line/VectorLine.svelte
- sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
- sites/geohub/src/components/maplibre/vector/VectorLegend.svelte
- sites/geohub/src/components/maplibre/vector/VectorParamsPanel.svelte
- sites/geohub/src/components/maplibre/vector/VectorSimulationAccordion.svelte
- sites/geohub/src/components/pages/map/layers/LayerEdit.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
- sites/geohub/src/lib/config/AppConfig/TabNames.ts
- sites/geohub/src/lib/config/AppConfig/TourOptions.ts
- sites/geohub/src/routes/(app)/management/+layout.server.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1273399293) by [Unito](https://www.unito.io)
> fix: moved simulation tab to Style tab as an accordion.

- .changeset/few-ads-kick.md
- sites/geohub/src/routes/(app)/data/+page.server.ts
await page data loading at +page.server.ts
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1273616261) by [Unito](https://www.unito.io)
> fix: await page data at +page.server.ts for /data page

- .changeset/seven-terms-reflect.md
- packages/svelte-undp-design/package.json
- packages/svelte-undp-design/src/lib/Header/Header.svelte
browser variable is necessary...sorry for making a bug
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1273827337) by [Unito](https://www.unito.io)
>  fix: Use browser from sveltekit to check window is available

- .changeset/shy-kangaroos-deny.md
- packages/svelte-static-image-controls/package.json
- packages/svelte-static-image-controls/src/routes/+page.ts
- packages/svelte-static-image-controls/svelte.config.js
- pnpm-lock.yaml
fixes #2583
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1273920999) by [Unito](https://www.unito.io)
> chore: sveltekit v2 static api control

- .changeset/small-sheep-brake.md
- sites/geohub/src/components/header/UserAccount.svelte
fixes #2594
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1274100278) by [Unito](https://www.unito.io)
> fix: removed letter-space from between initials in user account icon

- .changeset/real-ravens-juggle.md
- .changeset/spicy-needles-boil.md
- packages/svelte-undp-design/src/lib/Accordion/Accordion.stories.ts
- packages/svelte-undp-design/src/lib/Accordion/Accordion.svelte
- sites/geohub/src/components/maplibre/OptionalPropertyEditor.svelte
- sites/geohub/src/components/maplibre/circle/VectorCircle.svelte
- sites/geohub/src/components/maplibre/fill-extrusion/VectorFillExtrusion.svelte
- sites/geohub/src/components/maplibre/fill/VectorPolygon.svelte
- sites/geohub/src/components/maplibre/heatmap/VectorHeatmap.svelte
- sites/geohub/src/components/maplibre/line/VectorLine.svelte
- sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
- sites/geohub/src/components/maplibre/symbol/IconImage.svelte
- sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
- sites/geohub/src/components/pages/map/data/DataVectorCard.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLabelPanel.svelte
- sites/geohub/src/components/util/ColorMapPicker.svelte
- sites/geohub/src/components/util/DataPreview.svelte
- sites/geohub/src/routes/+layout.svelte
- sites/static-image-api/src/routes/(app)/+layout.svelte
because UNDP design uses 16px as default font size
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1274155578) by [Unito](https://www.unito.io)
> fix: changed default font size from 13px to 16px

- .changeset/stupid-scissors-invent.md
- sites/geohub/src/components/maplibre/circle/VectorCircle.svelte
- sites/geohub/src/components/maplibre/fill-extrusion/VectorFillExtrusion.svelte
- sites/geohub/src/components/maplibre/fill/VectorPolygon.svelte
- sites/geohub/src/components/maplibre/heatmap/VectorHeatmap.svelte
- sites/geohub/src/components/maplibre/line/VectorLine.svelte
- sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
- sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
- sites/geohub/src/components/maplibre/vector/VectorSimulationAccordion.svelte
- sites/geohub/src/components/pages/map/data/DataCard.svelte
- sites/geohub/src/components/pages/map/data/DataVectorCard.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLabelPanel.svelte
- sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
- sites/geohub/src/components/util/Accordion.svelte
- sites/geohub/src/components/util/Help.svelte
- sites/geohub/src/components/util/stac/StacCatalogItem.svelte
- sites/geohub/src/components/util/stac/StacCatalogMap.svelte
- sites/geohub/src/routes/(map)/maps/[id]/+page.svelte
closes #2608 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1274828056) by [Unito](https://www.unito.io)
> fix: switched accordion from svelte-undp-design

- .changeset/thirty-cooks-agree.md
- sites/geohub/src/components/pages/map/plugins/MaplibreLegendControl.svelte
- sites/geohub/src/components/util/Accordion.svelte
fixes #2613
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1275338839) by [Unito](https://www.unito.io)
> fix: fixed Accordion component's layer name bug

- docker/README.md
- docker/docker-compose.yml
- sites/geohub/.env.docker.example
- sites/geohub/.gitignore
added static api to docker-compose
it will be exposed as localhost:9000
also, added .env template for docker `.env.docker.example`
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1275483141) by [Unito](https://www.unito.io)
> add static-image-api to docker-compose.yml

- sites/static-image-api/package-lock.json
- sites/static-image-api/package.json
- sites/static-image-api/src/routes/(app)/+layout.svelte
- sites/static-image-api/src/routes/(app)/api/+page.ts
- sites/static-image-api/src/routes/(app)/playground/+page.server.ts
- sites/static-image-api/src/routes/(app)/playground/+page.svelte
- sites/static-image-api/src/routes/api/og/+server.ts
- sites/static-image-api/src/routes/api/style/static/[bbox]/[width]x[height].[format]/+server.ts
- sites/static-image-api/src/routes/api/style/static/[lon],[lat],[zoom],[bearing],[pitch]/[width]x[height].[format]/+server.ts
- sites/static-image-api/src/routes/api/style/static/auto/[width]x[height].[format]/+server.ts
closes #2627
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1276285381) by [Unito](https://www.unito.io)
> chore: upgrade sveltekit to v2 for static API

- .changeset/perfect-gorillas-impress.md
- packages/undp-bulma/package.json
- pnpm-lock.yaml
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1276569958) by [Unito](https://www.unito.io)
> chore: upgrade vite to v5

- .changeset/shiny-horses-drive.md
- sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
- sites/geohub/src/components/pages/data/datasets/SelectedTags.svelte
- sites/geohub/src/components/pages/data/datasets/TagFilter.svelte
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasetHeader.svelte
- sites/geohub/src/components/pages/map/Content.svelte
- sites/geohub/src/components/pages/map/data/DataView.svelte
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/components/pages/map/plugins/StyleShare.svelte
- sites/geohub/src/lib/VectorTileData.ts
fixes #2634
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1276843376) by [Unito](https://www.unito.io)
> fix: replaced history.replaceState to goto method with replaceState parameter = true or replaceState from /navigation

- sites/geohub/svelte.config.js
there was a mistake in alias setting of svelte.config.js. $ sign was needed...
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1277068448) by [Unito](https://www.unito.io)
> fix: alias of svelte config

- .changeset/shy-parents-rhyme.md
- sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
- sites/geohub/src/components/pages/data/datasets/SelectedTags.svelte
- sites/geohub/src/components/pages/data/datasets/TagFilter.svelte
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasetHeader.svelte
- sites/geohub/src/components/pages/map/Content.svelte
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/components/pages/map/plugins/StyleShare.svelte
found typescript error for replaceState
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1277077495) by [Unito](https://www.unito.io)
> fix: pass '' to the second argument of replaceState

- .changeset/short-garlics-play.md
- sites/geohub/src/components/maplibre/vector/VectorParamsPanel.svelte
fixes #2640 
I only fixed layout collapse since it might be changed later
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1277277781) by [Unito](https://www.unito.io)
> fix: fixed layout collapse for vector simulation component

- .changeset/slimy-houses-smell.md
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
fixes #2663
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1278080090) by [Unito](https://www.unito.io)
> fix: delete style editor when clicking delete all layers button

- .changeset/gentle-jokes-call.md
- .changeset/small-lamps-end.md
- sites/geohub/src/components/pages/map/layers/LayerEdit.svelte
- sites/geohub/src/components/pages/map/plugins/MaplibreLegendControl.svelte
- sites/geohub/src/components/util/FloatingPanel.svelte
fixes #2668 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1278290653) by [Unito](https://www.unito.io)
> fix: click the entire header to toggle layer editor and legend panel.

- .changeset/angry-bulldogs-talk.md
- sites/geohub/src/components/pages/map/layers/LayerEdit.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
fixes #2673
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1279004452) by [Unito](https://www.unito.io)
> fix: update layer edit contents between vector layers / raster layers.

- .changeset/long-news-vanish.md
- sites/geohub/src/routes/(auth)/auth/signIn/+page.svelte
- sites/geohub/src/routes/(auth)/auth/signIn/+page.ts
add some description about admin approval error
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1279036275) by [Unito](https://www.unito.io)
> fix: add description for need admin approval error in sign in page

- .changeset/friendly-trees-joke.md
- sites/geohub/src/components/pages/map/layers/LayerEdit.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
fixes #2688
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1279905218) by [Unito](https://www.unito.io)
> fix: fixed tab from scrolling

- .changeset/rotten-badgers-exercise.md
- sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
fixes #2697
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1280764229) by [Unito](https://www.unito.io)
> fix: removed uncessary paddings from maplibre popup of query tool

- backends/k8s/cogserver/yaml/cogserver-deployment.yaml
update CiCD
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1280793940) by [Unito](https://www.unito.io)
> change label and memory
