- .github/workflows/main_undpgeohub.yml
I think sveltekit will bundle devDependencies packages, so we don't need to deploy them to the server.
I added `pnpm install --prod` to only deploy dependencies to the server. Folder size was reduced from 370MB to 200MB
> fix: only deploy node_modules for Dependencies

- package.json
I think lefthook will be installed automatically through `prepare` script
> fix: added lefthook install in prepare

- package.json
- pnpm-lock.yaml
Since `pnpm i --prod` skip installing `devDependencies`, CI failed. Thus I moved lefthook from devDependencies to dependencies.
> moved lefthook to dependencies

- src/routes/martin/+server.ts
- src/routes/pgtileserv/+server.ts
${url.origin} does not work correctly in production website, I deleted url.origin to change it from full URL to relative URL
> removed url.origin to change URL to relative one

- src/components/DataCard.svelte
- src/components/MiniMap.svelte
- src/lib/MosaicJsonData.ts
- src/lib/RasterTileData.ts
- src/lib/VectorTileData.ts
fix #830 
also fixed bug of min max zoom
> show raster tile's metadata in accordion

- .dockerignore
- Dockerfile
- docker-compose.yml
I just tried to add Dockerfile to make production server environment with pm2. The image will be build by multistages and in my environment, final Docker image size is 260 MB.
The server will be launched by pm2 with 4 instances cluster.
However, building time is very long (like almost 10 minutes...) because it cannot use pnpm's cache inside Dockerfile.
> feat: add Dockerfile for production server environment

- sites/geohub/src/components/Content.svelte
- sites/geohub/src/components/LayerList.svelte
- sites/geohub/src/components/RasterLayer.svelte
- sites/geohub/src/components/VectorLayer.svelte
fixes #1020
- moved style loading codes from Content.svelte to LayerList.svelte
- exposed `classificationMethod` from vectorLayer and rasterLayer
- set classification method from restored style.json
> fix: set classification from restored style.json fro vector and raster layer

- packages/svelte-undp-design/src/lib/Accordion/Accordion.stories.ts
- packages/svelte-undp-design/src/lib/Accordion/Accordion.svelte
- sites/geohub/src/components/data-view/DataStacAssetCard.svelte
Asset header is now different from the main dataset accordion title
> add asset header font size options

- sites/geohub/src/components/controls/IntervalsLegendColorMapRow.svelte
- sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
- sites/geohub/src/lib/helper/generateColorMap.ts
fixes #1185 
- fixed bug of restoring visibility button state for vector interval legend
- fixed bug of `generateColormap` function to set opacity=1 instead of 255 for raster.
> fix: bug of restoring state of visilibity button in interval legend

- sites/geohub/vite.config.ts
Disabled optimizeDeps in vite.config.ts. 
There was an issue of showing 500 error in my environment for dashboard page (and it works in production, only for dev command).
I found it works if we disabled optimizeDeps option in vite.config.ts.
> fix: disabled optimizeDeps since there is an issue of dashboard page when pnpm dev is run

- sites/geohub/src/routes/+layout.server.ts
Since there is error of __data.json, I updated +layout.server.ts not to set `session` property if there is no login info. Hope it will work...
> updated layout.server.ts that only set session property in __data.json when there is session info

- sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
fixes #1190 
Fix bug of not setting transparency of fill outline color in advanced legend
> fix: update filloutline color with new transparency of fill color in vector advanced legend

- sites/geohub/src/lib/helper/updateParamsInURL.ts
Fixed bug that maplibre complains there are undefined properties in style's sources (raster-dem source).
> fix: a bug to remove undefined properties from source of style.json

- .changeset/fluffy-teachers-develop.md
- packages/geohub-cli/src/util/BlobServiceAccountManager.ts
For vector tiles, previously we used file name as `name` field of dataset table, but it should be retrieved from `name` property of metadata.json or metadata on pmtiles if `name` is present.
If `name` does not exist in metadata, file name will be used as `name` field as the same with current API.
> Use name property from metadata.json or pmtiles's metadata instead of using file name if name property is present.

- sites/geohub/src/components/maps/MapStyleCardList.svelte
- sites/geohub/src/routes/maps/+page.svelte
fixed a design layout of map stats. Use css flex instead of using bulma tile. Removed some gaps between cards
> fix: use css flex instead of bulma tile

- sites/geohub/src/components/controls/vector-styles/Legend.svelte
- sites/geohub/src/lib/helper/updateParamsInURL.ts
Since PR https://github.com/UNDP-Data/geohub/pull/1262 was merged, updateParamsInUrl function has no longer fire sourcedata event, styledata event, load event because the function is directly updating source URL and delete cache.
Thus, I added a code to fire custom maplibre event `source:changed` to update legend symbol in layer name. 
> Fix: fire sourcechange event

- sites/geohub/src/routes/api/style/+server.ts
forgot to change URL of saved map in /style api. It was using old `/viewer` URL in share dialog
> fix: forgot to change URL of saved map in /style api

- sites/geohub/src/components/LayerList.svelte
- sites/geohub/src/components/data-view/DataCard.svelte
- sites/geohub/src/components/data-view/DataStacAssetCard.svelte
- sites/geohub/src/lib/MosaicJsonData.ts
- sites/geohub/src/lib/RasterTileData.ts
- sites/geohub/src/lib/helper/getRandomColormap.ts
- sites/geohub/src/lib/types/Layer.ts
For Raster layers that have unique values, the Unique Value Legend will be available by default.
> Fix: show unique value legend by default

- sites/geohub/src/components/MainApp.svelte
- sites/geohub/src/components/control-groups/LayerNameGroup.svelte
- sites/geohub/src/components/controls/DeleteButton.svelte
- sites/geohub/src/styles/button-icons-selected.scss
- fixed z-index of close button in sidebar (#1339 )
- fixed delete dialog for responsive (#1338)
- fixed alignment of buttons next to layer name (use css grid now)
- also enabled delete button always. non-login user still cannot save map, so I think it is ok for them to delete layer)
> fix: 1338 delete button

- .changeset/tame-llamas-retire.md
- packages/svelte-undp-design/src/lib/Accordion/Accordion.svelte
Before the Accordion was not aligned. when there was not button. Adding a div that covers approximately the 10% of the width as the slot fixes this issue
> fix: add style for acordion to make it aligned when there is no button

- sites/geohub/src/lib/VectorTileData.ts
fixes error of not showing pmtiles of narok water
> fix: to check type is pgtilerserv or martin before setting tile.json URL

- sites/geohub/src/components/controls/ColorMapPicker.svelte
> fix: default tab on colormappicker is selected by current colormap name

- renovate.json
added automerge setting for renovate by following this example.
https://docs.renovatebot.com/key-concepts/automerge/#configuration-examples
https://github.com/sveltejs/kit/blob/0ceab95d4b463540b6391b50e9b58af391b0a461/renovate.json#L22-L25
> chore: added automerge setting

- sites/geohub/src/components/DataView.svelte
- sites/geohub/src/components/data-view/TextFilter.svelte
- sites/geohub/src/components/maps/MapStyleCardList.svelte
- sites/geohub/src/lib/constants.ts
- sites/geohub/src/lib/server/helpers/createDatasetSearchWhereExpression.ts
- sites/geohub/src/routes/data/+page.server.ts
- sites/geohub/src/routes/data/+page.svelte
- sites/geohub/src/routes/data/publish/+page.server.ts
- sites/geohub/src/routes/data/upload/+page.server.ts
- sites/geohub/src/routes/maps/+page.server.ts
- sites/geohub/static/api/docs/swagger.yaml
- separate logic of loading styles from frontend side to backend.
- added `queryoperator` (either `and` or `or`, default is `and`) in /datasets api. Now you just type keywords in `query` param with spaces. and /datasets api will handle to replace spaces to equivalent operator according to `queryoperator` param. 
> refactor: separate data loading from frontend to +page.server.ts

- renovate.json
added `stabilityDays` settings in renovate.json
- auto merge after 7days for major release
- auto merge after 3 days for minor release
- auto merge after 2 days for patch release
> chore: added stabilityDays in renovate.json

- sites/geohub/src/components/controls/RasterPropertyEditor.svelte
- sites/geohub/src/lib/MosaicJsonData.ts
- set raster resampling for mosaicjson
- delete help from raster property editor to make it compact
> fix: set nearest for resampling of mosaicjson as default, and delete help from raster property editor to make it compact

- sites/geohub/src/routes/data/upload/+page.svelte
added space, &, % for file name validation
> fix: added space, &, % for file name validation

- sites/geohub/src/lib/types/TileJson.ts
- sites/geohub/src/routes/api/datasets/ingesting/+server.ts
now it can fetch all ingested datasets under datasets folder
> fix: bug of ingesting api. now it can detect all ingested datasets

- sites/geohub/src/components/LayerList.svelte
- sites/geohub/src/components/layer-order/LegendPanel.svelte
I could not figure out #1523, but fixed two bugs
- checkbox of filtering geohub layer was not working
- legend was not shown when saved map is loaded.
> fix: checkbox selecting in layer order panel

- sites/geohub/src/components/controls/VectorClassifyLegend.svelte
closes #1514
This PR is going to set default color when the property value is NULL for vector interval or categorical legend.
I set default color as `rgba(0,0,0,0)` (transparent value).
https://maplibre.org/maplibre-gl-js-docs/style-spec/other/#function-default
However, new view layers which are from pg_tileserv has numeric value as string data type, if we select `value_yyyy` column, it cannot be visualised. but the error was solved now. no weird error from maplibre
Furthermore, I force to use interval legend if the value is number
> fix: set defaultcolor value (transparent color) for interval/categorical expression

- sites/geohub/src/components/controls/VectorClassifyLegend.svelte
I did a mistake to set color value for icon-size and line-width. I set zero because NULL value should not be shown
> fix: set default iconSize and lineWidth to zero for classify legend.

- sites/geohub/src/components/controls/VectorClassifyLegend.svelte
- sites/geohub/src/lib/helper/getIntervalList.ts
fixes #1538
use unique value legend if values is only one
> fix: use uniquevalue legend if value is only one

- .changeset/slow-gorillas-decide.md
- packages/geohub-cli/README.md
- packages/geohub-cli/src/cli/index.ts
disabled commands to update azblob and pgtileserv because it will break our database if we use it now.
> fix: disabled commands for azblob, pgtileserv and cogunit

- sites/geohub/src/components/data-upload/DataPreview.svelte
- sites/geohub/src/components/data-view/MiniMap.svelte
- sites/geohub/src/routes/data/publish/+page.server.ts
- sites/geohub/src/routes/data/publish/+page.svelte
this PR is going to enable `/data/publish` page to edit/register pgtileserv layers if login user is superuser. 
Note. pgtileserv layers are not shown in `/data` page. This is very secret feature for super user.
For using this feature, just open URL like below.
https://dev.undpgeohub.org/data/publish?url=https://pgtileserv.undpgeohub.org/rwanda.water_facilities/{z}/{x}/{y}.pbf
> feat: enabled to edit/register pgtileserv layer if user is superuser

- sites/geohub/src/components/maps/MapStyleCard.svelte
I feel opening map editor page as different tab is disrupting. I changed it to open map in the same tab.
> fix: in maps page, now will open editor page in the same tab instead of opening in another tab

- sites/geohub/src/components/Header.svelte
- sites/geohub/src/components/Map.svelte
- sites/geohub/src/components/StyleShareControl.svelte
- sites/geohub/src/lib/config/AppConfig/TourOptions.ts
Previously, there was a share menu in header as shown in the following figure.
SInce all other menus are to move to different page, this share menu has only different action to save user's work within the map editor. I feel this difference on share menu of header may confuse users. Hence, I moved share menu to maplibre control. Now it is shown in top-right of control.
I also added a tour for this share control.
> feat: moved share menu from header to maplibre control button

- pnpm-lock.yaml
- sites/geohub/package.json
sorry, revert changes of https://github.com/UNDP-Data/geohub/pull/1761.
I think `sveltekit-og` and `svelte` needs to be dependencies for server side api.
> fix: moved sveltekit-sg and svelte to dependencies

- sites/geohub/src/components/data-view/LayerTypeSwitch.svelte
> fix: set default layer type when geometry is linestring

- .changeset/khaki-worms-wave.md
- .changeset/nice-cobras-sell.md
- packages/svelte-undp-design/src/lib/CtaLink/CtaLink.stories.ts
- packages/svelte-undp-design/src/lib/CtaLink/CtaLink.svelte
- packages/svelte-undp-design/src/lib/FluidCarousel/FluidCarousel.svelte
- packages/svelte-undp-design/src/lib/Header/Header.svelte
- sites/geohub/src/components/Content.svelte
- sites/geohub/src/components/DataView.svelte
- sites/geohub/src/components/Header.svelte
- sites/geohub/src/components/UserAccount.svelte
- sites/geohub/src/components/controls/Modal.svelte
- sites/geohub/src/components/data-view/SelectedTags.svelte
- sites/geohub/src/components/data-view/TagFilter.svelte
- sites/geohub/src/components/data-view/TextFilter.svelte
- sites/geohub/src/components/maps/MapStyleCard.svelte
- sites/geohub/src/routes/(app)/+page.svelte
- sites/geohub/src/routes/(app)/map/+layout@.svelte
- sites/geohub/src/routes/(app)/map/+page.svelte
Due to adding confirmation dialog, moving to pages by `document.location` does not trigger `beforeNavigate` event of sveltekit. So I changed most of links to use `<a href="url">`. Now every time if there is unsaved changes on map page, confirmation dialog will be appeared.
Furthermore, I found using `history.replaceState({}, null, url.toString());` can update page URL without triggering `beforeNavigate`. So, replaceState function is now used for all dataset search events in data tab.
> feat: add confirmation dialog to save or discard changes on map

- sites/geohub/src/components/RasterLayer.svelte
- sites/geohub/src/components/VectorLayer.svelte
Bulma tab looks good, but we will lose the feature of toggle content if switch from UNDP tab. We need another way to hide contents.
@iferencik @Thuhaa What do you think this Bulma tab? Also. do you have any alternative design idea to toggle contents?
> refactor: changed undp tab to bulma tab for layer legend

- sites/geohub/src/components/Settings.svelte
- sites/geohub/src/components/controls/vector-styles/TextField.svelte
- sites/geohub/src/lib/config/AppConfig/FontJonUrl.ts
- sites/geohub/src/lib/config/AppConfig/index.ts
- sites/geohub/src/lib/config/DefaultUserConfig/LabelTextFont.ts
- sites/geohub/src/lib/config/DefaultUserConfig/index.ts
fixes #1838 
Due to the change of Glyph URL, now we need to add text-font property always.
I also added dafault font option in settings.
If users already have saved map with CARTO's glyph URL, text-font property will not be generated.
> feat: add text-font property when label is created

- sites/geohub/src/components/Settings.svelte
Previously, users had to click tab menu to see settings. Now all setting items are flatten, and hash ID works to anchor section position now.
> refactor: flatten settings

- sites/geohub/src/components/LayerHeader.svelte
- sites/geohub/src/components/controls/RasterBandSelector.svelte
- sites/geohub/src/components/controls/RasterLegend.svelte
Since raster band selector does not need to be shown if only a band is available, now it is only shown if more than two bands are selectable. Also, moved it from layer header to raster legend component.
It will looks like the below screenshots if two bands are available in the layer. 
But most of our raster datasets only have a band. I even don't know which databasets have two bands...
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1200040941) by [Unito](https://www.unito.io)
> refactor: moved rasterbandselector to raster legend, and only available if available bands are more than one

- .changeset/lazy-suits-flow.md
- packages/svelte-undp-design/src/lib/CtaLink/CtaLink.svelte
- sites/geohub/src/components/data-upload/DataPreviewContent.svelte
- sites/geohub/src/components/data-upload/IngestingDatasetRowDetail.svelte
* hide `unpublish` button when the dataset is not published yet in responsive mode.
* changed PMTiles viewer for original one. since UNDP one does not show basemap correctly (maybe because of CORS)
* open PMTiles viewer from href link. 
* Added target property in CtaLink component of UNDP design. So it can be opened to new tab by specifying `_blank`. default is emptying string `''`.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1201215417) by [Unito](https://www.unito.io)
> fix: hide unpublish button in responsive, and open pmtiles viewer with href

- sites/geohub/src/components/data-upload/IngestingDatasets.svelte
- sites/geohub/src/routes/(app)/data/+page.svelte
There was a bug that elements on ingesting table were not updated when sorting setting is changed. I added `key` tag to force to recreate table.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1202286856) by [Unito](https://www.unito.io)
> fix: regenerate elements after sorting in client side

- sites/geohub/src/components/data-upload/PublishedDatasets.svelte
- sites/geohub/src/components/data-upload/SdgPicker.svelte
Adjusted height of SDG filter button
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1202750000) by [Unito](https://www.unito.io)
> fix: adjusted SDG filter height

- sites/geohub/src/hooks.server.ts
- sites/geohub/src/lib/server/helpers/upload.ts
- sites/geohub/src/routes/(app)/data/publish/+page.server.ts
- sites/geohub/src/routes/(app)/data/upload/+page.server.ts
- sites/geohub/src/routes/+layout.server.ts
- sites/geohub/src/routes/api/datasets/[id]/+server.ts
- sites/geohub/src/routes/api/datasets/ingesting/+server.ts
Make user hash key in hooks.server.ts now. so all server.ts can use user id as defalt through `session.user.id`.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1207637061) by [Unito](https://www.unito.io)
> fix: moving code of generating user hash key to hooks.server.ts

- sites/geohub/src/components/data-upload/IngestingDatasetRow.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1214735401) by [Unito](https://www.unito.io)
> fix: position of error message to be the next of Show details

- sites/geohub/build-nodemodules.sh
In dashboards/electricity and map page, the following error is shown when we reload the page (Moving from links in other page can work)
【 code  】
500
require is not defined in ES module scope, you can use import instead This file is being treated as an ES module because it has a '.js' file extension and '/home/site/wwwroot/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
【 end code 】
According to what the error says, package.json in deployment folder looks affecting nodejs server behaviour. Let me try not to copy package.json in build folder through this PR.
┆Issue …
> fix: don't copy package.json to deployment

- sites/geohub/src/components/controls/VectorClassifyLegend.svelte
- sites/geohub/src/lib/helper/generateColorMap.test.ts
- sites/geohub/src/lib/helper/getIntervalList.test.ts
- sites/geohub/src/lib/helper/getIntervalList.ts
- sites/geohub/src/lib/helper/getSampleFromInterval.ts
- sites/geohub/src/lib/helper/index.ts
- sites/geohub/src/lib/helper/isInt.test.ts
- sites/geohub/src/lib/helper/isInt.ts
@iferencik please review it for me
closes this old issue #792 finally
previously, interval legend shows float value for like `year` column. It is not intuitive to understand values.
Now, interval legend assumes the selected column's data type is integer if min and max value are int type. Then force to use interger value to create interval legend
But if min === 0 and max === 1, interval lgend will allow float values.
Furthermore, if the the number of values in stats are few (let's say less than unique value threshold's. 25), even number column should show unique value legend. Thus, now unique value legend is shown if the values length is less than 25.
┆Issue is synchronized …
> fix: force to use integer values if the column values are integer

- .changeset/new-dancers-sip.md
- packages/svelte-undp-design/src/lib/Pagination/Pagination.svelte
- packages/svelte-undp-design/src/lib/css/pagination.min.css
- sites/geohub/src/components/maps/MapStyleCard.svelte
- sites/geohub/src/components/maps/MapStyleCardList.svelte
It is going to fix the following weird error.
The problem was in UNDP Pagination component. It has several <a> tag and does not have any href prop. When the element come within viewport of browser, svelte failed to create URL object from a tag and it shows error.
I changed a tag to div element and it works well in localhost.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1227525592) by [Unito](https://www.unito.io)
> fix: changed a tag to div element on Pagination component because svelte complains it does not use any href

- sites/geohub/src/routes/(app)/management/stac/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1230127224) by [Unito](https://www.unito.io)
> fix: set limit=999 for getting geohub dataset

- sites/geohub/src/components/maplibre/symbol/IconImage.svelte
- sites/geohub/src/components/maplibre/symbol/IconImagePicker.svelte
- sites/geohub/src/components/pages/map/Map.svelte
- sites/geohub/src/components/pages/map/layers/header/LayerHeader.svelte
- sites/geohub/src/components/pages/map/layers/header/Legend.svelte
- sites/geohub/src/components/pages/map/layers/order/LayerOrderPanel.svelte
- sites/geohub/src/components/pages/map/layers/order/LayerOrderPanelButton.svelte
- sites/geohub/src/components/pages/map/layers/order/SortLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorClassifyLegend.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
- sites/geohub/src/routes/(app)/settings/+page.svelte
- sites/geohub/src/routes/(map)/map/+layout.svelte
- sites/geohub/src/stores/index.ts
- sites/geohub/src/stores/spriteImageList.ts
closes #1996 
* In settings page, it does not need to use store for SpriteImageList variable, so I just simply removed and directly use the variable.
* In map page, now create spriteImageStore in +layout.svelte and setContext. In children components, they getContext for sprite image.
* also, fixes some minor bugs related to Legend.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1230940761) by [Unito](https://www.unito.io)
> refactor: use ContextAPI for spriteImageList store. For settings, I changed not to use store since it is used within a page.

- .changeset/friendly-beers-search.md
- sites/geohub/src/lib/server/helpers/getStyleById.ts
- sites/geohub/src/lib/stac/MicrosoftPlanetaryStac.ts
fixed bug of resetting SAS token for Microsoft Planetary Computer in saved maplibre style source
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1234570503) by [Unito](https://www.unito.io)
> fix: fixed bug of resetting SAS token for Microsoft Planetary Computer in saved maplibre style source

- .changeset/sour-eels-behave.md
- sites/geohub/src/components/pages/map/layers/raster/RasterClassifyLegend.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLegend.svelte
For raster unique value data, default legend is not useful. only classifylegend is available for unique value raster
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1237704275) by [Unito](https://www.unito.io)
> fix: removed Default legend if the raster layer is unique value type

- .changeset/rude-donuts-press.md
- sites/geohub/src/components/util/StacExplorer.svelte
- sites/geohub/src/routes/api/stac/[type]/[collection]/[...item]/[asset]/+server.ts
fixes #2103
* fix: fixed bahaviour of STAC Explorer. Set MaxZoom and MaxBounds in the explorer, and fixed some behaviours when parameters are changed.
* I set MaxZoom as 8 for now.
* fixed mosaicjson path like `https://undpngddlsgeohubdev01.blob.core.windows.net/mosaicjson/microsoft-pc/sentinel-2-l2a/S2A_MSIL2A_20230714T072621_R049_T37MDP_20230714T145720/S2B_MSIL2A_20230907T072619_R049_T37MEP_20230907T152656/mosaicjson.json` (microsoft-pc/{collection id}/{...item}/mosaicjson.json)
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1240001636) by [Unito](https://www.unito.io)
> fix: #2103 stac explorer

- .changeset/six-spiders-study.md
- sites/geohub/src/routes/api/datasets/[id]/style/[layer]/[type]/+server.ts
fixes #2119
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1240061448) by [Unito](https://www.unito.io)
> fix: Use server endpoint if saved style source URL origin is different from current server (for pg_tileserv source)

- .github/workflows/ci.yml
fixed CI to trigger production deployment if branch is main
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1240204819) by [Unito](https://www.unito.io)
> fix: ci to trigger production deployment if branch is main

- .github/RELEASE_PULL_REQUEST_TEMPLATE.md
- .github/workflows/release.yml
closes #2142
It uses the below GitHub actions
https://github.com/marketplace/actions/create-pull-request
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1240763450) by [Unito](https://www.unito.io)
> feat: add new GitHub action job to create a release PR to prod automatically

- .github/RELEASE_PULL_REQUEST_TEMPLATE.md
- .github/workflows/release.yml
adding a CI job to create a PR automatically from develop to main
checkout `develop` branch and set `main` to base branch
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1240821327) by [Unito](https://www.unito.io)
> chore: add new CI job to create PR to merge develop to main

- .changeset/famous-brooms-impress.md
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
I fixed the bug where where sometimes the missing shapefile extensions are not visible #2153 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1241213335) by [Unito](https://www.unito.io)
> fix: Missing file extension error of shapefile is not shown

- .changeset/seven-parents-own.md
- sites/geohub/src/components/util/BackToPreviousPage.svelte
I am not sure why, but the a link used in go back button seems not working in some cases, I changed to use a link to button element's on click event and `goto` method of sveltekit. Hope it can work.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1241580697) by [Unito](https://www.unito.io)
> fix: use goto method of sveltekit for go back to previous page button

- .changeset/flat-cooks-punch.md
- sites/geohub/src/components/util/StacExplorer.svelte
closes #2160
I found currentZoom is not updated when map extent is changed. 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1241591463) by [Unito](https://www.unito.io)
> fix: update current zoom when map extent is changed in STAC explorer.

- sites/geohub/src/routes/(app)/data/+page.svelte
Remove `afterNavigate` from data page.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1242292923) by [Unito](https://www.unito.io)
> refactor: remove afterNavigate in datapage

- .changeset/blue-planets-mix.md
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasets.svelte
fixes #2177 (hopefully)
at least, it is not now flickering in my localhost when I reload browser
> fix: fixes data table flickering when my data page is reloaded

- .changeset/hip-needles-fetch.md
- sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
closes #2213
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1243318435) by [Unito](https://www.unito.io)
> fix: fixed bug of not showing default style edit page for RGB true color raster dataset

- .changeset/few-socks-cheat.md
- sites/geohub/src/components/maplibre/vector/VectorColorClassification.svelte
closes #2233
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1246594598) by [Unito](https://www.unito.io)
> fix: restore custom color correctly in VectorColorClassification legend

- .changeset/flat-rice-burn.md
- sites/geohub/src/components/maplibre/symbol/IconImage.svelte
fixes #2234
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1246600361) by [Unito](https://www.unito.io)
>  fix: sync icon-color in icon tab if user changed the color

- .changeset/two-frogs-admire.md
- sites/geohub/src/components/maplibre/circle/CircleColor.svelte
- sites/geohub/src/components/maplibre/circle/VectorCircle.svelte
- sites/geohub/src/components/maplibre/fill-extrusion/FillExtrusionColor.svelte
- sites/geohub/src/components/maplibre/fill-extrusion/VectorFillExtrusion.svelte
- sites/geohub/src/components/maplibre/fill/FillColor.svelte
- sites/geohub/src/components/maplibre/fill/FillOutlineColor.svelte
- sites/geohub/src/components/maplibre/fill/VectorPolygon.svelte
- sites/geohub/src/components/maplibre/line/LinePattern.svelte
- sites/geohub/src/components/maplibre/line/LineWidth.svelte
- sites/geohub/src/components/maplibre/line/VectorLine.svelte
- sites/geohub/src/components/maplibre/symbol/IconColor.svelte
- sites/geohub/src/components/maplibre/symbol/IconImage.svelte
- sites/geohub/src/components/maplibre/symbol/IconSize.svelte
- sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
- sites/geohub/src/components/maplibre/vector/VectorColorClassification.svelte
- sites/geohub/src/components/maplibre/vector/VectorLegend.svelte
- sites/geohub/src/components/maplibre/vector/VectorPropertyEditor.svelte
- sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
- sites/geohub/src/components/pages/map/layers/header/VisibilityButton.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
- sites/geohub/src/lib/helper/getVectorDefaultColor.ts
- sites/geohub/src/stores/defaultColor.ts
- sites/geohub/src/stores/index.ts
closes #2257
now defaultColor prop is using ContextAPI, and it is defined at VectorLayer component and DefaultStyleEditor component.
So, the state of default color will be kept even after switching to different tabs.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1249737049) by [Unito](https://www.unito.io)
> refactor: Use ContextAPI/store for defaultColor prop for vector style components

- .changeset/wise-bobcats-wave.md
- sites/geohub/src/components/header/Header.svelte
- sites/geohub/src/components/pages/home/MapHero.svelte
- sites/geohub/src/components/pages/map/data/StacExplorerButton.svelte
- sites/geohub/src/routes/(app)/+layout@.svelte
- sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
- sites/geohub/src/routes/(map)/map/+layout.svelte
- sites/geohub/src/stores/headerHeight.ts
- sites/geohub/src/stores/index.ts
I found context key of `header-height` was hard coded, and now uses constant variables and function from stores folder across different pages.
setContext at +layout.svelte which uses Header component
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1249759009) by [Unito](https://www.unito.io)
> refactor: Use context api with store for header height

- .changeset/brave-deers-speak.md
- sites/geohub/src/lib/config/AppConfig/AcceptedExtensions.ts
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
Commented out `.atx` extension as it is not needed in geohub and it breaks the functionality of upload file geodatabase that have `.atx` extension
https://docs.fileformat.com/gis/atx/#:~:text=Format%20%2D%20More%20Information-,What%20is%20a%20ATX%20file%3F,attribute%20index%20created%20in%20ArcCatalog.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1252137900) by [Unito](https://www.unito.io)
> fix: comment out  extension

- .changeset/eleven-beans-accept.md
- sites/geohub/src/routes/(app)/data/[id]/edit/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1252223066) by [Unito](https://www.unito.io)
> fix: show created_user correctly in dataset edit page

- .dockerignore
- pnpm-lock.yaml
- sites/geohub/package.json
Temporally downgrade auth/core to 0.18.0 because of `Directory import is not supported resolving ES modules imported from` error
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1254670432) by [Unito](https://www.unito.io)
> fix: downgrade auth/core to 0.18.0

- .changeset/wet-carpets-shake.md
- sites/geohub/src/components/maplibre/raster/RasterClassifyLegend.svelte
fixes #2371
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1259628899) by [Unito](https://www.unito.io)
> fix: fixed bug of default style edit page for raster unique value datasets

- .changeset/shaggy-poets-move.md
- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/lib/config/AppConfig/TourOptions.ts
because xmark button on the map has no clear relationship with sidebar closing, I updated menu plugin to move xmark button to inside the sidebar container.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1259853210) by [Unito](https://www.unito.io)
> fix: Updated menu plugin. Now xmark button on the map was moved into the top-right corner of sidebar container inside

- .changeset/twelve-wasps-rescue.md
- sites/geohub/src/routes/(app)/data/upload/+page.svelte
Found I had called `checkShapefileValidity` in the wrong place.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1261173314) by [Unito](https://www.unito.io)
> fix: call `checkShapeFileValidity` in the correct place

- .changeset/twenty-doors-admire.md
- sites/geohub/src/routes/(map)/maps/[id]/+page.ts
fixes #2453
I think #2453 was caused by we mix CSR and SSR in same line of endpoints
* /maps - CSR
* /maps/{id} - SSR
* /maps/{id}/edit - CSR
I guess SSR between CSR pages does not work in sveltekit in some reasons (not sure why). Hope at least this PR can fix issue in production (I could not confirm now because it is not reproducable in localhost).
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1264989257) by [Unito](https://www.unito.io)
> fix: switch /maps/id page to CSR

- .changeset/funny-schools-jam.md
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/components/util/PanelButton.svelte
fixes #2451
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1265788050) by [Unito](https://www.unito.io)
> fix: hide sort button if only a layer is added

- .changeset/rotten-doors-call.md
- packages/geohub-cli/src/util/StacManager.ts
- sites/geohub/src/components/util/stac/StacApiExplorer.svelte
- sites/geohub/src/components/util/stac/StacCatalogItem.svelte
fix: fixed bug of checking STAC asset item type. it is preferred to use `image/tiff; application=geotiff; profile=cloud-optimized` to check asset type, but we found some of COG from some STAC server, they don't put `profile=cloud-optimized`. So I removed profile from validation. There might be normal GeoTiff coming from STAC server, but we can assume all GeoTiffs are cloud optiomised GeoTiff from STAC.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1266052152) by [Unito](https://www.unito.io)
> fix: fixed bug of checking STAC asset item type.

- .changeset/fair-ears-rhyme.md
- sites/geohub/src/components/maplibre/circle/VectorCircle.svelte
- sites/geohub/src/components/maplibre/fill-extrusion/VectorFillExtrusion.svelte
- sites/geohub/src/components/maplibre/fill/VectorPolygon.svelte
- sites/geohub/src/components/maplibre/line/VectorLine.svelte
- sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
- sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
- sites/geohub/src/components/pages/map/layers/SimpleLayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/header/Legend.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
- sites/geohub/src/components/pages/map/plugins/MaplibreLegendControl.svelte
* made readonly legend more simple
* removed accordion from readonly legend
* if not classified legend, just show legend icon before layer name
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1267401152) by [Unito](https://www.unito.io)
> feat: made readonly legend more simple

- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterSimpleLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorSimpleLayer.svelte
- sites/geohub/src/components/pages/map/plugins/MaplibreLegendControl.svelte
fixes #2507
I created an Accordion component under util to enable changing icon size, but this affected reactivity of changing tabs. Thus, I removed this Accordion component from LayerTemplate.
Looks like nested slots sometimes lose reactivity in some cases (not sure exactly why this does not work)
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1267594033) by [Unito](https://www.unito.io)
> fix: fixed bug of tabs not changing. removed nested slot of accordion from LayerTemplate

- docker/README.md
- docker/docker-compose.yml
- sites/geohub/.env.example
added pg_tileserv to docker-compose.yml
```
cp sites/geohub/.env docker/.env
make docker-up
```
Then, titiler and pg_tileserv will be running in backend.
after that, in another terminal to run `make dev` to launch geohub (don't forget to set pgtileserv and titiler's localhost URL in .env)
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1275428726) by [Unito](https://www.unito.io)
> feat: add pg_tileserv to docker-compose.yml

- .changeset/spicy-zoos-yawn.md
- sites/geohub/src/components/pages/map/Content.svelte
- sites/geohub/src/components/pages/map/data/DataView.svelte
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
fixes #2638
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1277101329) by [Unito](https://www.unito.io)
> fix: add same margin-left and margin-right for data tab, layer tab

- .changeset/grumpy-poets-exercise.md
- sites/geohub/src/components/pages/map/data/DataCard.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
fixes #2650
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1277193568) by [Unito](https://www.unito.io)
> fix: add notification ! icon to show data accesibility in data tab accordion if dataset is not public access.

- .changeset/witty-jokes-listen.md
- sites/geohub/src/components/maplibre/raster/ClassificationSwitch.svelte
- sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
fixes #2662
renamed like the below screenshot
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1278138209) by [Unito](https://www.unito.io)
> fix: renamed title of colormap accordion

- .changeset/tough-masks-pull.md
- sites/geohub/src/components/pages/map/Map.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
* font of layer edit panel was different from default. now it is fixed
* changed tab size to normal
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1279928191) by [Unito](https://www.unito.io)
> fix: fixed font of layer panel. changed tab size for layer panel.

- .changeset/thirty-flies-fix.md
- sites/geohub/src/components/maplibre/vector/VectorParamsPanel.svelte
- sites/geohub/src/components/maplibre/vector/VectorSimulationArgument.svelte
fixes #2719 
1. set 1.2rem for line-height
1. set 56px for min-height of header. add `is-medium` for icon class with `fa-lg` (container size 2rem, icon size 1.33rem) in bulma
* https://bulma.io/documentation/elements/icon/#sizes
Two lines parameter name
1. add 0.5rem (8px) of margin-top for reset button
1. use `is-link` (UNDP blue color) for active color, use `is-info` for hover/expanded color
1. use same color of x button
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1282513787) by [Unito](https://www.unito.io)
> fix: improved new simulation component UI

- .changeset/cuddly-knives-dance.md
- sites/geohub/src/components/pages/data/datasets/PublishedDatasetOperations.svelte
- sites/geohub/src/components/pages/data/datasets/PublishedDatasetRow.svelte
- sites/geohub/src/components/pages/data/datasets/UserPermission.svelte
- sites/geohub/src/components/util/FieldControl.svelte
- sites/geohub/src/lib/server/DatasetPermissionManager.ts
- sites/geohub/src/routes/(app)/data/[id]/permission/+page.server.ts
- sites/geohub/src/routes/(app)/data/[id]/permission/+page.svelte
- sites/geohub/src/routes/(app)/data/[id]/permission/+page.ts
- sites/geohub/static/api/swagger/spec.yaml
closes #2701
* added new dropdown menu `set user permission` at dataset page
* created new page `dataset/{id}/permission` to add/edit/delete` user permission
* allows READ permission users to invite users to dataset as new viewer permission
* I commented source code of email message textbox.
TODO
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1285139894) by [Unito](https://www.unito.io)
> feat: add GUI to set user permission for a dataset

- .changeset/weak-parrots-study.md
- sites/geohub/src/routes/(app)/data/+page.svelte
- sites/geohub/src/routes/api/datasets/+server.ts
There was a bug in dataset api and data page when users do not sign in.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1287729635) by [Unito](https://www.unito.io)
> fix: fixed bug of datasets api SQL when users do not sign in

- .changeset/selfish-rocks-join.md
- sites/geohub/src/routes/api/datasets/[id]/style/[layer]/[type]/+server.ts
I found bugs in default style api. to update or delete, READ permission should not be allowed (at least WRITE permission)
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1288531769) by [Unito](https://www.unito.io)
> fix: fixed bug of dataset permission when saving/deleting default style

- .changeset/happy-cherries-thank.md
- sites/geohub/src/components/pages/data/datasets/PublishedDataset.svelte
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
- sites/geohub/src/routes/(map)/maps/[id]/+page.svelte
fixes #2798
* use same design of header for data page and map page with back ground color and same margin.
* for map page, moved operation buttons to under preview tab (maybe star and delete can be under Info tab, but I just kept all buttons together)
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1295924608) by [Unito](https://www.unito.io)
> fix: add more margin and background-color for header in data page and map page.

- .changeset/rotten-tigers-lie.md
- sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
fixes #2851
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1300472633) by [Unito](https://www.unito.io)
> fix: changed tabs in layer edit panel to UNDP tabs

- .changeset/strong-taxis-sip.md
- sites/geohub/src/components/pages/map/data/DataView.svelte
fixed bug of loading data when selecting a continent in data tab
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1301511296) by [Unito](https://www.unito.io)
> fix: bug of when selecting continent in data tab.

- docker/docker-compose.yml
- docker/static-api-entrypoint.sh
found static-api image does not work with docker-compose locally. but it works in our AppService. Decided to use another different entrypoint.sh for docker-compose
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1301944150) by [Unito](https://www.unito.io)
> fix: use different entrypoint.sh for static-api used in docker-compose

- docker/static-api-entrypoint.sh
fixed bug of entrypoint.sh for docker
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1302074272) by [Unito](https://www.unito.io)
> fix: don't execute evfb if DISPLAY is already in use

- .changeset/rude-berries-tell.md
- sites/geohub/src/routes/(app)/settings/+page.svelte
fixes #2876
* introduced same tabs of maps/data page
* added accordions for each section because there are so many properties in map tab. it will be helpful for users to overview settings.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1303034728) by [Unito](https://www.unito.io)
> fix: introduced tabs in settings page to use unified design with maps/data page.

- .changeset/rude-berries-tell.md
- sites/geohub/src/routes/(app)/settings/+page.svelte
Reverts UNDP-Data/geohub#2879
introducing accordions looks not good for users. Previous version is better. I am going to revert it.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1303074734) by [Unito](https://www.unito.io)
> Revert "fix: introduced tabs in settings page to use unified design with maps/data page."

- .changeset/shaggy-geese-glow.md
- packages/undp-bulma/bulma.scss
- packages/undp-bulma/src/main.ts
set same padding of UNDP button for bulma
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1303176942) by [Unito](https://www.unito.io)
> fix: set button padding and disabled background color in undp-bulma button style

- .changeset/chilly-cows-appear.md
- packages/undp-bulma/bulma.scss
it has a problem of disabled button color appearance
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1303519030) by [Unito](https://www.unito.io)
> fix: removed button-disabled-background-color from undp-bulma setting

- .changeset/serious-students-build.md
- sites/geohub/src/components/pages/map/Map.svelte
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterSimpleLayer.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorSimpleLayer.svelte
- sites/geohub/src/components/pages/map/plugins/MaplibreLegendControl.svelte
- sites/geohub/src/lib/server/helpers/getStyleById.ts
- sites/geohub/src/routes/(auth)/auth/signIn/+page.ts
fixes #2832
* fix: remove layers from saved map style.json if signed/unsigned in user does not have permission to access to the dataset. In this case, a warning message is shown inside the layer accordion to tell users does not have permission to access.
* remove layers/sources which user does not have permission to access at /api/style/{id} endpoint
* but it still remain layer in `style.layers` array, so frontend can know user has no access to the dataset.
it shows warning message like below.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1303837205) by [Unito](https://www.unito.io)
> fix: remove layers from saved map style.json if signed/unsigned in user does not have permission to access to the dataset

- .changeset/smart-dryers-protect.md
- sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
fix: skip if layer is not there in style.json when use query tool
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1303965411) by [Unito](https://www.unito.io)
> fix: skip if layer is not there in style.json when use query tool

- .changeset/nine-ants-enjoy.md
- packages/svelte-undp-design/src/lib/css/country-site-header.min.css
previously, we changed logo height to be the same height of header because the logo stuck out affected our sidebar design. But current design can be together with original logo height. 
Reverted logo height to the original UNDP design header.
@balagurova what do you think of this reverting? Is that better to be the same logo height of UNDP design?
* current version
* reverted version
landing page
with sidebar
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1304013587) by [Unito](https://www.unito.io)
> fix: reverted logo height to original UNDP header version

- .changeset/tender-scissors-deliver.md
- sites/geohub/src/components/pages/map/Map.svelte
fixed position of map buttons because of conflicting with admin tool control.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1304737520) by [Unito](https://www.unito.io)
> fix: show map menu buttons on top-right always (not affected by the position of sidebar).

- .changeset/giant-windows-boil.md
- sites/geohub/src/components/pages/map/layers/LayerList.svelte
- sites/geohub/src/lib/config/DefaultUserConfig/MaplibreDevMode.ts
- sites/geohub/src/lib/config/DefaultUserConfig/index.ts
- sites/geohub/src/routes/(app)/settings/+page.server.ts
- sites/geohub/src/routes/(app)/settings/+page.svelte
or if add `/maps/edit?dev=true` in address bar, it can show tile boundaries and collision boxes
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1306498461) by [Unito](https://www.unito.io)
> feat: added new setting of Development mode in setting page to enable tile boundaries and collision boxes for advanced users.

- .changeset/grumpy-eagles-turn.md
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
forgot to update endpoint for map edit page
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1307252870) by [Unito](https://www.unito.io)
> fix: redirect to map edit page from stac explorer

- .changeset/mighty-poets-provide.md
- packages/svelte-undp-design/package.json
I realized storybook files are included in dist folder.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1315905020) by [Unito](https://www.unito.io)
> fix: Remove unused code from svelte-undp-design package

- .changeset/light-monkeys-crash.md
- sites/geohub/src/components/pages/data/datasets/RasterBandSelectbox.svelte
fixes #3034
some band description is quite long, so I decided to keep band name, and show band description after band name if available.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1317590906) by [Unito](https://www.unito.io)
> fix: show band description after band name in raster band selectbox if applicable

- .changeset/ninety-tigers-attack.md
- sites/geohub/src/routes/(app)/maps/+page.svelte
Fixed url to /maps/edit in `New Map` button in /maps page
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1320671746) by [Unito](https://www.unito.io)
> fix: new map url in button

- .changeset/brave-steaks-breathe.md
- .changeset/metal-drinks-float.md
- packages/svelte-undp-design/src/lib/Card/Card.stories.ts
- packages/svelte-undp-design/src/lib/Card/Card.svelte
- packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.stories.ts
- packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.svelte
- sites/geohub/src/components/pages/data/datasets/CardView.svelte
- sites/geohub/src/components/pages/home/MapStyleCardList.svelte
Now users can see data/map access level in card view
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1321346301) by [Unito](https://www.unito.io)
> fix: show accessibility icon on card at maps and data page

- .changeset/swift-lamps-watch.md
- sites/geohub/src/routes/(app)/data/+page.svelte
fixes #3122
I think this bug was caused by refactoring of hero header component.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1324918189) by [Unito](https://www.unito.io)
> fix: fixed bug of inaccessible to data page when users do not sign in

- .changeset/tender-flies-shake.md
- packages/svelte-undp-components/src/lib/components/ModalTemplate.svelte
- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/components/pages/map/layers/header/DeleteMenu.svelte
I removed `svelte-keydown` and moved that functionality to `ModalTemplate` component to close dialog by escape key. But if close button is not shown in dialog, no close event will be occurred.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1324948835) by [Unito](https://www.unito.io)
>  fix: close ModalTemplate by espace key if close button is shown in dialog.

- .changeset/neat-planes-repeat.md
- sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
found no title and description were shown in accordion
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1325084087) by [Unito](https://www.unito.io)
> fix: show algorithm's title and description at accordion title and help at layer editor

- .github/workflows/ci.yml
I created a new AppService for dev.undpgeohub.org to use our docker image instead of NodeJS server
Migrated all environmental variables including secrets, so it should work 
I deleted `deploy_to_develop` job from CI since no longer needed.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1329682246) by [Unito](https://www.unito.io)
> ci: removed deploy to develop job since AppService was migrated to Docker version intead of Node js server

- .changeset/cool-bats-impress.md
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRowDetail.svelte
I found add button is shown for preview popup which should not be there
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1329699787) by [Unito](https://www.unito.io)
> fix: remove add to map button in ingested dataset preview

- .changeset/chilled-buckets-breathe.md
- packages/svelte-undp-components/src/lib/components/ColorMapPicker.svelte
- packages/svelte-undp-components/src/lib/components/ColorMapPickerCard.svelte
- packages/svelte-undp-components/src/lib/components/ColorMapPickerCard.test.ts
Previously, color legend was not shown in fullwidth. Now can show it in fullwidth.
Furthermore, I made title of tabs capitalized
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1330437844) by [Unito](https://www.unito.io)
> fix: show colormap legend in fullwidth for color card in colormap picker

- .changeset/real-snakes-hammer.md
- docker/Dockerfile.production
- pnpm-lock.yaml
- sites/geohub/package.json
reduced 299MB to 267MB for production docker image
I moved some dependencies to devDependencies. like auth.js modules can be in dev, I think. this can reduce size of node_modules folder
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1331291679) by [Unito](https://www.unito.io)
> fix: moved some dependencies to devDependencies and switched prod docker image to distroless image

- .changeset/twenty-carpets-happen.md
- sites/geohub/src/components/pages/map/data/StacExplorerButton.svelte
- sites/geohub/src/components/util/stac/StacCatalogExplorer.svelte
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
- sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.server.ts
- sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte
- sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.ts
fixes #3054
Now can register collection level from STAC catalog. Also added access level selector in dialog.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1334084732) by [Unito](https://www.unito.io)
> fix: register STAC Catalog as a collection level with selected access level on management page.

- .changeset/nice-feet-float.md
- .changeset/plenty-suits-clean.md
- sites/geohub/src/components/maplibre/raster/RasterLegendEdit.svelte
- sites/geohub/src/components/util/stac/StacCatalogTools.svelte
- sites/geohub/src/lib/RasterTileData.ts
- sites/geohub/src/lib/server/defaultStyle/RasterDefaultStyle.ts
- sites/geohub/src/routes/api/datasets/style/[layer]/[type]/+server.ts
- sites/geohub/static/api/swagger/spec.yaml
fixes #3250
* fix: accidentally removed rescale from URL when colormap is changed. Now it preserve original rescale in URL.
* fix: add algorithm param in default style api to create correct layer definition and metadata according to setting
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1336541252) by [Unito](https://www.unito.io)
> fix: preserve rescale value. add algorithm param in default style api

- documentation/Dockerfile
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1339735117) by [Unito](https://www.unito.io)
> fix: run git init for mkdocs author plugin to be executed correctly

- .changeset/angry-years-hide.md
- .changeset/itchy-cooks-teach.md
- .changeset/olive-pillows-protect.md
- .changeset/shaggy-flowers-divide.md
- .changeset/six-flies-bathe.md
- packages/svelte-static-image-controls/package.json
- packages/svelte-static-image-controls/src/lib/MaplibreStaticImageControl.svelte
- packages/svelte-static-image-controls/src/lib/StaticImageControl.svelte
- packages/svelte-static-image-controls/src/routes/+page.svelte
- packages/svelte-undp-components/src/lib/components/SegmentButtons.stories.ts
- packages/svelte-undp-components/src/lib/components/SegmentButtons.svelte
- pnpm-lock.yaml
- sites/geohub/src/components/pages/map/Map.svelte
fixes #3318
* fix: added hiddenApiTypes property in Static Image API Control
* fix: use SegmentButtons and FieldControls from svelte-undp-components
* fix: show loader for export control
* fix: added more options of capitalized, uppercase and fontweight for segmentbuttons component
* fix: Updated StaticImageControl, and make api type setting hidden for GeoHub's export control
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1342095241) by [Unito](https://www.unito.io)
> fix: show loader for export control, improved UI of export control

- .changeset/sour-dots-rescue.md
- sites/geohub/src/lib/server/helpers/getStyleById.ts
I improved the logic of style updating to ensure all new layers from the latest style will be added.
* firstly, copy all layers from the latest style
* then, add geohub layers from saved style.layers to new style layers in the same layer order
If the layer index is more than total layer length (exclude geohub layer), I consider it can be added in the last of layers array.
If the layer index is located at the middle of array, it compares layer id before the target layer. If before layer id is same, insert it in the same index.
Otherwise, insert it before the first symbol layer (new base style structure might have been changed).
┆Issue …
> fix: improved the logic of saved style update

- .changeset/little-pillows-teach.md
- sites/geohub/src/components/maplibre/raster/RasterClassifyLegend.svelte
fixes #3325
There were unnecessary event triggered by classification method and rescale store subscription. Fixed the bug for both raster categories legend and unique value legend.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1342970624) by [Unito](https://www.unito.io)
> fix: restore raster categories correctly when users set a class color transparent or customized.

- .changeset/weak-berries-taste.md
- sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
fixes #3340 
encodeURI for expression is not needed
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1342998230) by [Unito](https://www.unito.io)
> fix: fixed bug of map query after applying raster expression.

- .changeset/weak-elephants-sit.md
- sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte
- sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
- sites/geohub/src/lib/helper/getValueFromRasterTileUrl.ts
I found the dataset which has 0-1 value cannot be visualized well after applying raster expression because 0 was used as default value. So, if add expression of `b1 < 0.5`, pixels with a value more than 0.5 will become 0, and makes visualization very weird.
I did the following two changes.
* set -9999 as default value for raster expression instead of using zero (0)
* set nodata option for -9999. Titiler will overwrite nodata by -9999. So, the default value will not be shown.
* removed setting `rescale` param at transform component.
But I am not sure which default value is more appropriate. Not  so confident use of -9999 for nodata value.
Refer to [CONTRIBUTING.MD](https://github.com/UNDP-Data/geohub/blob/develop/CONTRIBUTING.md) for more …
> fix: set -9999 as default value for raster expression instead of zero. Also, set nodata option for -9999

- .changeset/gentle-paws-give.md
- sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte
- sites/geohub/src/lib/types/RasterExpression.ts
- sites/geohub/src/lib/types/index.ts
fixes #3316
I simplified the code related to state management. Each input element value is now directly binded to expression object other than having two variables to syncronize state.
Also, moved `RasterExpression` interface to the component itself since it is not used by any other component. 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1343067861) by [Unito](https://www.unito.io)
> fix: simplified the logic of state management for RasterTransform

- .github/workflows/ci.yml
- documentation/Dockerfile
- documentation/README.md
- documentation/docker-compose.yml
- documentation/mkdocs.yml
This can allow us to use different production URLs (prod and dev, and localhsot) to build. 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1343776808) by [Unito](https://www.unito.io)
> fix: change site_url from environmental variable

- .changeset/odd-bats-rush.md
- packages/svelte-undp-components/src/lib/components/NumberInput.svelte
fixes #3358
Allow users to enter negative value or float value manually. also, if entered value is out of range of min/max value, it will be overwritten by force.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1344027920) by [Unito](https://www.unito.io)
> fix: allow to input float value and negative value manually at NumberInput component

- .changeset/calm-horses-fry.md
- sites/geohub/src/components/maplibre/raster/RasterRescale.svelte
fix #3360
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1344587695) by [Unito](https://www.unito.io)
> fix: fixed bug of rescale when min/max is 0-1

- .changeset/seven-carrots-heal.md
- sites/geohub/src/components/pages/map/Map.svelte
found a bug when restore style from local storage
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1344625395) by [Unito](https://www.unito.io)
> fix: fixed a bug of restoring style in map page

- .changeset/weak-feet-rule.md
- sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte
- sites/geohub/src/lib/RasterTileData.ts
fixes #3345
* update $rescaleStore when new transform is applied
* show warning message in transform tab if user changed rescale from default.
Note.
This PR does not update `layer.info.band_metadata` and `layer.info.stats` properties because band name in a layer will be changed after applying expression, this causes a tricky behaviour. But the PR will fetch the new min and max value from statistics endpoint, and update rescale values.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1353120333) by [Unito](https://www.unito.io)
> fix: update rescale store when a raster transform is applied

- .changeset/nine-mangos-melt.md
- sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte
Improved default value setting for raster transform. When `<`, `<=`, `>`, `>=` operator is selected, visualization is improved. But still has an issue of nodata value masking when `\=`, `!=` is selected (still -9999 is used)
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1353205842) by [Unito](https://www.unito.io)
> fix: In raster transform, use layer max + 1 for <, <= operator. and Use min - 1 for >, >= operator.

- .changeset/tall-suits-applaud.md
- sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte
- sites/geohub/src/lib/RasterTileData.ts
Use nodata_value in info api if available, otherwise use -9999 for = and != operator, use threshold + 1 if < and <=, Use threshold - 1 if > and >=.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1353267788) by [Unito](https://www.unito.io)
> fix: Use nodata_value from info if available, otherwise use -9999 or threshold value inputted

- .changeset/eight-forks-design.md
- .changeset/perfect-ligers-explain.md
- packages/svelte-undp-components/src/lib/components/PropertyEditor.stories.ts
- packages/svelte-undp-components/src/lib/components/PropertyEditor.svelte
- packages/svelte-undp-components/src/lib/components/Slider.stories.ts
- packages/svelte-undp-components/src/lib/components/Slider.svelte
- sites/geohub/src/components/maplibre/raster/RasterAlgorithms.svelte
- sites/geohub/src/lib/types/RasterAlgorithm.ts
* fix: show labels on slider if algorithm's options_descriptions property is available
* feat: add formatter option to Slider and PropertyEditor components
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1356344543) by [Unito](https://www.unito.io)
> fix: show labels on slider if algorithm's options_descriptions property is available

- .changeset/curly-beers-move.md
- sites/geohub/src/components/maplibre/raster/RasterAlgorithmExplorer.svelte
- sites/geohub/src/components/maplibre/raster/RasterAlgorithms.svelte
- sites/geohub/src/components/pages/map/data/DataCard.svelte
- sites/geohub/src/lib/server/defaultStyle/RasterDefaultStyle.ts
- sites/geohub/src/lib/types/RasterAlgorithm.ts
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
also, set unit in PropertyEditor for algorithm if available
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1356432250) by [Unito](https://www.unito.io)
>  fix: add unit tag if algorithm's outputs.unit prop is available for showing unit in legend.

- .changeset/long-teachers-grab.md
- sites/geohub/src/components/util/stac/StacCatalogTools.svelte
Previously, unit tag was overwritten and removed it.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1356455166) by [Unito](https://www.unito.io)
> fix: add unit tag when RCA layer for stac is added

- .changeset/rude-knives-rhyme.md
- sites/geohub/src/components/pages/data/datasets/TagFilter.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1360212704) by [Unito](https://www.unito.io)
> fix: reset unapplied tag filter setting when the popup is closed.

- documentation/theme_overrides/reveal.html
I am not sure this can work. default href of go back button is set to `/` (relative path), just wanted to try to change absolute url to relative url for the link updated by script.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1361034697) by [Unito](https://www.unito.io)
> fix: changed absolute url to relative url for go back button

- .changeset/lemon-vans-laugh.md
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1361177802) by [Unito](https://www.unito.io)
> fix: fixed link of existing map edit page at data page

- .changeset/healthy-geese-hunt.md
- sites/geohub/src/components/util/stac/StacCatalogTools.svelte
previously, when month is changed, the day is kept from the previous month's. and add button was not disabled.
Now it checks whether all assets for input bands are selected.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1361738675) by [Unito](https://www.unito.io)
> fix: check whether assets are selected for all input bands when the date is changed from picker.

- backends/k8s/stac-pipeline/yaml/deployment.yaml
* added another scaled job to be triggered by cron
* trigger at 23:30pm to 23:40pm
* add new message for yesterday
adding yesterday's message may not work since most of data was created 2 to 3 days later. maybe adding 3 to 5 days days before is better??
https://eogdata.mines.edu/nighttime_light/nightly/rade9d_sunfiltered/?C=N;O=D
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1364781110) by [Unito](https://www.unito.io)
> chore: add scaledjob triggered by cron

- .changeset/lemon-lizards-jam.md
- sites/geohub/src/routes/(app)/data/[id]/+page.svelte
fixes #3504
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1367620469) by [Unito](https://www.unito.io)
> fix: enable permission tab for stac datasets

- backends/k8s/stac-pipeline/yaml/deployment.yaml
after archving historical data, can revert to one pod
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1368189859) by [Unito](https://www.unito.io)
> Max Replica to two pods for speeding up archiving

- Makefile
fixes #3517
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1369105961) by [Unito](https://www.unito.io)
> fix: exclude dist folder under documentation for make clean

- sites/static-image-api/src/lib/server/renderMap.ts
This fix remove `icon-overlap` property from symbol layer since it is not supported by maplibre native. Partially fixes #3534
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1372558169) by [Unito](https://www.unito.io)
> fix: removed icon-overlap property at static image api

- .github/workflows/release.yml
check changeset file in action to prevent merging develop to main before versioning.
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1373285875) by [Unito](https://www.unito.io)
> fix: check changeset file in action

- .github/workflows/release.yml
I found createReview action has never worked since the PR is created in the same action job. I included validated massage in description instead. then exit 1 if changeset file exists
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1373304876) by [Unito](https://www.unito.io)
> ci: add validated message in PR description

- .changeset/two-birds-guess.md
- sites/geohub/src/components/pages/map/Map.svelte
fixes #3584
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1376657086) by [Unito](https://www.unito.io)
> fix: disable featurestate of admin tool for geohub main map page

- .changeset/cuddly-crabs-mate.md
- sites/geohub/src/components/util/stac/StacCatalogExplorer.svelte
stac catalog from HREA has mixed collections and item, this PR at least fixes a bug of this catalog
https://globalnightlight.s3.amazonaws.com/HREAv1.1_COGs/AGO/AGO/catalog.json
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1376819310) by [Unito](https://www.unito.io)
> fix: fixed bug when a stac catalog hax mixed both collection and item

- .changeset/stupid-roses-ring.md
- sites/geohub/src/components/util/stac/StacCollectionMap.svelte
fixes #3606 
┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1378432934) by [Unito](https://www.unito.io)
> fix: show tabs in popup of map mode if multiple items/collections are matched.

- .changeset/shaggy-news-beam.md
- sites/geohub/src/components/pages/data/datasets/UserPermission.svelte
- sites/geohub/src/hooks.server.ts
- sites/geohub/src/lib/server/auth.ts
If signed user email address consists of mixed capitalized and lower case characters, and only lowercase email is added to permission table, they were considered as different email address.
To solve this issue, I made the following two changes:
- In hooks.server.ts, it will force to transform signed user email to lower case for all the time.
- In UserPermission component, validate user email after transforming to lower case, and register lower case email address even users input capitalized email. So, no capitalized email will be registered.
> fix: force to transform user_email to lowercase in hooks.server.ts and UserPermission component

- .changeset/two-feet-grin.md
- sites/geohub/src/routes/(app)/tools/+page.server.ts
- sites/geohub/src/routes/(app)/tools/+page.svelte
- sites/geohub/src/routes/(app)/tools/+page.ts
I think vector simulation datasets are also an important tool in GeoHub. Hence, I added these links to tools page as `Simulation add-ons` section.
If click a card, it will be redirected to the dataset page.
> fix: add dynamic vector to tools

- .github/workflows/ci.yml
I am not sure why only geohub-prod appservice does not redeploy docker image while other appservices will redeploy automatically when new docker image is pushed.
I added the deployment job into CI to force redeploying production image.
https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-docker-to-azure-app-service
> fix: redeploy produciton docker image

- sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
disable hovered feature state for admin tool since the geometry is different from electricity data's admin
> fix: disabled hovered feature state for dashboard

- sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
- sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte
- sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSliderControl.svelte
Controlling the order of Maplibre Control in svelte component is not straightforward. I added isActive prop in the time slider control to switch visibility of the slider.
> fix: changed top-left controls order. show timeslider control first

- backends/k8s/pgtileserv/yaml/pgtileserv-deployment.yaml
I realized docker image for k8s has no longer upgraded while docker image in docker-compose.yml was upgraded by renovate
> chore: upgraded pg_tileserv docker to 20240614

- .changeset/strong-kangaroos-trade.md
- packages/undp-bulma/bulma.scss
realized select box needs color to be black in UNDP design.
> fix: set black color of border for bulma select to align with UNDP design.

- .changeset/calm-snails-dream.md
- sites/geohub/src/routes/(map)/dashboards/electricity/components/Charts.svelte
- sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte
- sites/geohub/src/routes/(map)/dashboards/electricity/constansts.ts
realized line chart does not include forecast data
> fix: add data from 2021 to 2030 to line charts on dashboard

- .changeset/fresh-wombats-attack.md
- sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
- sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
fixed size of preview map to 216x128px
> fix: fixed size of preview map in sidebar of storymap editor.

- .changeset/modern-pans-shout.md
- sites/geohub/src/components/pages/storymap/StorymapStyleSelector.svelte
> fix: show geohub map id in map selector if it is selected already

- .changeset/cyan-carrots-smoke.md
- packages/svelte-undp-components/src/lib/components/ModalTemplate.svelte
> fix: use h5 of undp-bulma for ModalTemplate title

- sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
- sites/geohub/src/routes/(map)/dashboards/ceei/components/LayerControl.svelte
- sites/geohub/src/routes/(map)/dashboards/ceei/stores/index.ts
- sites/geohub/src/routes/(map)/dashboards/ceei/utils/layerHelper.ts
global store variable is not safe, switched to use context api for map object.
> refactor: Use map context api instead of global store variable

- .changeset/olive-ways-try.md
- sites/geohub/src/components/pages/storymap/ImageUploader.svelte
- sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
- sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte
fixed Card tab design (except layer selection) according to the below wireframe
https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3474-5209&focus-id=3474-5492&m=dev
https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3474-5209&focus-id=3474-5388&m=dev
> fix: changed Card tab design of storymap editor

- .changeset/beige-hornets-flow.md
- .changeset/gentle-trainers-own.md
- packages/svelte-undp-design/src/lib/Switch/Switch.svelte
- sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
- sites/geohub/src/components/pages/storymap/StorymapChapterLayerEventEditor.svelte
- sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
- sites/geohub/src/lib/helper/getMapImageFromStyle.ts
- sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
fixes #3955 
- only update slide mini preview when user change setting 
- update all slides' preview in sidebar if user delete or duplicate the slide
I switched to use context api with writable store instead of prop to reduce reactivitiy
> fix: only update the slide mini preview in sidebar which is updated by slide setting.

- .changeset/short-apples-exercise.md
- sites/geohub/src/components/pages/storymap/MapLocationSelector.svelte
- sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
- sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
in the mini preview of sidebar, check whether actual chapter object has been changed. if not changed, never trigger flag to update map image.
previously, when user click a chapter, it updated map image even it is not changed. now improved (I believe!)
> fix: only update preview in sidebar if chapter has any changes.

- .changeset/healthy-lemons-rest.md
- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/lib/server/SvgLegendCreator.ts
- sites/geohub/src/lib/server/helpers/clipSpriteServer.ts
- sites/geohub/src/lib/server/helpers/generateLegendFromStyle.ts
fixes #3979
I found a way to use pngjs instead of image-clipper with node-canvas (asked chatgpt to write code). pngjs has no dependencies, it should work
also fixed some bugs on legend api
> fix: use pngjs to crop sprite image instead of using image-clipper with node-canvas

- .changeset/tidy-jokes-compare.md
- packages/svelte-maplibre-storymap/src/lib/MaplibreLegendControl.svelte
- packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
In mobile, legend can be hidden as default, so it does not interrupt users to see stories.
> fix: collapse storymap legend in small screen as default

- .changeset/nine-lobsters-chew.md
- packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
> fix: when users go back to storymap header, restore all style and legend setting to be initial state.

- .changeset/wet-ants-wonder.md
- sites/geohub/src/routes/(map)/dashboards/electricity/components/AnalyzeBivariate.svelte
- sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte
previously, raster layer was still shown when users switch to the third menu. I just simply set visibility: none for raster layer. When second menu component is mounted, it will recreate new raster.
> fix: hide EA raster layer when show AnalyzeBivariate component.

- .changeset/fluffy-islands-draw.md
- packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
- packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
- sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte
> fix: removed max-height from storymap slide card content itself, but added max-height for storymap editor preview.

- .changeset/dry-candles-carry.md
- sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
- sites/geohub/src/lib/config/AppConfig/DatasetSearchQueryParams.ts
- sites/geohub/src/lib/server/db.ts
- sites/geohub/src/lib/server/helpers/createDatasetSearchWhereExpression.ts
- sites/geohub/src/routes/(app)/data/+page.server.ts
fixes #4234 
I changed behaviour a little bit
- dataset tab
- when I select private (my name), show private + organization + public
- when I select organisation (UNDP), show organization only
- when I select public, show public only
- my data tab
- the above conditions which signed user have permission (read, write or owner)
- non-signed user
- only show public
> fix: fixed bug of dataset searching when access level is selected.

- .changeset/lovely-turkeys-behave.md
- sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
I saw warning message that registered so many pubsub event listener. fixed to only register listener for in progress status
> fix: only register pubsub listener when status is not in progress

- .changeset/quiet-hotels-report.md
- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/components/pages/map/layers/vector/VectorFilter.svelte
- sites/geohub/src/lib/helper/expression2cql.ts
fixes #4269
fixes #4271
fixes #4270
- fix: fixed bugs of restoring state of vector filter.
- fix: restore not in conditions when editor is reopened.
- fix: restore OR condition correctly at VectorFilter.
- fix: dynamically apply AND/OR change to filter.
> fix: fixed bugs of restoring state of vector filter.

- .changeset/witty-knives-invite.md
- sites/geohub/src/routes/api/settings/+server.ts
fixes #4280
fix: previously user settings are remained even after user sign out. It was occured by that Object.assign update DefaultUserConfig variable in nodejs side. Now copied object is passed to Object.assign to prevent default value is changed.
> fix: previously user settings are remained even after user sign out. copied object is passed to Object.assign to prevent default value is changed.

- .changeset/fluffy-cheetahs-brake.md
- sites/geohub/src/lib/server/helpers/getStyleById.ts
If a public style includes organization level datasets, datasets will be removed from maps even if signed user is same organization domain of creator. I fixed this issue by checking signed in user domain and creator domain.
> fix: fixed bug of removing dataset from style.json if dataset access level is orgnaization and signed user is same organization domain

- .changeset/strange-pears-sort.md
- sites/geohub/src/routes/api/datasets/[id]/style/[layer]/[type]/+server.ts
there was a bug not renewing sas token for saved default style, thus some datasets which default style was saved 1 year ago had 403 error for both pmtiles and cog.
In default style endpoint, now sas url is renewed
> fix: renew azure sas token for saved default style.

- .changeset/wet-apples-swim.md
- packages/svelte-undp-components/package.json
- packages/svelte-undp-design/package.json
- pnpm-lock.yaml
because there were sveltekit and svelte in dependencies at both packages, this seems blocking to upgrade svelte to v5 in geohub and static api.
> fix: move sveltekit and svelte from dependencies to devDependencies.

- .changeset/blue-dragons-grow.md
- sites/geohub/src/components/pages/data/datasets/DatasetPreview.svelte
> fix: hide layer preview setting if only a line layer in a dataset.

- .changeset/proud-pots-look.md
- sites/geohub/drizzle/meta/_journal.json
- sites/geohub/src/lib/server/schema.ts
because the bug of drizzle, `geometry('Polygon', 4136)` is turned into `geometry('Point')` and, srid will be dropped always. I changed to use custom data type to avoid this bug for time being until it will be fixed in drizzle
> fix: fixed drizzle schema.ts to use customType for geometry columns.

- .changeset/metal-rice-prove.md
- sites/geohub/src/lib/server/helpers/getStyleById.ts
I found when we fetch style, style GET endpoint changed vector layer position from original one.
> fix: fixed bug of changing symbol layer order when style is fetched.

- .changeset/tough-poems-give.md
- sites/geohub/src/lib/server/helpers/getStyleById.ts
improved logic of updating style from latest base map. Previously it always changes layer style even no changes. Now only changes if layers are different from latest base style
> fix: improved logic to update saved map's base style from the latest if any different is presented

- .changeset/old-taxis-cover.md
- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/components/pages/map/Map.svelte
looks like v2 has issue in geohub. there is weird error in local
```
TypeError: Class extends value undefined is not a constructor or null
at $r (/Users/j_igarashi/Documents/git/UNDP-Data/geohub/node_modules/.pnpm/@maptiler+geocoding-control@2.0.1_maplibre-gl@4.7.1_ol@10.2.1_react@18.3.1_svelte@4.2.19/node_modules/@maptiler/src/MapLibreBasedGeocodingControl.ts:242:47)
at /Users/j_igarashi/Documents/git/UNDP-Data/geohub/node_modules/.pnpm/@maptiler+geocoding-control@2.0.1_maplibre-gl@4.7.1_ol@10.2.1_react@18.3.1_svelte@4.2.19/node_modules/@maptiler/src/maplibregl.ts:16:51
at async instantiateModule (file:///Users/j_igarashi/Documents/git/UNDP-Data/geohub/sites/geohub/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5)
```
Refer to …
> fix: downgrade maptiler geocoder to 1.4.1

- .changeset/proud-teachers-agree.md
- packages/svelte-undp-components/package.json
- pnpm-lock.yaml
- sites/geohub/src/lib/RasterTileData.ts
- sites/geohub/vite.config.ts
date-picker-svelte should be 2.12.1 with svelte 4. 2.14 is svelte 5 and cannot be used in geohub (svelte 4)
> fix: downgraded @undp-data/date-picker-svelte to 2.12.1 since geohub is still svelte 4, and it has issue of using svelte 5 component

- .changeset/thin-tigers-invite.md
- packages/svelte-undp-components/src/lib/util/getIntervalList.ts
In some cases, getIntervalList returns array with duplicated number, and maplibre complains about it. For instance, google/microsoft open building data's confidence field has quite tight range of values and chroma produces duplicated array for quantile and logarithmic (same for jenks of natural breaks). I decided to remove duplicated values from array in this function.
Because of this, sometimes only 2 or 3 classes can be produced even users want to make 5 classes. but I feel this can be better other than aligning user selected number of classes somehow.
> fix: sometimes there might be same values in array. remove duplicated values from intervalList.

- .changeset/curly-kids-prove.md
- sites/geohub/src/components/pages/map/data/DataCard.svelte
- sites/geohub/src/components/pages/map/data/DataVectorCard.svelte
- sites/geohub/src/components/pages/map/data/DataView.svelte
only create maplibre object when accordion is expanded. otherwise, browser delete oldest maplibre object including main map
> fix: fixed bug of creating too many webgl object in data tab.

- .changeset/tall-spoons-invent.md
- packages/svelte-undp-design/src/lib/Header/Header.svelte
- sites/geohub/src/components/header/Header.svelte
I realized custom slot using name with `-` will have issue when use snippet of svelte 5
> fix: renamed header slot name from custom-button to customButton.

- .changeset/few-bikes-look.md
- sites/geohub/src/lib/server/helpers/getStyleById.ts
previously only checked layers by layer ID (but not by children's ids). I changed to filter geohub layers by source ids. now it should be ok.
> fix: fixed bug of not returning label layer from /style/{id} endpoint

- .changeset/smart-brooms-explain.md
- sites/geohub/src/routes/(app)/+page.svelte
> fix: get only public storymap (max 4 items) for landing page

- .changeset/strange-singers-pay.md
- sites/geohub/src/routes/api/stac/[id]/[collection]/products/+server.ts
- sites/geohub/src/routes/api/stac/[id]/[collection]/products/[product_id]/+server.ts
product get endpoints should be allowed to access from unsigned users
> fix: allow unsigned users to access stac product api to get information.

- .changeset/witty-ears-shake.md
- sites/geohub/src/lib/RasterTileData.ts
- sites/geohub/src/lib/server/defaultStyle/RasterDefaultStyle.ts
- sites/geohub/src/lib/server/helpers/createDatasetLinks.ts
In maplibre, coordinates to fitBounds have to be LngLat. However, the latest titiler stop providing bounds in LngLat system from /info and /statistics. Instead, `/bounds` endpoint now has `crs` option. I fixed to use `/bounds` endpoint to fetch lng lat bounds for metadata.
> fix: use  to fetch bounds info in LngLat coordinates since the latest titiler does not return LngLat bounds from /info and /statistics.

- pnpm-lock.yaml
- sites/geohub/package.json
Reverts UNDP-Data/geohub#4690
there is error of `Uncaught ReferenceError: BaseChart is not defined`
> Revert "chore(deps): update dependency @carbon/charts-svelte to v1.22.8"

- pnpm-lock.yaml
- sites/static-image-api/package-lock.json
Reverts UNDP-Data/geohub#4708
after merging this, when I execute `pnpm dev` locally, it shows weird error in vite for svelte-carousel and svelte-file-dropzone.
> Revert "chore(deps): lock file maintenance"

- renovate.json
lock file maintenance PR by renovate sometimes break GeoHub, thus I am going to remove it from renovate
> chore: removed lock file maintenance setting from renovate.json

- .github/workflows/ci.yml
I found there are errors for azure-blob-storage-upload in our github actions
> ci: put version for azure-blob-storage-upload instead of using main

- pnpm-lock.yaml
- sites/geohub/package.json
Reverts UNDP-Data/geohub#4766
it works locally, but after deploying to AppService, it still has same error `_Uncaught ReferenceError: BaseChart is not defined` in production. Let me revert it
> Revert "chore: upgrade carbon/charts-svelte"

- backends/k8s/cert-manager/scripts/install.sh
- backends/k8s/cert-manager/yaml/cloudflare-apikey-secret.yaml
- backends/k8s/cert-manager/yaml/le-cluster-issuer.yaml
- backends/k8s/cert-manager/yaml/zerossl-cluster-issuer.yaml
Our Kube cluster's cert issuers used cloudflare API token to validate the undpgeohub domain. The token is valid cca 2 years and has just expired. As a result, we have switched to using Global Key instead of token  
> switched to cloudflare API key from token

- .changeset/healthy-lemons-shop.md
- .changeset/long-roses-eat.md
- packages/svelte-undp-components/src/lib/components/titiler/RasterRescale.svelte
- packages/svelte-undp-components/src/lib/components/ui/Slider.svelte
- sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
- sites/geohub/src/components/pages/map/layers/raster/RasterLegend.svelte
- sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
- sites/geohub/src/lib/RasterTileData.ts
- sites/geohub/src/lib/server/SvgLegendCreator.ts
- sites/geohub/src/lib/server/defaultStyle/RasterDefaultStyle.ts
- sites/geohub/src/lib/server/helpers/createDatasetLinks.ts
- fix: fixed bug of not showing scaled raster tile correctly. always use unscale=true for titiler now.
- fix: fixed too much reactivity caused by binding props in Slider and RasterRescale components.
for titiler, we can always enable `unscale=true`. this can work for both scaled and unscaled dataset. that is what I fixed for titiler. but stats from `info` is always unscaled stats, that means we must use min/max from `statistics` endpoint with `unscale=true`
> fix: fixed bug of not showing scaled raster tile correctly. always use unscale=true for titiler now.

- .github/workflows/release.yml
I believe this bug of changeset was caused by pnpm v10 upgrade. I could have reproduced same with local. I believe this can fix changeset CI
> ci: add --shamefully-hoist to pnpm install for changeset release job

- .changeset/weak-dancers-listen.md
- sites/geohub/src/lib/server/helpers/createDatasetLinks.ts
I found mosaicjson feature of Stac API and Catalog does not work because I missed to add tilematrixid to titiler mosaicjson endpoint when we upgrade titiler to v0.19 last time.
> fix: add tilematrixid (WebMercatorQuad) for mosaicjson tilejson endpoint.

- .changeset/itchy-ads-check.md
- sites/geohub/src/lib/server/defaultStyle/RasterDefaultStyle.ts
this fix is actually related to https://github.com/UNDP-Data/geo-cogserver/issues/55
if tilejson was given for titiler, and protocol is http, force replacing it to https.
> fix: replace http to https for titiler tilejson api's tile url if it starts with http, but not localhost.

- .changeset/five-suits-invent.md
- sites/geohub/src/lib/server/defaultStyle/RasterDefaultStyle.ts
fixes mosaicjson layer to have incorrect bounds for raster source
> fix: update bounds for mosaicjson if tilejson.bounds property is available

- .changeset/silver-cows-add.md
- sites/geohub/src/lib/server/StorymapManager.ts
- sites/geohub/src/lib/server/api/storymaps/GET.ts
I realized chapters are not needed for search page of storymaps. chapters tend to have many contents and images which potentially make the api response slow down. removing chapters from search result can improve the page performance significantly.
> fix: search exclude chapters to improve storymap portal performance

- .changeset/stale-rice-burn.md
- sites/geohub/src/components/pages/storymap/MarkdownEditor.svelte
- sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
- sites/geohub/src/components/pages/storymap/StorymapFooterEdit.svelte
fixes #4872
I think `key` statement made the bug of recreating markdown editor.
also fixed reactivity of MarkdownEditor to use onchange event.
> fix: fixed reactivity of MarkdownEditor component

- .changeset/little-news-film.md
- sites/geohub/src/routes/(app)/dashboards/ceei/+page@.svelte
- sites/geohub/src/routes/(app)/dashboards/ceei/components/DropdownSearch.svelte
fixes #4937
fix: previously simulation button on CEEI dashboard was disabled when the page is shown. Now the button is enabled on initial page shown. This bug was caused by svelte 5 migration which did not bind layer variable to the component correctly.
> fix: previously simulation button on CEEI dashboard was disabled when the page is shown.

- .changeset/chilled-fishes-attack.md
- pnpm-lock.yaml
- sites/geohub/package.json
- sites/geohub/src/routes/(app)/dashboards/ceei/+page@.svelte
- sites/geohub/src/routes/(app)/dashboards/electricity/+page@.svelte
- sites/geohub/src/routes/(app)/dashboards/zanzibar/+page@.svelte
- sites/geohub/src/routes/(app)/maps/[[id]]/edit/+page.svelte
- sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
fixes #4942
- added GlobeControl for map editor, map viewer and electricity dashboard
- deleted @watergis/maplibre-gl-sky
- save style when projection is changed at `projectiontransition` event.
- I confirmed static api works without error (it will print map as mercator map, and I think this is ok for static api)
We still need to add globe control functionality for storymap, but that can be done in another PR.
> feat: added maplibre globe mode to GeoHub

- .changeset/odd-jars-shake.md
- sites/geohub/src/routes/(app)/+page.server.ts
- sites/geohub/src/routes/(app)/tools/+page.server.ts
Currently, titiler is down because something happened for SSL certificate. In landing page and tools page, +page.server.ts access titiler /algorithms api to fetch the list of tools, this fetch fails and bring the whole page down.
> fix: add try catch to handle error when titiler is down, so landing page can be shown all the time

- .changeset/hip-toys-itch.md
- sites/geohub/src/lib/VectorTileData.ts
- sites/geohub/src/lib/server/api/datasets/[id]/preview/style.json/GET.ts
- sites/geohub/src/lib/server/api/datasets/[id]/style/[layer]/[type]/DELETE.ts
- sites/geohub/src/lib/server/api/datasets/[id]/style/[layer]/[type]/GET.ts
- sites/geohub/src/lib/server/api/datasets/[id]/style/[layer]/[type]/POST.ts
- sites/geohub/src/lib/server/api/datasets/style/[layer]/[type]/POST.ts
fixes #4987
This bug was caused by migration to sveltekit-api.
https://github.com/UNDP-Data/geohub/blob/54d39073bec29ce3595425d0aedc633410a58629/sites/geohub/src/lib/server/api/datasets/style/%5Blayer%5D/%5Btype%5D/POST.ts#L16-L21
I forgot to add `fill-extrusion` for layer type, and svektelit-api throw error 
> fix: added fill-extrusion layer type for default style endpoint.

- .changeset/wet-peas-grin.md
- packages/svelte-undp-components/src/lib/components/ui/NumberInput.stories.ts
- packages/svelte-undp-components/src/lib/components/ui/NumberInput.svelte
fixes #5000
I added debounce for NumberInput. Now it seems working good
> fix: set debounce for textbox of NumberInput component to allow users manually change value correctly.

- .changeset/four-cougars-hug.md
- sites/geohub/src/lib/server/StorymapManager.ts
> fix: fixed a bug not returning is_star and permission properties from /api/storymaps endpoint.

- documentation/docs/js/translate.js
- documentation/mkdocs.yml
- documentation/theme_overrides/home.html
- documentation/theme_overrides/partials/footer.html
added google translate widget for UN public languages at least (for temporary before we implement real i18n)
> docs: add google translate widget to the bottom of documentation page

- backends/k8s/stac-pipeline/README.md
- backends/k8s/stac-pipeline/yaml/deployment.yaml
I added some settings to ensure deleting jobs after completion
https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/#updating-ttl-for-finished-jobs
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#jobs-history-limits
> added settings to ensure deleting scaled cron job after completion

- .changeset/olive-mails-tan.md
- packages/style-switcher/package.json
- packages/style-switcher/src/lib/index.ts
- pnpm-lock.yaml
fixes #5126
- improved the logic of comparing style json
- only compare layers which exists in original style json sources + compare background layer
- some layer may have empty properties added, thus use omitBy(A, isEmpty) to remove empty properties first
- Instead of using stringify, use isEqual method of lodash to compare layer object.
> fix: fixed the logic of selecting current style as active style selected in the switcher. Previously, it did not consider they are the same style.

- .changeset/lovely-words-roll.md
- pnpm-lock.yaml
- sites/geohub/package.json
This PR upgrade the version of base map style package to add raster-dem source only for hillshade layer which can solve the issue raised by https://github.com/UNDP-Data/geohub/pull/5081
> fix: upgarded base style to v2.4.4 to add terririum-hillshade source only for hillshade layer.

- .changeset/smooth-ads-wave.md
- sites/geohub/src/lib/config/AppConfig/attribution.ts
In this PR:
I modified `getAttribution` function to add UNDP to the attribuiton as the storymaps are part of the UNDP's GeoHUB system.
UNDP is not attributed in any part of maps as there are no basemaps whose source is UNDP.
This PR will fix issue #5135 
> fix: add UNDP to attribution

- .changeset/funny-ads-serve.md
- sites/geohub/src/components/pages/map/layers/vector/TextField.svelte
- sites/geohub/src/components/pages/map/layers/vector/VectorLabelPanel.svelte
In this PR.
[x] Fix bug of showing labels of polygons which have been filtered out
> fix: applying filtering labels showing all labels instead of only filtered ones
